mfd: cs42l43: add REGMAP_IRQ requirement
The cs42l43 core uses devm_regmap_add_irq_chip(), so add REGMAP_IRQ
to what the core driver selects in order to provide this API.
This fixes a build error:

aarch64-linux-ld: drivers/mfd/cs42l43.o: in function `cs42l43_boot_work':
cs42l43.c:(.text+0x19d4): undefined reference to `devm_regmap_add_irq_chip'

Fixes: ace6d1448138 ("mfd: cs42l43: Add support for cs42l43 core driver")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Charles Keepax <ckeepax@opensource.cirrus.com>
Cc: James Schulman <james.schulman@cirrus.com>
Cc: David Rhodes <david.rhodes@cirrus.com>
Cc: Richard Fitzgerald <rf@opensource.cirrus.com>
Cc: alsa-devel@alsa-project.org
Cc: patches@opensource.cirrus.com
Cc: Lee Jones <lee@kernel.org>