drm/nouveau/disp: fix incompatible types in subtraction
This patch fixes the following sparse error:

drivers/gpu/drm/nouveau/dispnv50/disp.c:134:31: error: subtraction of different types can't work (different address spaces)
drivers/gpu/drm/nouveau/dispnv50/disp.c:197:31: error: subtraction of different types can't work (different address spaces)

In struct nvif_push, "cur" is of type u32 *, whereas
dmac->_push.mem.object.map.ptr is of type void __iomem *.
Converting push->cur to u32 __iomem * to fix above sparse
error.

Fixes: 9cf06d6ef7fd ("drm/nouveau/disp: fix cast removes address space of expression warnings")
Signed-off-by: Chen Jiahao <chenjiahao16@huawei.com>