rcu: Include torture_sched_setaffinity() declaration
The prototype for torture_sched_setaffinity() moved to a
different header, which needs to be included from update.c
to avoid this W=1 warning:

kernel/rcu/update.c:529:6: error: no previous prototype for 'torture_sched_setaffinity' [-Werror=missing-prototypes]
  529 | long torture_sched_setaffinity(pid_t pid, const struct cpumask *in_mask)

Fixes: 521ec59e5453e ("torture: Move rcutorture_sched_setaffinity() out of rcutorture")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
Signed-off-by: Paul E. McKenney <paulmck@kernel.org>