amdgpu: lockdep: move temporary mutexes off stack
In randconfig builds, the newly added function frequently exceeds
the limit for stack frames, like:

drivers/gpu/drm/amd/amdgpu/amdgpu_lockdep.c:84:5: error: stack frame size (1312) exceeds limit (1280) in 'amdgpu_lockdep_init' [-Werror,-Wframe-larger-than]

Change this to use static allocation for the locks to reduce
this at the expense of a slightly larger driver binary.

Fixes: 1d0f5838b126 ("drm/amdgpu: Add lockdep annotations for lock ordering validation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>