linux-next: build failure in the vfs tree
Hi all,

After merging the vfs tree, today's linux-next build (arm64 defconfig)
failed like this:

/tmp/next/build/fs/nsfs.c:582:27: error: initialization of 'struct file * (*)(const struct path *, unsigned int)' from incompatible pointer type 'struct file * (*)(struct path *, unsigned int)' [-Wincompatible-pointer-types]
  582 |         .open           = nsfs_export_open,
      |                           ^~~~~~~~~~~~~~~~
/tmp/next/build/fs/nsfs.c:582:27: note: (near initialization for 'nsfs_export_operations.open')

Caused by an interaction with commit

  06c4ff965e95b ("nsfs: support file handles")

from the vfs-brauner tree and

  efa6ab3688a54 ("export_operations->open(): constify path argument")

I've fixed it up as below and can carry as required.

From 56e625f1566ee6e3940c625a393b3b4e75806b3f Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Mon, 15 Sep 2025 21:03:13 +0100
Subject: [PATCH] nsfs: Fix up merge

Signed-off-by: Mark Brown <broonie@kernel.org>