bug: Mark __warn_printf() with __printf() attribute
__warn_printf() is using printf() type of format, and compiler
is not happy about them as is:

lib/bug.c:187:25: error: function ‘__warn_printf’ might be a candidate for ‘gnu_printf’ format attribute [-Werror=suggest-attribute=format]
  187 |                         vprintk(fmt, *args);
      |                         ^~~~~~~

Fix the compilation errors by adding __printf() attribute.

Fixes: 5c47b7f3d1a9 ("bug: Add BUG_FORMAT_ARGS infrastructure")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>