regulator: rtq2208: remove unused rtq2208_regulator_ldo_ops
After the recent rework, the structure is no longer referenced
anywhere and causes a build time warning:

drivers/regulator/rtq2208-regulator.c:222:35: error: 'rtq2208_regulator_ldo_ops' defined but not used [-Werror=unused-const-variable=]
  222 | static const struct regulator_ops rtq2208_regulator_ldo_ops = {
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~

Remove it to get a clean build again.

Fixes: 38bcec0e7cbb ("regulator: rtq2208: Fix LDO discharge register and add vsel setting")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>