power: supply: intel_dc_ti_battery: fix 64bit divisions
On 32bit builds, I get:
ERROR: modpost: "__udivdi3" [drivers/power/supply/intel_dc_ti_battery.ko] undefined!

This is due to 64bit ktime divisions. Fix both by using div_u64().

Signed-off-by: Jiri Slaby (SUSE) <jirislaby@kernel.org>
Fixes: 8c5795fe5527 ("power: supply: Add new Intel Dollar Cove TI battery driver")