selftests: pidfd: add missing sys/mount.h include in pidfd_fdinfo_test.c
Fix compile on openSUSE Tumbleweed (gcc-14.2.1, glibc-2.40):
  - add missing sys/mount.h include

Fixes:

  pidfd_fdinfo_test.c: In function ‘child_fdinfo_nspid_test’:
  pidfd_fdinfo_test.c:230:13: error: implicit declaration of function ‘mount’ [-Wimplicit-function-declaration]
    230 |         r = mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, 0);
        |             ^~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>