selinux: use explicit 64-bit division
On 32-bit targets, the division of a 64-bit integer by 33 causes a
function call:

arm-linux-gnueabi-ld: security/selinux/selinuxfs.o: in function `sel_read_class':
selinuxfs.c:(.text+0xdcc): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabi-ld: security/selinux/selinuxfs.o: in function `sel_read_perm':
selinuxfs.c:(.text+0xed0): undefined reference to `__aeabi_uldivmod'

Replace this with an explicit call to div_u64() and div_u64_rem() to
annotate that these are potentially very slow.

Fixes: fc68b6a45f16 ("selinux: convert selinuxfs inode numbers from unsigned long to u64")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>