csky/mm: fix build errors cause by folio flags changes
Kernel compilation on csky fails because csky was not updated during
conversion of folio flags to memdesc_flags_t:

arch/csky/abiv2/inc/abi/cacheflush.h: In function 'flush_dcache_folio':
arch/csky/abiv2/inc/abi/cacheflush.h:23:39: error: passing argument 2 of 'const_test_bit' from incompatible pointer type [-Werror=incompatible-pointer-types]
   23 |         if (test_bit(PG_dcache_clean, &folio->flags))
      |                                       ^~~~~~~~~~~~~
      |                                       |
      |                                       memdesc_flags_t *
include/linux/bitops.h:47:24: note: in definition of macro 'bitop'
   47 |          const##op(nr, addr) : op(nr, addr))
      |                        ^~~~
arch/csky/abiv2/inc/abi/cacheflush.h:23:13: note: in expansion of macro 'test_bit'
   23 |         if (test_bit(PG_dcache_clean, &folio->flags))
      |             ^~~~~~~~

Update references of folio->flags in arch/csky.

Fixes: 53fbef56e07d ("mm: introduce memdesc_flags_t")
Signed-off-by: Mike Rapoport (Microsoft) <rppt@kernel.org>