of: rexport of_find_next_cache_node()
This function is now called from a cpufreq driver, but that breaks the
build when the caller is in a loadable module, because of a missing
export:

ERROR: modpost: "of_find_next_cache_node" [drivers/cpufreq/qcom-cpufreq-nvmem.ko] undefined!

Export this as a GPL-only symbol, like the other related functions in
this file.

Fixes: 7683a63c08ff5 ("cpufreq: qcom-nvmem: create L2 cache device")
Fixes: a3e31b4588443 ("of: Move definition of of_find_next_cache_node into common code.")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>