rtc: stm32: Use NOIRQ_SYSTEM_SLEEP_PM_OPS()
If CONFIG_PM_SLEEP=n (e.g. m68k/allmodconfig):

    drivers/rtc/rtc-stm32.c:904:12: error: ‘stm32_rtc_resume’ defined but not used [-Werror=unused-function]
      904 | static int stm32_rtc_resume(struct device *dev)
	  |            ^~~~~~~~~~~~~~~~
    drivers/rtc/rtc-stm32.c:894:12: error: ‘stm32_rtc_suspend’ defined but not used [-Werror=unused-function]
      894 | static int stm32_rtc_suspend(struct device *dev)
	  |            ^~~~~~~~~~~~~~~~~

Indeed, the previous change mixed up the semantics between
SET_NOIRQ_SYSTEM_SLEEP_PM_OPS() and NOIRQ_SYSTEM_SLEEP_PM_OPS().
Fix this by using the modern NOIRQ_SYSTEM_SLEEP_PM_OPS() instead.

Reported-by: noreply@ellerman.id.au
Fixes: a69c610e13e2b2de ("rtc: stm32: remove incorrect #ifdef check")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>