ice: fix building withouto XDP
The newly added function fails to build when struct xsk_cb_desc is
not defined:

drivers/net/ethernet/intel/ice/ice_base.c: In function 'ice_xsk_pool_fill_cb':
drivers/net/ethernet/intel/ice/ice_base.c:525:16: error: variable 'desc' has initializer but incomplete type

Hide this part in the same #ifdef that controls the structure definition.

Fixes: d68d707dcbbf ("ice: Support XDP hints in AF_XDP ZC mode")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>