drm/efidrm: ensure screen_base is initialized
clang points out that there is a code path that leads to undefined behavior:

drivers/gpu/drm/sysfb/efidrm.c:353:11: error: variable 'screen_base' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
  353 |         else if (mem_flags & EFI_MEMORY_WB)
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~

Add the missing initialization.

Fixes: 32ae90c66fb6 ("drm/sysfb: Add efidrm for EFI displays")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>