RDMA/core: Remove _ib_copy_validate_udata_in() and _ib_respond_udata() stubs
After commit 65b044cee9fb ("RDMA/core: Move the _ib_copy_validate_udata*
functions to ib_core_uverbs"), builds without INFINIBAND_USER_ACCESS
enabled fail with:

  drivers/infiniband/core/ib_core_uverbs.c:433:5: error: redefinition of '_ib_copy_validate_udata_in'
    433 | int _ib_copy_validate_udata_in(struct ib_udata *udata, void *req,
        |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
  In file included from include/rdma/uverbs_std_types.h:10,
                   from drivers/infiniband/core/uverbs.h:49,
                   from drivers/infiniband/core/ib_core_uverbs.c:10:
  include/rdma/uverbs_ioctl.h:961:19: note: previous definition of '_ib_copy_validate_udata_in' with type 'int(struct ib_udata *, void *, size_t,  size_t)' {aka 'int(struct ib_udata *, void *, long unsigned int,  long unsigned int)'}
    961 | static inline int _ib_copy_validate_udata_in(struct ib_udata *udata, void *req,
        |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
  drivers/infiniband/core/ib_core_uverbs.c:483:5: error: redefinition of '_ib_respond_udata'
    483 | int _ib_respond_udata(struct ib_udata *udata, const void *src, size_t len)
        |     ^~~~~~~~~~~~~~~~~
  include/rdma/uverbs_ioctl.h:968:19: note: previous definition of '_ib_respond_udata' with type 'int(struct ib_udata *, const void *, size_t)' {aka 'int(struct ib_udata *, const void *, long unsigned int)'}
    968 | static inline int _ib_respond_udata(struct ib_udata *udata, const void *src,
        |                   ^~~~~~~~~~~~~~~~~

Remove the stubs and adjust the prototypes for _ib_respond_udata() and
_ib_copy_validate_udata_in(), as they will always be available when
INFINIBAND is enabled.

Fixes: 65b044cee9fb ("RDMA/core: Move the _ib_copy_validate_udata* functions to ib_core_uverbs")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>