staging: sm750: Fix missing config in Kconfig
Fixes the following compilation error:

ERROR: modpost: "fb_io_read" [drivers/staging/sm750fb/sm750fb.ko] undefined!
ERROR: modpost: "fb_io_write" [drivers/staging/sm750fb/sm750fb.ko] undefined!
ERROR: modpost: "fb_io_mmap" [drivers/staging/sm750fb/sm750fb.ko] undefined!

Signed-off-by: Fabricio Gasperin <fgasperin@lkcamp.dev>