usb: fotg210: fix link error for CONFIG_USB=n
Calling usb_hcd_platform_shutdown() is not possible if CONFIG_USB
is disabled:

arm-linux-gnueabi-ld: drivers/usb/fotg210/fotg210-core.o: in function `fotg210_shutdown':
fotg210-core.c:(.text+0x40): undefined reference to `usb_hcd_platform_shutdown'

Move this call into the hcd file to ensure this is only used
when USB host mode is actually available.

Fixes: 7dbc2e1ba8fd ("usb: fotg210: use the common EHCI core")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>