perf script: Fix build by removing unused evsel_script()
The evsel_script() function is unused since the linked commit. Fix the
build by removing it.

Fixes the following compilation error:

  builtin-script.c:347:36: error: unused function 'evsel_script' [-Werror,-Wunused-function]
  static inline struct evsel_script *evsel_script(struct evsel *evsel)
                                     ^
Fixes: 3622990efaab ("perf script: Change metric format to use json metrics")
Signed-off-by: James Clark <james.clark@linaro.org>