selftests/bpf: Fix cross-compile issue for some files and a static compile issue for "-lzstd"
1. Fix cross-compile issue for some files:
[Issue]
When cross-compiling bpf selftests for arm64 on x86_64 host, the following error occurs:
progs/loop2.c:20:7: error: incomplete definition of type 'struct user_pt_regs'
   20 |                 if (PT_REGS_RC(ctx) & 1)
      |                     ^~~~~~~~~~~~~~~

There are same error in files: loop1.c, loop2.c, loop3.c, loop6.c ???

[Reason]
On arm64, in file bpf_tracing.h, we use userspace's user_pt_regs,
which is defined in "linux/ptrace.h".
We include the header file by adding "-idirafter /usr/include" for "CLANG_CFLAGS".

However, during cross-compiling, "linux/ptrace.h" is based on x86_64
and has no definition of "struct user_pt_regs".

[Fix]
Thus, to fix this issue, we include the Linux source tree's header file directory.

2. Fix static compile issue for "-lzstd":
[Issue]
By running the command "LDLIBS=-static LDFLAGS=--sysroot=/aarch64-linux-gnu/libc ./vmtest.sh -s -- ./test_progs",
during static cross-compiling, an error occurs:
/aarch64-linux-gnu/bin/ld: aarch64-linux-gnu/libc/usr/lib/libelf.a(elf_compress.o): in function `__libelf_compress':
(.text+0xec): undefined reference to `ZSTD_createCCtx'
/aarch64-linux-gnu/bin/ld: (.text+0xf0): undefined reference to `ZSTD_createCCtx'
...

[Fix]
For static compile, add "LDLIBS += -lzstd".

Signed-off-by: Lin Yikai <yikai.lin@vivo.com>