vmwgfx: allow building with CONFIG_HAS_IOPORT disabled
The older version of the vmwgfx driver requires port I/O in order to work:

In file included from arch/arm64/include/asm/io.h:298,
                 from drivers/gpu/drm/vmwgfx/vmwgfx_kms.c:28:
drivers/gpu/drm/vmwgfx/vmwgfx_drv.h: In function 'vmw_read':
include/asm-generic/io.h:626:15: error: call to '_outl' declared with attribute error: outl() requires CONFIG_HAS_IOPORT
  626 | #define _outl _outl
include/asm-generic/io.h:663:14: note: in expansion of macro '_outl'
  663 | #define outl _outl
      |              ^~~~~
drivers/gpu/drm/vmwgfx/vmwgfx_drv.h:692:17: note: in expansion of macro 'outl'
  692 |                 outl(offset, dev_priv->io_start + SVGA_INDEX_PORT);
      |                 ^~~~

Change the version check to hardcode the v3 version and remove the PCI
ID for v2 in configurations that only support v3.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>