mm: slub: Wrap krealloc() __GFP_ZERO semantics diagram in literal code block
Sphinx reports htmldocs warnings:

Documentation/core-api/mm-api:40: ./mm/slub.c:4936: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]
Documentation/core-api/mm-api:40: ./mm/slub.c:4936: ERROR: Undefined substitution referenced: "--------". [docutils]

Fix the warning by wrapping krealloc() semantics diagram for __GFP_ZERO
in literal code block.

Fixes: 489a744e5fb1 ("mm: krealloc: clarify valid usage of __GFP_ZERO")
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>