crypto: qat - add missing header inclusion
On Wed, May 21, 2025 at 05:56:15AM +0100, Cabiddu, Giovanni wrote:
> On Tue, May 20, 2025 at 06:11:36PM +0200, Arnd Bergmann wrote:
> > From: Arnd Bergmann <arnd@arndb.de>
> >
> > Without this header, building the new driver fails with:
> >
> > In file included from drivers/crypto/intel/qat/qat_common/adf_gen6_shared.c:7:
> > drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h: In function 'adf_gen4_init_pf_pfvf_ops':
> > drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h:13:34: error: 'adf_pfvf_comms_disabled' undeclared (first use in this function)
> >    13 |         pfvf_ops->enable_comms = adf_pfvf_comms_disabled;
> >       |                                  ^~~~~~~~~~~~~~~~~~~~~~~
> >
> > Fixes: 17fd7514ae68 ("crypto: qat - add qat_6xxx driver")
> > Signed-off-by: Arnd Bergmann <arnd@arndb.de>
> Thanks Arnd. This occurs with CONFIG_PCI_IOV not set. Can this be added
> to the commit message?
>
> > ---
> >  drivers/crypto/intel/qat/qat_common/adf_gen2_pfvf.h | 1 +
> >  drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h | 1 +
> >  2 files changed, 2 insertions(+)
> >
> > diff --git a/drivers/crypto/intel/qat/qat_common/adf_gen2_pfvf.h b/drivers/crypto/intel/qat/qat_common/adf_gen2_pfvf.h
> > index a716545a764c..9efee0053f3a 100644
> > --- a/drivers/crypto/intel/qat/qat_common/adf_gen2_pfvf.h
> > +++ b/drivers/crypto/intel/qat/qat_common/adf_gen2_pfvf.h
> > @@ -4,6 +4,7 @@
> >  #define ADF_GEN2_PFVF_H
> >
> >  #include <linux/types.h>
> > +#include "adf_common_drv.h"
> >  #include "adf_accel_devices.h"
> NIT. Can this be in alphabetical order?

---8<---

From: Arnd Bergmann <arnd@arndb.de>
Subject: [PATCH] crypto: qat - add missing header inclusion

Without this header, the build of the new qat_6xxx driver fails when
CONFIG_PCI_IOV is not set:

    In file included from drivers/crypto/intel/qat/qat_common/adf_gen6_shared.c:7:
    drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h: In function 'adf_gen4_init_pf_pfvf_ops':
    drivers/crypto/intel/qat/qat_common/adf_gen4_pfvf.h:13:34: error: 'adf_pfvf_comms_disabled' undeclared (first use in this function)
       13 |         pfvf_ops->enable_comms = adf_pfvf_comms_disabled;
          |                                  ^~~~~~~~~~~~~~~~~~~~~~~

Fixes: 17fd7514ae68 ("crypto: qat - add qat_6xxx driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Giovanni Cabiddu <giovanni.cabiddu@intel.com>