sched/fair: Remove dead code which might prevent from building
Clang, in particular, is not happy about dead code:

kernel/sched/fair.c:5233:19: error: unused function 'cfs_rq_throttled' [-Werror,-Wunused-function]
 5233 | static inline int cfs_rq_throttled(struct cfs_rq *cfs_rq);
      |                   ^~~~~~~~~~~~~~~~
1 error generated.

kernel/sched/fair.c:6736:19: error: unused function 'cfs_rq_throttled' [-Werror,-Wunused-function]
 6736 | static inline int cfs_rq_throttled(struct cfs_rq *cfs_rq)
      |                   ^~~~~~~~~~~~~~~~
1 error generated.

Remove a leftover from the previous cleanup.

Fixes: fe8d238e646e ("sched/fair: Propagate load for throttled cfs_rq")
Fixes: eb962f251fbb ("sched/fair: Task based throttle time accounting")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>