media: platform: amd: avoid -Wformat-security warning
The newly added kthread_run() call passes a string variable as an sprintf()
style format, which gcc warns about when -Wformat-security is enabled:

drivers/media/platform/amd/isp4/isp4_subdev.c: In function 'isp4sd_start_resp_proc_threads':
include/linux/kthread.h:71:16: error: format not a string literal and no format arguments [-Werror=format-security]
   71 |         struct task_struct *__k                                            \
      |                ^~~~~~~~~~~
drivers/media/platform/amd/isp4/isp4_subdev.c:596:38: note: in expansion of macro 'kthread_run'
  596 |                 thread_ctx->thread = kthread_run(isp4sd_fw_resp_thread,
      |                                      ^~~~~~~~~~~

Use an indirect "%s" format to do this safely, avoiding the warning.

Fixes: 4e5e7a7ddb4a ("media: platform: amd: isp4 subdev and firmware loading handling added")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>