linux-next: build failure after merge of the bpf-next tree
Hi all,

After merging the bpf-next tree, today's linux-next build (x86_64_perf)
failed like this:

      CC      builtin-trace.o
    builtin-trace.c: In function ‘syscall_arg__strtoul_btf_enum’:
    builtin-trace.c:972:27: error: comparison of integer expressions of different signedness: ‘int’ and ‘__u32’ {aka ‘unsigned int’} [-Werror=sign-compare]
      972 |         for (int i = 0; i < btf_vlen(bt); ++i, ++be) {
          |                           ^
      CC      util/btf.o
    util/btf.c: In function ‘__btf_type__find_member_by_name’:
    util/btf.c:19:43: error: comparison of integer expressions of different signedness: ‘int’ and ‘__u32’ {aka ‘unsigned int’} [-Werror=sign-compare]
       19 |         for (i = 0, m = btf_members(t); i < btf_vlen(t); i++, m++) {
          |                                           ^

Caused by commit

    f7a6b9eaff3e ("bpf: Extend BTF UAPI vlen, kinds to use unused bits")

I've fixed it up like below, but please fix this in your tree as well.

Thanks,
Thierry