selftest/futex: Comment out test_futex_mpol
test_futex_mpol() is not called, resulting in

futex_numa_mpol.c:134:13: error: ‘test_futex_mpol’ defined but not used

if built with -Werror. Disable the function but keep it in case it was
supposed to be used.

Fixes: d35ca2f64272 ("selftests/futex: Refactor futex_numa_mpol with kselftest_harness.h")
Cc: André Almeida <andrealmeid@igalia.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>