wifi: iwlwifi: fix iwlmld-test link failure
If the driver is built-in but the test is in a loadable module, the symbols
are not exported, resulting in a link failure:

ERROR: modpost: "iwl_get_cmd_string" [drivers/net/wireless/intel/iwlwifi/mld/tests/iwlmld-tests.ko] undefined!
ERROR: modpost: "__iwl_dbg" [drivers/net/wireless/intel/iwlwifi/mld/tests/iwlmld-tests.ko] undefined!

Enable CONFIG_IWLWIFI_OPMODE_MODULAR in this configuration, to
make those symbols visible.

Fixes: d1e879ec600f ("wifi: iwlwifi: add iwlmld sub-driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>