tracing/timerlat: move interface_lock definition up
The definition was previously moved into an #ifdef block by
accident and now causes a build failure when CONFIG_TIMERLAT_TRACER
is disabled:

In file included from include/linux/seqlock.h:19,
                 from kernel/trace/trace_osnoise.c:20:
kernel/trace/trace_osnoise.c: In function 'osnoise_sleep':
kernel/trace/trace_osnoise.c:1631:21: error: 'interface_lock' undeclared (first use in this function); did you mean 'trace_clock'?
 1631 |         mutex_lock(&interface_lock);
      |                     ^~~~~~~~~~~~~~

Move it up some more to be outside of that #ifdef again.

Fixes: e6a53481da29 ("tracing/timerlat: Only clear timer if a kthread exists")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>