ASoC: es9356-sdca: add SND_SOC_SDCA dependencies
Without this, the driver fails to link:

x86_64-linux-ld: sound/soc/codecs/es9356.o:(.rodata+0x4208): undefined reference to `sdca_asoc_q78_put_volsw'

Fixes: 5d9cb740cd38 ("ASoC: es9356-sdca: Add ES9356 SDCA driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>