mm/gfp: cast GFP_ZONE_TABLE entries to long to avoid shift overflow
When a new zone is added to enum zone_type in mmzone.h, the existing
GFP_ZONE_TABLE macro causes a compile-time shift overflow:

  CC      arch/x86/kernel/asm-offsets.s
  In file included from ./include/linux/slab.h:16,
                   from ./include/linux/crypto.h:18,
                   from arch/x86/kernel/asm-offsets.c:9:
  ./include/linux/gfp.h: In function ‘gfp_zone’:
  ./include/linux/gfp.h:132:27: error: left shift count >= width of type [-Werror=shift-count-overflow]
    132 |         | (OPT_ZONE_DMA32 << (___GFP_MOVABLE | ___GFP_DMA32) * GFP_ZONES_SHIFT)\
        |                           ^~
  ./include/linux/gfp.h:157:14: note: in expansion of macro ‘GFP_ZONE_TABLE’
    157 |         z = (GFP_ZONE_TABLE >> (bit * GFP_ZONES_SHIFT)) &
        |

This can be reproduced by adding a new zone:

@@ -868,6 +868,7 @@ enum zone_type {
 #ifdef CONFIG_ZONE_DEVICE
        ZONE_DEVICE,
 #endif
+       ZONE_FOO,
        __MAX_NR_ZONES

 };

This happens because the left-hand side operands of the shifts inside GFP_ZONE_TABLE are enum zone_type, which is of type int. The shift is logically valid because it has been checked by 16 * GFP_ZONES_SHIFT > BITS_PER_LONG previously.

Fixed this by casting each value in GFP_ZONE_TABLE to type long.

Signed-off-by: Yankai Xu <815559068@qq.com>