rust: fwctl: replace `__pinned_init` with `raw_try_init`
Commit

  ea7da3116015 ("rust: treewide: replace `__pinned_init` with `raw_[try_]init`")

from the pin-init tree replaced the method before removing it, but commit

  e052daab94ee ("rust: introduce abstractions for fwctl")

from the fwctl tree added a new use.

Thus replace that one as well to fix this error in next-20260817:

    error[E0599]: no method named `__pinned_init` found for associated type `impl pin_init::PinInit<T, error::Error>` in the current scope
       --> rust/kernel/fwctl.rs:465:49
        |
    465 |                 match T::open(device, reg_data).__pinned_init(uctx_ptr) {
        |                                                 ^^^^^^^^^^^^^ method not found in `impl pin_init::PinInit<T, error::Error>`

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>