firmware: arm_scmi: Use modern PM ops
When building without CONFIG_PM_SLEEP (e.g., with hexagon or s390),
there is a warning because scmi_system_power_resume() is not used due to
how SET_SYSTEM_SLEEP_PM_OPS is defined:

  drivers/firmware/arm_scmi/scmi_power_control.c:363:12: error: 'scmi_system_power_resume' defined but not used [-Werror=unused-function]
    363 | static int scmi_system_power_resume(struct device *dev)
        |            ^~~~~~~~~~~~~~~~~~~~~~~~

Use the moderm SYSTEM_SLEEP_PM_OPS to resolve the warnings, which is
what SET_SYSTEM_SLEEP_PM_OPS ultimately expands to, so there is no
change in behavior.

Fixes: 9a0658d3991e ("firmware: arm_scmi: power_control: Ensure SCMI_SYSPOWER_IDLE is set early during resume")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>