EDAC: fix dev_set_name() format string
Passing a variable string as the format to dev_set_name() causes a W=1 warning:

drivers/edac/edac_device.c:736:9: error: format not a string literal and no format arguments [-Werror=format-security]
  736 |         ret = dev_set_name(&ctx->dev, name);
      |         ^~~

Use a literal "%s" instead so the name can be the argument.

Fixes: db99ea5f2c03 ("EDAC: Add support for EDAC device features control")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>