scripts/gdb/symbols: follow up on refactoring for const struct bin_attribute
The work for 'const struct bin_attribute' [1] was merged into linux-next
but did not include updates to the lx-symbols code. So it now fails with
the following error:
Python Exception <class 'gdb.error'>: There is no member named nsections.
Error occurred in Python: There is no member named nsections.

Restore its functionality by aligning it with those changes on
kernel/module/sysfs.c.

[1] https://lore.kernel.org/all/20241227-sysfs-const-bin_attr-module-v2-0-e267275f0f37@weissschuh.net/

Signed-off-by: Koichiro Den <koichiro.den@canonical.com>