lib/vsprintf: include stdarg.h from sprintf.h to provide va_list
Declarations in sprintf.h use va_list so it needs to include stdarg.h,
otherwise we may be getting warnings like this:

./include/linux/sprintf.h:11:54: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   11 | __printf(2, 0) int vsprintf(char *buf, const char *, va_list);
      |                                                      ^
      |                                                      int

Fixes: 39ced19b9e60 ("lib/vsprintf: split out sprintf() and friends")
Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>