audit: Update audit_alloc_mark() and audit_dupe_exe() CONFIG_AUDITSYSCALL=n stubs
Commit 84470b80b7b0 ("audit: fix recursive locking deadlock in
audit_dupe_exe()") added a ctx parameter to audit_alloc_mark() and
audit_dupe_exe() but did not update the macro stubs used when
CONFIG_AUDITSYSCALL is not enabled, resulting in a build error for this
configuration:

  kernel/auditfilter.c: In function 'audit_data_to_entry':
  kernel/auditfilter.c:592:85: error: macro 'audit_alloc_mark' passed 4 arguments, but takes just 3
    592 |                         audit_mark = audit_alloc_mark(&entry->rule, str, f_val, NULL);
        |                                                                                     ^
  In file included from kernel/auditfilter.c:23:
  kernel/audit.h:327:9: note: macro 'audit_alloc_mark' defined here
    327 | #define audit_alloc_mark(k, p, l) (ERR_PTR(-EINVAL))
        |         ^~~~~~~~~~~~~~~~
  kernel/auditfilter.c:592:38: error: 'audit_alloc_mark' undeclared (first use in this function)
    592 |                         audit_mark = audit_alloc_mark(&entry->rule, str, f_val, NULL);
        |                                      ^~~~~~~~~~~~~~~~
  kernel/auditfilter.c:592:38: note: 'audit_alloc_mark' is a function-like macro and might be used incorrectly
  kernel/auditfilter.c:592:38: note: each undeclared identifier is reported only once for each function it appears in
  kernel/auditfilter.c: In function 'audit_dupe_rule':
  kernel/auditfilter.c:879:59: error: macro 'audit_dupe_exe' passed 3 arguments, but takes just 2
    879 |                         err = audit_dupe_exe(new, old, ctx);
        |                                                           ^
  kernel/audit.h:333:9: note: macro 'audit_dupe_exe' defined here
    333 | #define audit_dupe_exe(n, o) (-EINVAL)
        |         ^~~~~~~~~~~~~~
  kernel/auditfilter.c:879:31: error: 'audit_dupe_exe' undeclared (first use in this function)
    879 |                         err = audit_dupe_exe(new, old, ctx);
        |                               ^~~~~~~~~~~~~~
  kernel/auditfilter.c:879:31: note: 'audit_dupe_exe' is a function-like macro and might be used incorrectly

Update the macros with the correct number of parameters to resolve the
build error.

Cc: stable@vger.kernel.org
Fixes: 84470b80b7b0 ("audit: fix recursive locking deadlock in audit_dupe_exe()")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>