drm/imagination: Depend on power sequencing
Since commit e38e8391f30b ("drm/imagination: Use pwrseq for TH1520 GPU
power management"), the driver calls power sequencing functions. Add
missing dependency on POWER_SEQUENCING, otherwise the kernel may fail
to build if the driver is built-in and POWER_SEQUENCING is a module
with these linker errors:

aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
aarch64-linux-gnu-ld: drivers/gpu/drm/imagination/pvr_power.o: in function `pvr_power_off_sequence_pwrseq':
pvr_power.c:(.text+0x70): undefined reference to `pwrseq_power_off'
aarch64-linux-gnu-ld: drivers/gpu/drm/imagination/pvr_power.o: in function `pvr_power_on_sequence_pwrseq':
pvr_power.c:(.text+0x88): undefined reference to `pwrseq_power_on'
aarch64-linux-gnu-ld: drivers/gpu/drm/imagination/pvr_power.o: in function `pvr_power_init_pwrseq':
pvr_power.c:(.text+0xb4): undefined reference to `devm_pwrseq_get'

Fixes: e38e8391f30b ("drm/imagination: Use pwrseq for TH1520 GPU power management")
Signed-off-by: Marek Vasut <marek.vasut+renesas@mailbox.org>