bitfield: Fix FIELD_PREP_CONST() with __GENMASK_ULL() on gcc<14
There is a bug in gcc<14[1] that causes the following minimal example to
not be treated as a constant:

  int main() {
      sizeof(struct {
          int t : !(__builtin_ffsll(~0ULL) + 1 < 0);
      });
  }

  test.c: In function 'main':
  test.c:3:21: error: bit-field 't' width not an integer constant
      3 |                 int t : !(__builtin_ffsll(~0ULL) + 1 < 0);
        |                     ^

The result of this bug is a bizarre interaction between FIELD_PREP_CONST()
and __GENMASK_ULL(). Note that this does not occur with GENMASK_ULL() since
that has not been based on the UAPI variant since commit 104ea1c84b91
("bits: unify the non-asm GENMASK*()").

The underlying compiler bug has been fixed in gcc since 14.1.0, but the fix
appears to have been incidental in a larger change[2].

[1]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124699
[2]: https://gcc.gnu.org/cgit/gcc/commit/?id=0d00385eaf72ccacff17935b0d214a26773e095f

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202603222211.A2XiR1YU-lkp@intel.com/
Signed-off-by: Matt Coster <matt.coster@imgtec.com>