iommu/arm-smmu-v3: Add missing #include of linux/string_choices.h
Commit 78dcd96aada7 ("iommu/arm-smmu-v3: Use str_read_write helper w/
logs") introduced a call to str_read_write() in the SMMUv3 driver but
without an explicit #include of <linux/string_choices.h>. This breaks
the build for custom configurations where CONFIG_ACPI=n:

drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c:1909:4: error: call to
	undeclared function 'str_read_write'; ISO C99 and later do not
	support implicit function declarations [-Wimplicit-function-declaration]
 1909 |                         str_read_write(evt->read),
      |                         ^

Add the missing #include.

Link: https://lore.kernel.org/r/d07e82a4-2880-4ae3-961b-471bfa7ac6c4@samsung.com
Reported-by: Marek Szyprowski <m.szyprowski@samsung.com>
Fixes: 78dcd96aada7 ("iommu/arm-smmu-v3: Use str_read_write helper w/ logs")
Signed-off-by: Will Deacon <will@kernel.org>