pinctrl: mediatek: mt8189: Add MODULE_LICENSE declaration
Add missing MODULE_LICENSE("GPL v2") macro to fix modpost error during
kernel module build. The license identifier matches the SPDX header
(GPL-2.0) at the top of the file.

This fixes the following build error:
  ERROR: modpost: missing MODULE_LICENSE() in pinctrl-mt8189.o

Signed-off-by: Justin Yeh <justin.yeh@mediatek.com>