NFS: flexfilelayout: Mark err as __maybe_unused in ff_layout_io_track_ds_error
Fix the following compiler warning when building with W=1:

  flexfilelayout.c: In function 'ff_layout_io_track_ds_error':
  flexfilelayout.c:1503:6:
  error: variable 'err' set but not used [-Werror=unused-but-set-variable]
   1503 |  int err;
        |      ^~~

Variable 'err' is assigned the return value of ff_layout_track_ds_error()
but is only used in the dprintk() debug statement at the end of the
function. When debug output is disabled, the variable appears unused to
the compiler.

Mark it as __maybe_unused to indicate this is intentional.

Signed-off-by: Peng Fan <peng.fan@nxp.com>