media: dvbdev: return -EINVAL on failure
The dvb_register_device() function can return an uninitialized
error code:

drivers/media/dvb-core/dvbdev.c:554:10: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
  554 |                 return ret;
      |                        ^~~

Change this to -EINVAL as in the other half of the #ifdef block.

Fixes: 972e63e895ab ("media: dvbdev: prevent the risk of out of memory access")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>