selftests: pid_namespace: Include sys/mount.h
When executing "make -C tools/testing/selftests/pid_namespace", there exist
many errors such as:

  $ make -C tools/testing/selftests/pid_namespace
  ...
  pid_max.c:42:15: error: implicit declaration of function 'mount' [-Wimplicit-function-declaration]
  ...
  pid_max.c:42:36: error: 'MS_PRIVATE' undeclared (first use in this function); did you mean 'MAP_PRIVATE'?
  ...
  pid_max.c:42:49: error: 'MS_REC' undeclared (first use in this function)
  ...

Include sys/mount.h to fix the errors, tested on x86_64 and LoongArch.

Reported-by: Haiyong Sun <sunhaiyong@loongson.cn>
Fixes: 615ab43b838b ("tests/pid_namespace: add pid_max tests")
Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>