arm64: dts: rockchip: Add rk3588-orangepi-5b device tree and refactor
Implements a slightly modified rk3588s-orangepi-5b.dts from the vendor.
Unfortunately the &wireless_bluetooth and &wireless_wlan overlays don't seem
to compile, so I removed them for now:

Error: arch/arm64/boot/dts/rockchip/rk3588s-orangepi-5b.dts:20.1-20 Label or path wireless_bluetooth not found
Error: arch/arm64/boot/dts/rockchip/rk3588s-orangepi-5b.dts:24.1-15 Label or path wireless_wlan not found

Bigger parts of the rk3588s-orangepi-5.dts file were moved into a new
rk3588s-orangepi-5.dtsi file, so that both device trees from the orangepi-5 and 5b include from it and avoid including from the .dts.

How does this board differ from the original Orange Pi 5?
  - builtin eMMC storage
  - no SPI NOR flash (u-boot, preboot etc. initiates from within the eMMC
    storage)
  - ap6275p Wifi module (like the Orange Pi 5 Plus)
  - builtin BlueTooth module

Beside that everything is exactly the same as far as I know.

Signed-off-by: Cenk Uluisik <cenk.uluisik@googlemail.com>