mm-swap-pm-hibernate-atomically-replace-hibernation-pin-checkpatch-fixes
WARNING: Unknown commit id '8e6e0d845823', maybe rebased or not pulled?
#28: 
Fixes: 8e6e0d845823 ("mm/swap, PM: hibernate: fix swapoff race in uswsusp by pinning swap device")

WARNING: Assisted-by expects 'AGENT_NAME:MODEL_VERSION [TOOL1] [TOOL2]' format
#29: 
Assisted-by: Codex (gpt-5-codex)

ERROR: code indent should use tabs where possible
#54: FILE: include/linux/swap.h:440:
+                                       sector_t offset);$

WARNING: please, no spaces at the start of a line
#54: FILE: include/linux/swap.h:440:
+                                       sector_t offset);$

total: 1 errors, 3 warnings, 106 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-swap-pm-hibernate-atomically-replace-hibernation-pin.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: David Carlier <devnexen@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>