vfio/pds: Using pci_physfn() to fix a compilation issue
If PCI_ATS isn't set, then pdev->physfn is not defined.
it causes a compilation issue:

../drivers/vfio/pci/pds/vfio_dev.c:165:30: error: ‘struct pci_dev’ has no member named ‘physfn’; did you mean ‘is_physfn’?
  165 |   __func__, pci_dev_id(pdev->physfn), pci_id, vf_id,
      |                              ^~~~~~

So using pci_physfn() rather than using pdev->physfn directly.

Signed-off-by: Shixiong Ou <oushixiong@kylinos.cn>