bitfield.h: add FIELD_MAX_CONST
FIELD_MAX_CONST is like FIELD_MAX, but it can be used where statement
expressions are forbidden. For example, using FIELD_MAX in a
static_assert gives:
  error: braced-group within expression allowed only inside a function

It can be used also in array declarations, where using FIELD_MAX would
trigger a warning :
  warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
(It's a bit surprising, because despite the warning, gcc calculated
the array size correctly at compile time.)

A simplified example of what I actually want to use in a driver:
  #define DATA_SIZE_M GENMASK(3, 0)
  #define MAX_DATA_SIZE FIELD_MAX_CONST(DATA_SIZE_M)
  static void f(void) {
  	char buf[MAX_DATA_SIZE];
  	/* ... */
  }

In the implementation, reuse the existing compile-time checks from
FIELD_PREP_CONST.

Signed-off-by: Michal Schmidt <mschmidt@redhat.com>