selftest: breakpoints: fix a minor typo in the format string
GCC 13.2.0 reported a format string warning:

step_after_suspend_test.c: In function ‘run_test’:
step_after_suspend_test.c:92:32: warning: too many arguments for format [-Wformat-extra-args]
   92 |                 ksft_print_msg("waitpid() failed: $s\n", strerror(errno));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~

Fixing the typo $s into %s resolves the issue.

Fixes: 3fa72f2c784b5 ("selftests: breakpoints: step_after_suspend_test use ksft_* var arg msg api")
Cc: Shuah Khan <shuah@kernel.org>
Cc: linux-kselftest@vger.kernel.org
Cc: linux-kernel@vger.kernel.org
Signed-off-by: Mirsad Todorovac <mirsad.todorovac@alu.unizg.hr>