soc: qcom: Fix compile error caused by uncorrectable definition of TRACE_INCLUDE_PATH
Compiler reports the error message when compiling the file drivers/soc/qcom/pmic_pdcharger_ulog.c:
  - ./include/trace/define_trace.h:95:42: fatal error: ./pmic_pdcharger_ulog.h: No such file or directory
      95 | #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)

TRACE_INCLUDE_PATH shoule be relative to the path include/trace/define_trace.h, not
the file including it. Fix it.

Fixes: 086fdb48bc65d(soc: qcom: add ADSP PDCharger ULOG driver)
Signed-off-by: Guanjun <guanjun@linux.alibaba.com>