drm/imagination: don't include pvr_rogue_fwif_check.h under sparse
The checks in pvr_rogue_fwif_check.h trigger issues with sparse
as it may not decide to deal with structure definitions the same
way as the kernel.

There is nothing in pvr_rogue_fwif_check.h that needs to be checked
by sparse, so skip it to reduce the number of failed asserts from
sparse:

drivers/gpu/drm/imagination/pvr_rogue_fwif_check.h:487:1: error: static assertion failed: "struct rogue_fwif_hwrtdata is incorrect size"

Signed-off-by: Ben Dooks <ben.dooks@codethink.co.uk>