NFS: nfs4proc: Mark ptr as __maybe_unused in nfs4_proc_create_session
Fix the following compiler warning when building with W=1:

  nfs4proc.c: In function 'nfs4_proc_create_session':
  nfs4proc.c:9244:16: error: variable 'ptr' set but
  not used [-Werror=unused-but-set-variable]
   9244 |  unsigned *ptr;
        |            ^~~

The variable 'ptr' is assigned but only used in dprintk() debug statements.
When debug output is disabled, the variable appears unused to the compiler.

Mark it as __maybe_unused to indicate this is intentional.

Signed-off-by: Peng Fan <peng.fan@nxp.com>