cxl: Drop unused detach_spa()
Clang warns:
  drivers/misc/cxl/native.c:272:20: error: unused function 'detach_spa' [-Werror,-Wunused-function]

It was created as part of some refactoring in commit a8a7790f4f81 ("cxl:
Allocate and release the SPA with the AFU"), but has never been called
in its current form. Drop it.

Acked-by: Andrew Donnellan <ajd@linux.ibm.com>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/20230823044803.737175-1-mpe@ellerman.id.au