lsm: export security_mmap_backing_file
This symbol can now be used from a loadable erofs module, which causes
a build failure when it is not exported:

ERROR: modpost: "security_mmap_backing_file" [fs/erofs/erofs.ko] undefined!

Fixes: 0e2baaf8fed0 ("lsm: add the security_mmap_backing_file() hook")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>