can: rockchip_canfd: avoids 64-bit division
The new driver fails to build on some 32-bit configurations:

arm-linux-gnueabi-ld: drivers/net/can/rockchip/rockchip_canfd-timestamp.o: in function `rkcanfd_timestamp_init':
rockchip_canfd-timestamp.c:(.text+0x14a): undefined reference to `__aeabi_ldivmod'

Rework the delay calculation to only require a single 64-bit
division.

Fixes: 4e1a18bab124 ("can: rockchip_canfd: add hardware timestamping support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>