Revert "firmware: qcom: scm: Add support for MC boot address API"
This reverts commits 3718852043f4 and 3dc5a65f3767, since this still
causes a build failure when QCOM_SCM is a loadable module, or when
CONFIG_SMP is disabled:

ERROR: modpost: "cpu_logical_map" [drivers/firmware/qcom-scm.ko] undefined!

This be done better for 5.17, but it's too late now to rework
properly.

Fixes: 3dc5a65f3767 ("firmware: qcom: scm: Don't break compile test on non-ARM platforms")
Fixes: 3718852043f4 ("firmware: qcom: scm: Add support for MC boot address API")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>