io_uring: initialize vairable "sqe" to silence build warning
clang-17 compiler throws build error when [-Werror,-Wuninitialized] are enabled
error: variable 'sqe' is uninitialized when used here [-Werror,-Wuninitialized]

Initialize struct io_uring_sqe *sqe = NULL; to have clean build
Reported-by: kernelci.org bot <bot@kernelci.org>
Link: https://lore.kernel.org/regressions/176110914348.5309.724397608932251368@15dd6324cc71/

Signed-off-by: Mallikarjun Thammanavar <mallikarjunst09@gmail.com>