linux-next: build failure after merge of the block tree
Hi all,

After merging the block tree, today's linux-next build (arm64 defconfig)
failed like this:

/tmp/next/build/io_uring/zcrx.c: In function 'zcrx_register_netdev':
/tmp/next/build/io_uring/zcrx.c:816:15: error: implicit
declaration of function '__net_mp_open_rxq'; did you mean
'netif_mp_open_rxq'? [-Wimplicit-function-declaration]
  816 |         ret = __net_mp_open_rxq(ifq->netdev, if_rxq, &mp_param, NULL);
      |               ^~~~~~~~~~~~~~~~~ netif_mp_open_rxq

Caused by commit

   1e91c98bc9a8ef (net: Slightly simplify net_mp_{open,close}_rxq)

interacting with block tree changes.  I have fixed this up as per below
and can carry as needed

From d5971ccec3525c71d28cb40bc4a6c9596f354b48 Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Fri, 10 Apr 2026 13:14:23 +0100
Subject: [PATCH] io_uring: Fix up build for "net: Slightly simplify
 net_mp_{open,close}_rxq"

/tmp/next/build/io_uring/zcrx.c: In function 'zcrx_register_netdev':
/tmp/next/build/io_uring/zcrx.c:816:15: error: implicit
declaration of function '__net_mp_open_rxq'; did you mean
'netif_mp_open_rxq'? [-Wimplicit-function-declaration]
  816 |         ret = __net_mp_open_rxq(ifq->netdev, if_rxq, &mp_param, NULL);
      |               ^~~~~~~~~~~~~~~~~ netif_mp_open_rxq

Signed-off-by: Mark Brown <broonie@kernel.org>