pinctrl: pic32: use consistent spacing around '+'
Address the following warning from checkpatch.pl:

    ERROR: need consistent spacing around '+' (ctx:WxV)

Fixes: 50d4d321b92db ("pinctrl: pinctrl-pic32: Add PIC32 pin control driver")
Signed-off-by: Brian Masney <bmasney@redhat.com>
Reviewed-by: Bartosz Golaszewski <bartosz.golaszewski@oss.qualcomm.com>
Signed-off-by: Linus Walleij <linusw@kernel.org>