fs/qnx6: Fix building with GCC 15
GCC 15 enables -Werror=unterminated-string-initialization by default.
This results in the following build error

fs/qnx6/inode.c: In function ‘qnx6_checkroot’:
fs/qnx6/inode.c:182:41: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
  182 |         static char match_root[2][3] = {".\0\0", "..\0"};
      |                                         ^~~~~~~
fs/qnx6/inode.c:182:50: error: initializer-string for array of ‘char’ is too long [-Werror=unterminated-string-initialization]
  182 |         static char match_root[2][3] = {".\0\0", "..\0"};
      |                                                  ^~~~~~

Dropping to match_root array and drictly comparing dir_entry entries via
memcmp provides a work aroud for the build error.

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>