compiler_types.h: fix "unused variable" in __compiletime_assert()
This refines commit c03567a8e8d5 ("include/linux/compiler.h: don't
perform compiletime_assert with -O0") and restores #ifdef __OPTIMIZE__
symmetry by evaluating the 'condition' variable in both compile-time
variants of __compiletimeassert().

As __OPTIMIZE__ is always true by default, this commit does not change
anything by default. But it fixes warnings with _non-default_ CFLAGS
like for instance this:

 make  CFLAGS_tcp.o='-Og -U__OPTIMIZE__'

                 from net/ipv4/tcp.c:273:

 include/net/sch_generic.h: In function ‘qdisc_cb_private_validate’:
 include/net/sch_generic.h:511:30:
            error: unused variable ‘qcb’ [-Werror=unused-variable]

  {
     struct qdisc_skb_cb *qcb;

     BUILD_BUG_ON(sizeof(skb->cb) < sizeof(*qcb));
     ...
  }

Signed-off-by: Marc Herbert <Marc.Herbert@linux.intel.com>