lock_mount(): Remove unused function
clang is not happy about unused function:

/fs/namespace.c:2856:20: error: unused function 'lock_mount' [-Werror,-Wunused-function]
 2856 | static inline void lock_mount(const struct path *path,
      |                    ^~~~~~~~~~
1 error generated.

Fix the compilation breakage (`make W=1` build) by removing unused function.

Fixes: d14b32629541 ("change calling conventions for lock_mount() et.al.")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>