tools headers UAPI: sync linux/taskstats.h for procacct.c
Background
==========
After commit 9b93f7e32774 ("tools/getdelays: use the static UAPI
headers from tools/include/uapi"), the Makefile was changed to use
-I../include/uapi/ instead of -I../../usr/include to ensure tools
always use the up-to-date UAPI headers.

However, only linux/taskstats.h was added to tools/include/uapi/ in
commit e5bbb35a07b3 ("tools headers UAPI: sync linux/taskstats.h"),
but linux/acct.h was missing.

Problem
=======
This causes procacct.c to fail to compile with:

procacct.c:234:37: error: 'AGROUP' undeclared (first use in this function)

gcc -I../include/uapi/    getdelays.c   -o getdelays
gcc -I../include/uapi/    procacct.c   -o procacct
procacct.c: In function ‘print_procacct’:
procacct.c:234:37: error: ‘AGROUP’ undeclared (first use in this function)
did you mean ‘NOGROUP’?
  234 |  , t->version >= 12 ? (t->ac_flag & AGROUP ? 'P' : 'T') : '?'
      |                                     ^~~~~~
      |                                     NOGROUP
procacct.c:234:37: note: each undeclared ident

because procacct.c uses the AGROUP macro defined in linux/acct.h.

Solution
========
Add the missing linux/acct.h to complete the static UAPI header set.

Fixes: 9b93f7e32774 ("tools/getdelays: use the static UAPI headers from tools/include/uapi")
Signed-off-by: Wang Yaxin <wang.yaxin@zte.com.cn>