preempt_rt: increase PERCPU_DYNAMIC_SIZE_SHIFT for slab randomization
When both PREEMPT_RT and RANDOM_KMALLOC_CACHES are enabled, the slub allocator
runs into a build time failure:

In file included from <command-line>:
In function 'alloc_kmem_cache_cpus',
    inlined from 'do_kmem_cache_create' at mm/slub.c:6041:7:
include/linux/compiler_types.h:517:45: error: call to '__compiletime_assert_598' declared with attribute error: BUILD_BUG_ON failed: PERCPU_DYNAMIC_EARLY_SIZE < NR_KMALLOC_TYPES * KMALLOC_SHIFT_HIGH * sizeof(struct kmem_cache_cpu)
  517 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |                                             ^
include/linux/compiler_types.h:498:25: note: in definition of macro '__compiletime_assert'
  498 |                         prefix ## suffix();                             \
      |                         ^~~~~~
include/linux/compiler_types.h:517:9: note: in expansion of macro '_compiletime_assert'
  517 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
include/linux/build_bug.h:39:37: note: in expansion of macro 'compiletime_assert'
   39 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
include/linux/build_bug.h:50:9: note: in expansion of macro 'BUILD_BUG_ON_MSG'
   50 |         BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
      |         ^~~~~~~~~~~~~~~~
mm/slub.c:5133:9: note: in expansion of macro 'BUILD_BUG_ON'
 5133 |         BUILD_BUG_ON(PERCPU_DYNAMIC_EARLY_SIZE <
      |         ^~~~~~~~~~~~

The problem is the additional size overhead from local_lock in
struct kmem_cache_cpu.  Avoid this by preallocating a larger area.

Fixes: d8fccd9ca5f9 ("arm64: Allow to enable PREEMPT_RT.")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202410020326.iaZIteIx-lkp@intel.com/
Signed-off-by: Arnd Bergmann <arnd@arndb.de>