staging: media: atomisp: remove unnecessary parentheses in return statement
Remove unnecessary parentheses around the return value in
ia_css_pipeline_get_pipe_io_status(). return is not a function,
so parentheses are not required.

This addresses the following checkpatch error:
  ERROR: return is not a function, parentheses are not required

Signed-off-by: Teng Liu <27rabbitlt@gmail.com>