nvme-keyring: add MODULE_LICENSE()
When NVME_KEYRING=y (NVME_AUTH is not set), there is a modpost build
error:

ERROR: modpost: missing MODULE_LICENSE() in drivers/nvme/common/nvme-common.o

so add a MODULE_LICENSE() to keyring.c (copied from auth.c).

Fixes: 9d77eb527784 ("nvme-keyring: register '.nvme' keyring")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Keith Busch <kbusch@kernel.org>
Cc: Jens Axboe <axboe@fb.com>
Cc: Christoph Hellwig <hch@lst.de>
Cc: Sagi Grimberg <sagi@grimberg.me>
Cc: Hannes Reinecke <hare@suse.de>
Cc: linux-nvme@lists.infradead.org