usb: acpi: fix undefined behavior in USB_ACPI_LOCATION_VALID
USB_ACPI_LOCATION_VALID uses a signed left shift into the sign
bit. Shifting a signed value into the sign bit is undefined behavior.
Use BIT(31) instead.

Found by cppcheck:
      drivers/usb/core/usb-acpi.c:221:24: error:
      Shifting signed 32-bit value by 31 bits is undefined behaviour
      [shiftTooManyBitsSigned]

Fixes: f3ac348e6e045 ("usb: usb-acpi: Set port connect type of not connectable ports correctly")
Signed-off-by: Igor Cudnik <igor@its.rel.pl>