media: b2c2: flexcop-eeprom: Fix assignment and missing return in MAC check
Fixes a coding style violation and build error in
`flexcop_eeprom_check_mac_addr()`. The function contained
an invalid assignment in an if-condition and was missing
a return at the end of a non-void function.

Fixes the warning:
  warning: operation on ‘ret’ may be undefined [-Wsequence-point]

And the error:
  error: control reaches end of non-void function [-Werror=return-type]

Signed-off-by: Darshan Rathod <darshanrathod475@gmail.com>