pmdomain: ti_sci: add CONFIG_PM_SLEEP dependency
Without CONFIG_PM_SLEEP, the pm_generic_suspend() function cannot be called
since it is defined to NULL:

In file included from include/uapi/linux/posix_types.h:5,
		...
                 from drivers/pmdomain/ti/ti_sci_pm_domains.c:10:
drivers/pmdomain/ti/ti_sci_pm_domains.c: In function 'ti_sci_pd_suspend':
include/linux/stddef.h:9:14: error: called object is not a function or function pointer
    9 | #define NULL ((void *)0)
      |              ^
include/linux/pm.h:875:41: note: in expansion of macro 'NULL'
  875 | #define pm_generic_suspend              NULL
      |                                         ^~~~
drivers/pmdomain/ti/ti_sci_pm_domains.c:134:15: note: in expansion of macro 'pm_generic_suspend'
  134 |         ret = pm_generic_suspend(dev);
      |               ^~~~~~~~~~~~~~~~~~

Fixes: 7c2c8d2651b5 ("pmdomain: ti_sci: add per-device latency constraint management")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>