LoongArch: Enable tracing syscalls in defconfig
There exist the following errors when building bpf selftest:

  $ cd tools/testing/selftests/bpf/
  $ make
  ...
  CLNG-BPF [test_progs] profiler1.bpf.o
  In file included from progs/profiler1.c:5:
  progs/profiler.inc.h:599:49: error: declaration of 'struct syscall_trace_enter' will not be visible outside of this function [-Werror,-Wvisibility]
  ...
  progs/profiler.inc.h:604:15: error: incomplete definition of type 'struct syscall_trace_enter'
  ...
  progs/profiler.inc.h:605:15: error: incomplete definition of type 'struct syscall_trace_enter'
  ...
  3 errors generated.

This is because there is no basic tracer to catch the syscall entry
and exit events, it is better to enable the kernel tracing syscalls
with CONFIG_FTRACE_SYSCALLS in defconfig to avoid the building errors.

Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>