ice: don't compile ice_dpll.c if CONFIG_PTP_1588_CLOCK is disabled
The ice_dpll.c file was recently merged with support for the DPLL
interface. This feature as currently written in the ice driver depends on
the PTP infrastructure and causes compilation failures if
CONFIG_PTP_1588_CLOCK is disabled:

ld: vmlinux.o: in function `ice_dpll_init_info_direct_pins':
ice_dpll.c:(.text+0x894167): undefined reference to `ice_cgu_get_pin_freq_supp'
ld: ice_dpll.c:(.text+0x894197): undefined reference to `ice_cgu_get_pin_name'
ld: ice_dpll.c:(.text+0x8941a8): undefined reference to `ice_cgu_get_pin_type'
ld: vmlinux.o: in function `ice_dpll_update_state':
ice_dpll.c:(.text+0x894494): undefined reference to `ice_get_cgu_state'
ld: vmlinux.o: in function `ice_dpll_init':
(.text+0x8953d5): undefined reference to `ice_get_cgu_rclk_pin_info'

This occurs because the ice_dpll.c file is compiled unconditionally, but it
depends on functions in ice_ptp_hw.c which is only compiled with
CONFIG_PTP_1588_CLOCK. It might be possible to break this dependency and
expose those functions without CONFIG_PTP_1588_CLOCK, but that is not clear
to me.

For now, simply fix the Makefile to compile ice_dpll.c only when we have
PTP support enabled. Also update the ice_dpll.h header to provide no-op
fallbacks for enabling and disabling the DPLL feature in this case.

Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>