drm/amd/display:: fix designated initializer error
{} instead of {0} avoids the error with W=1

error: positional initialization of field in ‘struct’ declared
with ‘designated_init’ attribute [-Werror=designated-init]

Signed-off-by: Rosen Penev <rosenp@gmail.com>