kerneldoc: Fix two missing newlines in drm_connector.c
drm_connector.c has two kerneldoc comments that were missing newlines.
This results in the following warnings when running make htmldocs:

./Documentation/gpu/drm-kms:538: ./drivers/gpu/drm/drm_connector.c:2344:
WARNING: Definition list ends without a blank line; unexpected unindent.
[docutils] ./Documentation/gpu/drm-kms:538:

./drivers/gpu/drm/drm_connector.c:2346: ERROR: Unexpected indentation.
[docutils] ./Documentation/gpu/drm-kms:538:

./drivers/gpu/drm/drm_connector.c:2368: WARNING: Block quote ends without a
blank line; unexpected unindent. [docutils] ./Documentation/gpu/drm-kms:538:

./drivers/gpu/drm/drm_connector.c:2381: ERROR: Unexpected indentation.
[docutils]

Signed-off-by: Daniel Yang <danielyangkang@gmail.com>