iio: proximity: isl29501: mark OF related data as maybe unused
When compile tested with W=1 on x86_64 with driver as built-in:

  isl29501.c:999:34: error: unused variable 'isl29501_i2c_matches' [-Werror,-Wunused-const-variable]

The if defined(CONFIG_OF) is also not needed in such case.

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>