perf bench sched-seccomp-notify: Fix __NR_seccomp undeclared build error on i386
Fix a build error on i386 system:

bench/sched-seccomp-notify.c: In function 'seccomp':
bench/sched-seccomp-notify.c:46:17: error: '__NR_seccomp' undeclared (first use in this function); did you mean 'seccomp'?
  return syscall(__NR_seccomp, op, flags, args);
                 ^~~~~~~~~~~~
                 seccomp
bench/sched-seccomp-notify.c:46:17: note: each undeclared identifier is reported only once for each function it appears in
bench/sched-seccomp-notify.c:47:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors

Fixes: 7d5cb68af638 ("perf/benchmark: add a new benchmark for seccom_unotify")
Signed-off-by: Yang Jihong <yangjihong1@huawei.com>