tools/nolibc/string: export strlen()
As with commit 8d304a374023, "tools/nolibc/string: export memset() and
memmove()", gcc -Os without -ffreestanding may fail to compile with:

	cc -fno-asynchronous-unwind-tables -fno-ident -s -Os -nostdlib -lgcc -c test.c -o test.o
	cc test.o -fno-asynchronous-unwind-tables -fno-ident -s -Os -nostdlib -lgcc  -static -o test
	/usr/bin/ld: test.o: in function `main':
	test.c:(.text.startup+0x32): undefined reference to `strlen'
	collect2: error: ld returned 1 exit status

As on the aforementioned commit, this patch adds a section to export
this function so compilation works on those cases too.

Signed-off-by: Rodrigo Campos <rodrigo@sdfg.com.ar>