ntfs3: align struct ATTR_LIST_ENTRY
On architectures like i386 that don't enforce natural alignment of u64
struct members, so the recent change to remove the final 48 bits
reduced the structure size from 32 to 28 bytes:

include/linux/build_bug.h:78:41: error: static assertion failed: "sizeof(struct ATTR_LIST_ENTRY) == 0x20"
fs/ntfs3/ntfs.h:530:1: note: in expansion of macro 'static_assert'
  530 | static_assert(sizeof(struct ATTR_LIST_ENTRY) == 0x20);
      | ^~~~~~~~~~~~~

Add an alignment attribute that makes the structure the same across
all architectures again.

Fixes: d155617006eb ("fs/ntfs3: Fix detected field-spanning write (size 8) of single field "le->name"")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>