lib/crc: re-disable optimized CRC code on user-mode Linux
The reorganization of lib/crc/ unintentionally enabled the x86-optimized
CRC64 code on user-mode Linux.  (It's enabled when CONFIG_X86_64, which
is set by arch/x86/um/Kconfig.  Note that this is a different option
from the "normal" CONFIG_X86_64 which is defined in arch/x86/Kconfig.)
Since this is not being taken into account, a build error results:

    CC      lib/crc/crc64-main.o
    cc1: error: ./lib/crc/um: No such file or directory [-Werror=missing-include-dirs]
    lib/crc/crc64-main.c:58:10: fatal error: crc64.h: No such file or directory
       58 | #include "crc64.h" /* $(SRCARCH)/crc64.h */
          |          ^~~~~~~~~
    compilation terminated.
    cc1: all warnings being treated as errors

Fix this by re-disabling the optimized CRC code on user-mode Linux.

Fixes: e2fd1883971d ("lib/crc: prepare for arch-optimized code in subdirs of lib/crc/")
Signed-off-by: Eric Biggers <ebiggers@google.com>