ACPI/processor_idle: Export acpi_processor_ffh_play_dead()
* Artem Bityutskiy <artem.bityutskiy@linux.intel.com> wrote:

> On Sat, 2025-02-15 at 12:51 +0800, kernel test robot wrote:
> > tree:   https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git x86/cpu
> > head:   96040f7273e2bc0be1871ad9ed4da7b504da9410
> > commit: 541ddf31e30022b8e6f44b3a943964e8f0989d15 [3/5] ACPI/processor_idle: Add FFH state handling
> > config: x86_64-randconfig-077-20250214 (https://download.01.org/0day-ci/archive/20250215/202502151207.FA9UO1iX-lkp@intel.com/config)
> > compiler: clang version 19.1.3 (https://github.com/llvm/llvm-project ab51eccf88f5321e7c60591c5546b254b6afab99)
> > reproduce (this is a W=1 build): (https://download.01.org/0day-ci/archive/20250215/202502151207.FA9UO1iX-lkp@intel.com/reproduce)
> >
> > If you fix the issue in a separate patch/commit (i.e. not just a new version of
> > the same patch/commit), kindly add following tags
> > > Reported-by: kernel test robot <lkp@intel.com>
> > > Closes: https://lore.kernel.org/oe-kbuild-all/202502151207.FA9UO1iX-lkp@intel.com/
> >
> > All errors (new ones prefixed by >>, old ones prefixed by <<):
> >
> > > > ERROR: modpost: "acpi_processor_ffh_play_dead" [drivers/acpi/processor.ko] undefined!
>
> Oh, this is the 'CONFIG_ACPI_PROCESSOR=m' case. The function export is missing. Sorry for this.
>
> The below patch fixes the issue. Could you please fold it into the following commit?
>
> 	541ddf31e300 ACPI/processor_idle: Add FFH state handling
>
> I am not sure about the rules of the tip tree in cases like this, please direct me on
> how to handle the delivery of the fix.

Additional patches have been added since then to tip:x86/cpu, so I
created the commit below, and added your Signed-off-by.

Thanks,

	Ingo

==========================>
From: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Date: Sun, 16 Feb 2025 14:26:14 +0200
Subject: [PATCH] ACPI/processor_idle: Export acpi_processor_ffh_play_dead()

The kernel test robot reported the following build error:

  >> ERROR: modpost: "acpi_processor_ffh_play_dead" [drivers/acpi/processor.ko] undefined!

Caused by this recently merged commit:

  541ddf31e300 ("ACPI/processor_idle: Add FFH state handling")

The build failure is due to an oversight in the 'CONFIG_ACPI_PROCESSOR=m' case,
the function export is missing. Add it.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202502151207.FA9UO1iX-lkp@intel.com/
Fixes: 541ddf31e300 ("ACPI/processor_idle: Add FFH state handling")
Signed-off-by: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Cc: Dave Hansen <dave.hansen@linux.intel.com>
Link: https://lore.kernel.org/r/de5bf4f116779efde315782a15146fdc77a4a044.camel@linux.intel.com