staging: gpib: Remove depends on BROKEN
The build of drivers/staging/gpib/hp_82341 driver was failing
with:

ERROR: modpost: "isapnp_read_byte"
[drivers/staging/gpib/hp_82341/hp_82341.ko] undefined!

The driver was marked BROKEN to fix this issue
Link: https://lore.kernel.org/all/2024101412-outsider-icing-052e@gregkh/

Remove the dependency on BROKEN

Signed-off-by: Dave Penkler <dpenkler@gmail.com>
Link: https://lore.kernel.org/linux-staging/20250122103859.25499-3-dpenkler@gmail.com/T/#u
Link: https://lore.kernel.org/r/20250124105900.27592-4-dpenkler@gmail.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>