irqchip/ath79-misc: fix missing prototypes warnings
ath79_misc_irq_init() was defined but unused since commit
51fa4f8912c0 ("MIPS: ath79: drop legacy IRQ code"), so it's time
to drop it. This patch also adds the missing header "asm/time.h"
which defines the prototype of get_c0_perfcount_int().

Fix the following warnings:

drivers/irqchip/irq-ath79-misc.c:26:5: error: no previous prototype for 'get_c0_perfcount_int' [-Werror=missing-prototypes]
   26 | int get_c0_perfcount_int(void)
      |     ^~~~~~~~~~~~~~~~~~~~
drivers/irqchip/irq-ath79-misc.c:181:13: error: no previous prototype for 'ath79_misc_irq_init' [-Werror=missing-prototypes]
  181 | void __init ath79_misc_irq_init(void __iomem *regs, int irq,
      |             ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>