mm/slab: Fix build error due to extra argument
    mm/slub.c:5553:30: error: too many arguments to function call, expected 5, have 6
     5552 |                 return __do_kmalloc_node(size, NULL, flags, node,
          |                        ~~~~~~~~~~~~~~~~~

Fix by removing the nonexistent size argument.

Closes: https://lore.kernel.org/all/178153914528.15282.16770125845520023465@330cfa3079ca/
Signed-off-by: Calvin Owens <calvin@wbinvd.org>