firmware: ti_sci: Fix compilation failure when CONFIG_TI_SCI_PROTOCOL=m
When build with CONFIG_TI_SCI_PROTOCOL=m && CONFIG_TI_K3_M4_REMOTEPROC=y,
compilation tool chain would throw the following error message:

   arm-linux-gnueabi-ld: drivers/remoteproc/ti_k3_m4_remoteproc.o:
   in function `k3_m4_rproc_probe':
   ti_k3_m4_remoteproc.c:(.text+0xc24):
   undefined reference to `devm_ti_sci_get_by_phandle'

This is because devm_ti_sci_get_by_phandle() is compiled into the driver
module rather than compiled into kernel, it causes compilation couldn't
find the reference of devm_ti_sci_get_by_phandle() when tool chain tries
to link ti_k3_m4_remoteproc.o into kernel image.

Replace IS_ENABLED with IS_REACHABLE to fix the problem.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/all/202410150837.FOGlkGvW-lkp@intel.com/
Fixes: aa276781a64a ("firmware: Add basic support for TI System Control Interface (TI-SCI) protocol")
Signed-off-by: Zeng Heng <zengheng4@huawei.com>