pwm: rcar: include linux/bitfield.h
The use of FIELD_MAX() breaks in some configurations because of
a missing header:

drivers/pwm/pwm-rcar.c:114:12: error: call to undeclared function 'FIELD_MAX'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  114 |         if (tmp > FIELD_MAX(RCAR_PWMCNT_CYC0_MASK))
      |                   ^

Fixes: edd549f4956b ("pwm: rcar: Improve register calculation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>