perf build: Add rust target flag for loongarch cross compile
Based on commit 30f998c992c9 ("tools build: Fix rust cross
compilation"), add rust target flags for loongarch cross tool to fix
perf compilation error:
*** Unknown rust cross compilation architecture loongarch. Stop.

Signed-off-by: lifangxu <lifangxu@kylinos.cn>