drm/tests: Remove CONFIG_DRM_FBDEV_EMULATION on .kunitconfig
Using the `kunit_tool` with the command:

tools/testing/kunit/kunit.py run --kunitconfig=drivers/gpu/drm/tests/

Lead to this error[0]. Fix it by expliciting removing the
CONFIG_DRM_FBDEV_EMULATION.

[0]
ERROR:root:
WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE
  Depends on [n]: VT [=n] && FB_CORE [=y] && !UML [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && !EXPERT [=n]

WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE_DETECT_PRIMARY
  Depends on [n]: VT [=n] && FRAMEBUFFER_CONSOLE [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && FRAMEBUFFER_CONSOLE [=y]

WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE
  Depends on [n]: VT [=n] && FB_CORE [=y] && !UML [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && !EXPERT [=n]

WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE_DETECT_PRIMARY
  Depends on [n]: VT [=n] && FRAMEBUFFER_CONSOLE [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && FRAMEBUFFER_CONSOLE [=y]

WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE
  Depends on [n]: VT [=n] && FB_CORE [=y] && !UML [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && !EXPERT [=n]

WARNING: unmet direct dependencies detected for FRAMEBUFFER_CONSOLE_DETECT_PRIMARY
  Depends on [n]: VT [=n] && FRAMEBUFFER_CONSOLE [=y]
  Selected by [y]:
  - DRM_FBDEV_EMULATION [=y] && HAS_IOMEM [=y] && DRM [=y] && FRAMEBUFFER_CONSOLE [=y]
/usr/bin/ld: drivers/video/fbdev/core/fbcon.o: in function `fbcon_suspended':
fbcon.c:(.text+0x1c): undefined reference to `vc_cons'
/usr/bin/ld: drivers/video/fbdev/core/fbcon.o: in function `fbcon_cursor':
fbcon.c:(.text+0x1ac): undefined reference to `console_blanked'
/usr/bin/ld: drivers/video/fbdev/core/fbcon.o: in function `fbcon_resumed':
fbcon.c:(.text+0x39c): undefined reference to `vc_cons'
/usr/bin/ld: fbcon.c:(.text+0x3aa): undefined reference to `redraw_screen'
/usr/bin/ld: drivers/video/fbdev/core/fbcon.o: in function `fbcon_update_vcs':
.
.
.
make[3]: *** [../scripts/Makefile.vmlinux:36: vmlinux] Error 1
make[2]: *** [/home/grillo/projects/linux/Makefile:1238: vmlinux] Error 2
make[1]: *** [/home/grillo/projects/linux/Makefile:234: __sub-make] Error 2
make: *** [Makefile:234: __sub-make] Error 2

Fixes: c242f48433e7 ("drm: Make FB_CORE to be selected if DRM fbdev emulation is enabled")
Signed-off-by: Arthur Grillo <arthurgrillo@riseup.net>