tools riscv: Include fence.h from the same directory barrier.h lives
When cross building perf to riscv I noticed that it isn't finding the
asm/fence.h file included from tools/arch/riscv/include/asm/barrier.h,
since both live in the same directory, load it from there instead of
from asm/fence.h, fixing the libbpf build in such environment:

  perfbuilder@number:~$ time dm ubuntu:22.04-x-riscv64
     1     4.32 ubuntu:22.04-x-riscv64        : FAIL gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
                       from mmap.c:7:
      /git/perf-6.12.0-rc6/tools/include/asm/../../arch/riscv/include/asm/barrier.h:13:10: fatal error: asm/fence.h: No such file or directory
         13 | #include <asm/fence.h>
            |          ^~~~~~~~~~~~~
      compilation terminated.
  <SNIP other similar errors>

This probably should work in other systems where the right asm/fence.h
is available, but in the above scenario, it fails. Probably we should
fix the perf build system to find it in tools/arch/riscv/include/asm/,
but this one-liner should be a stop gap solution till we get there.

Testing it:

  perfbuilder@number:~$ time dm ubuntu:22.04-x-riscv64
     1    21.65 ubuntu:22.04-x-riscv64        : Ok   riscv64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0  flex 2.6.4
  BUILD_TARBALL_HEAD=800d169e2d39e4e81ade326d73ae7c4343c12b45
  $ git log --oneline -1 800d169e2d39e4e81ade326d73ae7c4343c12b45
  800d169e2d39e4e8 tools riscv: Include fence.h from the same directory barrier.h lives
  toolsbuilder@number:~/perf-6.12.0-rc6$ ls -la /tmp/build/perf/perf
  -rwxr-xr-x. 1 toolsbuilder toolsbuilder 3278728 Nov 26 21:12 /tmp/build/perf/perf
  toolsbuilder@number:~/perf-6.12.0-rc6$ file /tmp/build/perf/perf
  /tmp/build/perf/perf: ELF 64-bit LSB pie executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-riscv64-lp64d.so.1, BuildID[sha1]=9b77bbf51da74cee24c6d5fc5814343cc7e9a652, for GNU/Linux 4.15.0, with debug_info, not stripped
  toolsbuilder@number:~/perf-6.12.0-rc6$
  toolsbuilder@number:~/perf-6.12.0-rc6$ readelf -d /tmp/build/perf/perf | head
  Dynamic section at offset 0x242db0 contains 33 entries:
    Tag        Type                         Name/Value
   0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
   0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
   0x0000000000000001 (NEEDED)             Shared library: [libelf.so.1]
   0x0000000000000001 (NEEDED)             Shared library: [libdw.so.1]
   0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
   0x0000000000000001 (NEEDED)             Shared library: [ld-linux-riscv64-lp64d.so.1]
   0x0000000000000020 (PREINIT_ARRAY)      0x238740
  toolsbuilder@number:~/perf-6.12.0-rc6$

Fixes: 6d74d178fe6eaf61 ("tools: Add riscv barrier implementation")
Cc: Charlie Jenkins <charlie@rivosinc.com>
Cc: Palmer Dabbelt <palmer@rivosinc.com>
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>