MIPS: lantiq: falcon: sysctrl: add missing header prom.h
"prom.h" includes the prototype of ltq_soc_init(). Fix warning:

arch/mips/lantiq/falcon/sysctrl.c:185:13: error: no previous prototype for 'ltq_soc_init' [-Werror=missing-prototypes]
  185 | void __init ltq_soc_init(void)
      |             ^~~~~~~~~~~~

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>