pinctrl: qcom: lpass-lpi: remove unused lpi_gpio_write function
All callers of this function were converted to calling __lpi_gpio_write
instead, so it now causes a warning:

drivers/pinctrl/qcom/pinctrl-lpass-lpi.c:82:12: error: unused function 'lpi_gpio_write' [-Werror,-Wunused-function]
   82 | static int lpi_gpio_write(struct lpi_pinctrl *state, unsigned int pin,

Remove the unused function.

Fixes: b719ede389d8 ("pinctrl: qcom: lpass-lpi: Switch to PM clock framework for runtime PM")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>