selftests: pidfd: add missing sys/ioctl.h include in pidfd_setns_test.c
Fix compile on openSUSE Tumbleweed (gcc-14.2.1, glibc-2.40):
  - add missing sys/ioctl.h include

Fixes:

  pidfd_setns_test.c: In function ‘current_nsset_setup’:
  pidfd_setns_test.c:172:54: error: implicit declaration of function ‘ioctl’ [-Wimplicit-function-declaration]
    172 |                 self->child_pidfd_derived_nsfds[i] = ioctl(self->pidfd, info->pidfd_ioctl, 0);
        |                                                      ^~~~~

Signed-off-by: Peter Seiderer <ps.report@gmx.net>