ublk: reduce stack usage in __ublk_shmem_remove_ranges
The array in __ublk_shmem_remove_ranges() is one kilobyte long,
which is really too much for an on-stack allocation, as can be
seen with a frame warning limit of 1.25kb that otherwise produces
a clean build on my test system:

drivers/block/ublk_drv.c: In function '__ublk_shmem_remove_ranges':
drivers/block/ublk_drv.c:5573:1: error: the frame size of 1392 bytes is larger than 1280 bytes [-Werror=frame-larger-than=]

Maybe half the size is good enough here, so try 32 entries.
If 64 entries are really required, the array could be dynamically
allocated, but that would risk an allocation failure.

Fixes: 309e02dccf64 ("ublk: avoid unpinning pages under maple tree spinlock")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>