drm/appletbdrm: fix format character for size_t
Use %zu for size_t instead of %lu to avoid failures on 32-bit builds:

error: format ‘%lu’ expects argument of type ‘long unsigned int’, but
argument 4 has type ‘size_t’ {aka ‘unsigned int’}

Fixes: 0670c2f56e45 ("drm/tiny: add driver for Apple Touch Bars in x86 Macs")
Cc: Kerem Karabay <kekrby@gmail.com>
Cc: Atharva Tiwari <evepolonium@gmail.com>
Cc: Aditya Garg <gargaditya08@live.com>
Cc: Aun-Ali Zaidi <admin@kodeit.net>
Cc: Thomas Zimmermann <tzimmermann@suse.de>
Signed-off-by: Jani Nikula <jani.nikula@intel.com>