uio: Fix build failure on 32 bit builds with 64 bit physaddr
Builds on 32-bit systems with 64 bit physical address fail with

drivers/uio/uio.c: In function 'uio_mmap_dma_coherent':
drivers/uio/uio.c:795:16: error:
	cast to pointer from integer of different size

The conversion itself is safe since sizeof(phys_addr_t) it in general equal
to or larger than sizeof(void *). Solve the problem by double-casting the
conversion.

Fixes: 576882ef5e7f ("uio: introduce UIO_MEM_DMA_COHERENT type")
Cc: Chris Leech <cleech@redhat.com>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/20240323144228.3924542-2-linux@roeck-us.net
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>