perf list: Don't write to const memory
Something now detected on fedora 44, where strchr() returns const if it
is passed a const pointer:

  util/print-events.c: In function 'print_sdt_events':
  util/print-events.c:89:29: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
     89 |                 char *bid = strchr(sdt_name->s, '@');
        |                             ^~~~~~

Fix it by using strnchr() if strchr finds the separator instead of
temporarily scrubbing it with '\0'.

Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>