media: lt6911uxe: select V4L2_CCI_I2C in Kconfig
lt6911uxe driver has dependency on V4L2_CCI_I2C, need select it in
Kconfig to fix the build errors:

ERROR: modpost: "cci_write" [drivers/media/i2c/lt6911uxe.ko] undefined!                                                                                                                                                                    ERROR: modpost: "cci_read" [drivers/media/i2c/lt6911uxe.ko] undefined!

Fixes: e49563c3be09 ("media: i2c: add lt6911uxe hdmi bridge driver")
Cc: stable@vger.kernel.org
Signed-off-by: Bingbu Cao <bingbu.cao@intel.com>