mfd: stmpe-spi: Correct the name used in MODULE_DEVICE_TABLE
The name used in the macro does not exist.

drivers/mfd/stmpe-spi.c:132:26: error: use of undeclared identifier 'stmpe_id'
  132 | MODULE_DEVICE_TABLE(spi, stmpe_id);
      |                          ^
1 error generated.

Fixes: e789995d5c61 ("mfd: Add support for STMPE SPI interface")
Cc: Lee Jones <lee@kernel.org>
Cc: Maxime Coquelin <mcoquelin.stm32@gmail.com>
Cc: Alexandre Torgue <alexandre.torgue@foss.st.com>
Signed-off-by: Alexey Gladkov <legion@kernel.org>