PCI: rcar-gen4: Fix type of type parameter in rcar_gen4_pcie_ep_raise_irq()
With clang's kernel control flow integrity (kCFI, CONFIG_CFI_CLANG),
indirect call targets are validated against the expected function
pointer prototype to make sure the call target is valid to help mitigate
ROP attacks. If they are not identical, there is a failure at run time,
which manifests as either a kernel panic or thread getting killed. A
warning in clang aims to catch these at compile time, which reveals:

  drivers/pci/controller/dwc/pcie-rcar-gen4.c:403:15: error: incompatible function pointer types initializing 'int (*)(struct dw_pcie_ep *, u8, enum pci_epc_irq_type, u16)' (aka 'int (*)(struct dw_pcie_ep *, unsigned char, enum pci_epc_irq_type, unsigned sort)') with an expression of type 'int (struct dw_pcie_ep *, u8, unsigned int, u16)' (aka 'int (struct dw_pcie_ep *, unsigned char, unsigned int, unsigned short)') [-Werror,-Wincompatible-function-pointer-types-strict]
    403 |         .raise_irq = rcar_gen4_pcie_ep_raise_irq,
        |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

'->raise_irq()' in 'struct dw_pcie_ep_ops' expects a type parameter of
type 'enum pci_epc_irq_type', not 'unsigned int'. Adjust the type to
match and use the proper enum values in the switch. The underlying value
of both the enum and the macro is the same, so there is no functional
change while clearing up the warning and avoiding a CFI failure at run
time.

Fixes: 32b83c68d634 ("PCI: rcar-gen4: Add endpoint mode support")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>