jfs: add extra superblock validation
Syzbot has reported the following crash:

ERROR: (device loop0): txBegin: read-only filesystem
ERROR: (device loop0): remounting filesystem as read-only
ERROR: (device loop0): dbFindCtl: Corrupt dmapctl page
jfs_create: dtInsert returned -EIO
ERROR: (device (efault)): txAbort:
Oops: general protection fault, probably for non-canonical address <...>
KASAN: null-ptr-deref in range [0x0000000000000050-0x0000000000000057]
...
Call Trace:
 <TASK>
 ? die_addr.cold+0x8/0xd
 ? exc_general_protection+0x147/0x240
 ? asm_exc_general_protection+0x26/0x30
 ? vprintk+0x86/0xa0
 ? jfs_error+0x10a/0x2a0
 ? dtInsert+0x72f/0xb10
 ? __pfx_jfs_error+0x10/0x10
 ? vprintk+0x86/0xa0
 ? _printk+0xd0/0x108
 ? __pfx__printk+0x10/0x10
 ? txAbort+0x332/0x540
 txAbort+0x382/0x540
 jfs_create+0x48e/0xb00
 ? __pfx_jfs_create+0x10/0x10
 ? generic_permission+0x230/0x690
 ? bpf_lsm_inode_permission+0x9/0x10
 ? security_inode_permission+0xbf/0x250
 ? inode_permission+0xba/0x5d0
 vfs_create+0x4e6/0x7a0
 do_mknodat+0x2f7/0x5d0
 ? __pfx_do_mknodat+0x10/0x10
 ? getname_flags.part.0+0x1c5/0x550
 __x64_sys_mknod+0x118/0x170
 do_syscall_64+0xc7/0x250
 entry_SYSCALL_64_after_hwframe+0x77/0x7f
...
 </TASK>

This happens during the mid-air condition when superblock is artificially
damaged before remount issued after superblock touch via 'fspick()' and
'fsconfig()'. So add basic superblock validation in 'readSuper()' and
do not go further if 'updateSuper()' returns non-zero error code.

Reported-by: syzbot+5f0d7af0e45fae10edd1@syzkaller.appspotmail.com
Closes: https://syzkaller.appspot.com/bug?extid=5f0d7af0e45fae10edd1
Fixes: 1da177e4c3f4 ("Linux-2.6.12-rc2")
Signed-off-by: Dmitry Antipov <dmantipov@yandex.ru>