rtc: pcf85063: hide an unused variable
The newly introduced configuration is only used by code that is
inside of an #ifdef block, cauing a warning when that block is
disabled by the configuration is still there:

drivers/rtc/rtc-pcf85063.c:566:37: error: 'config_rv8063' defined but not used [-Werror=unused-const-variable=]

Add the same #ifdef here.

Fixes: a3c7f7e16ea8 ("rtc: pcf85063: add support for RV8063")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>