bcachefs: Remove an unused label
Trivial fix for an issue that triggered -Werror.

fs/bcachefs/btree_io.c: In function ‘validate_bset’:
fs/bcachefs/btree_io.c:828:1: error: label ‘out’ defined but not used [-Werror=unused-label]
  828 | out:
      | ^~~
cc1: all warnings being treated as errors

Fixes: a78c8274ea0c7ebccf2474a9c2e4a15cead79295 ("bcachefs: Fix validate_bset() repair path")

Signed-off-by: Gabriel de Perthuis <g2p.code@gmail.com>