docs/vfs: Fix htmldocs build warning and error
Running "make htmldocs" generates the following build warning and error
in fs/namei.c:

Documentation/filesystems/api-summary:56: ./fs/namei.c:4952: WARNING: Inline emphasis start-string without end-string. [docutils]
Documentation/filesystems/api-summary:56: ./fs/namei.c:4942: ERROR: Unknown target name: "o". [docutils]

The error happens due to 'O_' being treated as a named reference by
docutils and the warning happens due to '*' in 'struct file *' being
treated as beginning of emphasis text.

Replace 'O_' with 'O_*' to avoid being treated as a named reference and
reword the return comment to fix the build warning and error.

Signed-off-by: Gopi Krishna Menon <krishnagopi487@gmail.com>