efi: Fix missing `efi_handover_entry` prototype
We get 1 error when building kernel withW=1:
drivers/firmware/efi/libstub/x86-stub.c:1068:6: error: no previous prototype for ‘efi_handover_entry’ [-Werror=missing-prototypes]
 1068 | void efi_handover_entry(efi_handle_t handle, efi_system_table_t *sys_table_arg,
      |      ^~~~~~~~~~~~~~~~~~

As this function is only used in the file, mark it as 'static'.

Signed-off-by: Zhou Ding <zhouding@cmss.chinamobile.com>