platform/x86:intel/pmc: fix build regression with pmtimer turned off
The acpi_pmtmr_{un,}register_suspend_resume_callback() declarations
got added into an #ifdef section without an alternative inline
stub, which now causes a build failure:

drivers/platform/x86/intel/pmc/core.c: In function 'pmc_core_probe':
drivers/platform/x86/intel/pmc/core.c:1507:17: error: implicit declaration of function 'acpi_pmtmr_register_suspend_resume_callback' [-Wimplicit-function-declaration]
 1507 |                 acpi_pmtmr_register_suspend_resume_callback(pmc_core_acpi_pm_timer_suspend_resume,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/platform/x86/intel/pmc/core.c: In function 'pmc_core_remove':
drivers/platform/x86/intel/pmc/core.c:1523:17: error: implicit declaration of function 'acpi_pmtmr_unregister_suspend_resume_callback' [-Wimplicit-function-declaration]
 1523 |                 acpi_pmtmr_unregister_suspend_resume_callback();
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Remove the unnecessary #ifdef and use IS_ENABLED() checks in the
respective callers.

Fixes: e774696b1f95 ("platform/x86:intel/pmc: Enable the ACPI PM Timer to be turned off when suspended")
Fixes: fe323dcb12fd ("clocksource: acpi_pm: Add external callback for suspend/resume")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>