perf parse-events: Remove BPF event support
New features like the BPF --filter support in perf record have made
the BPF event functionality somewhat redundant. As shown by commit
fcb027c1a4f6 ("perf tools: Revert enable indices setting syntax for
BPF map") and commit 14e4b9f4289a ("perf trace: Raw augmented syscalls
fix libbpf 1.0+ compatibility") the BPF event support hasn't been well
maintained and it adds considerable complexity in areas like event
parsing, not least as '/' is a separator for event modifiers as well
as in paths.

The BPF events also motivate llvm and clang libraries as dependencies
(to compile BPF events that are BPF C code) that have build and
distribution complexity. For this reason they are only enabled with
the build option LIBLLVMCLANG=1 which isn't done on major
distributions like Debian, Fedora and Gentoo. Removing BPF events
means we can also remove libclang and libllvm dependencies.

This patch removes support in the event parser for BPF events and then
the associated functions are removed. This leads to the removal of
whole source files like bpf-loader.c.  Removing support means that
augmented syscalls in perf trace is broken, this will be fixed in a
later commit adding support using BPF skeletons.

The removal of BPF events causes an unused label warning from flex
generated code, so update build to ignore it:
```
util/parse-events-flex.c:2704:1: error: label ‘find_rule’ defined but not used [-Werror=unused-label]
2704 | find_rule: /* we branch to this label when backing up */
```

Signed-off-by: Ian Rogers <irogers@google.com>