net: pse-pd: tps23881: Fix the compiler error about implicit declaration of function ‘FIELD_GET’
bitfield.h is not explicitly included but it is required for FIELD_GET.
There will be a compiler error:
  drivers/net/pse-pd/tps23881.c: In function ‘tps23881_i2c_probe’:
  drivers/net/pse-pd/tps23881.c:755:6: error: implicit declaration of function ‘FIELD_GET’ [-Werror=implicit-function-declaration]
    755 |  if (FIELD_GET(TPS23881_REG_DEVID_MASK, ret) != TPS23881_DEVICE_ID) {
        |      ^~~~~~~~~
  cc1: some warnings being treated as errors

Fixes: 89108cb5c285 (net: pse-pd: tps23881: Fix the device ID check)
Signed-off-by: Guanjun <guanjun@linux.alibaba.com>