selftests: x86: test_FISTTP: use fisttps instead of ambiguous fisttp
Use fisttps instead of fisttp to specify correctly that the output
variable is of size short.

test_FISTTP.c:28:3: error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
   28 |         "       fisttp  res16""\n"
      |          ^
<inline asm>:3:2: note: instantiated into assembly here
    3 |         fisttp  res16
      |         ^

...followed by three more cases of the same warning for other lines.

Signed-off-by: Muhammad Usama Anjum <usama.anjum@collabora.com>
[jh: removed a bit of duplication from the warnings report, above, and
     fixed a typo in the title]
Signed-off-by: John Hubbard <jhubbard@nvidia.com>