init/Kconfig: lower to GCC version 9 check for -Warray-bounds
commit 3e00f5802fab ("init/Kconfig: lower GCC version check for -Warray-bounds")
lowers GCC version check for -Warray-bounds, but I continue to see false positives
from -Warray-bounds in GCC 9.4.

This happens after
commit b44759705f7d ("bitmap: make bitmap_{get,set}_value8() use bitmap_{read,write}()")

During the rcuturture test in Ubuntu 20.04 GCC 9.4.0 x86_64, the compiling of
drivers/gpio/gpio-pca953x.c issues following warning:

```
  CC      drivers/gpio/gpio-pca953x.o
In file included from drivers/gpio/gpio-pca953x.c:12:
drivers/gpio/gpio-pca953x.c: In function ‘pca953x_probe’:
./include/linux/bitmap.h:799:17: error: array subscript [1, 1024] is outside array bounds of ‘long unsigned int[1]’ [-Werror=array-bounds]
  799 |  map[index + 1] &= BITMAP_FIRST_WORD_MASK(start + nbits);
      |                 ^~
In file included from ./include/linux/atomic.h:5,
                 from drivers/gpio/gpio-pca953x.c:11:
drivers/gpio/gpio-pca953x.c:1015:17: note: while referencing ‘val’
 1015 |  DECLARE_BITMAP(val, MAX_LINE);
      |                 ^~~
./include/linux/types.h:11:16: note: in definition of macro ‘DECLARE_BITMAP’
   11 |  unsigned long name[BITS_TO_LONGS(bits)]
      |                ^~~~
In file included from drivers/gpio/gpio-pca953x.c:12:
./include/linux/bitmap.h:800:17: error: array subscript [1, 1024] is outside array bounds of ‘long unsigned int[1]’ [-Werror=array-bounds]
  800 |  map[index + 1] |= (value >> space);
      |  ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/atomic.h:5,
                 from drivers/gpio/gpio-pca953x.c:11:
drivers/gpio/gpio-pca953x.c:1015:17: note: while referencing ‘val’
 1015 |  DECLARE_BITMAP(val, MAX_LINE);
      |                 ^~~
./include/linux/types.h:11:16: note: in definition of macro ‘DECLARE_BITMAP’
   11 |  unsigned long name[BITS_TO_LONGS(bits)]
```

Disable gcc-9+ array-bounds avoid above warning.

Signed-off-by: Zhouyi Zhou <zhouzhouyi@gmail.com>