scripts/gdb: fix parsing of MNT_* constants
Recently, constants in linux/mount.h were changed from integer macros
parsable by LX_VALUE() to enums which are not, thus breaking gdb python
scripts:

  Reading symbols from vmlinux...
  Traceback (most recent call last):
    File ".../linux/vmlinux-gdb.py", line 25, in <module>
      import linux.constants
    File ".../linux/scripts/gdb/linux/constants.py", line 19, in <module>
      LX_MNT_NOSUID = MNT_NOSUID
  NameError: name 'MNT_NOSUID' is not defined

Update to parse with LX_GDBPARSED(), which correctly handles enums.

Fixes: 101f2bbab541 ("fs: convert mount flags to enum")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>