sched: drop unused variable cpumask in mm_cid_get()
When compiling with W=1, we get the following warning:

In file included from kernel/sched/rq-offsets.c:5:
kernel/sched/sched.h:3743:18: error: variable 'cpumask' set but not used [-Werror,-Wunused-but-set-variable]
 3743 |         struct cpumask *cpumask;
      |                         ^
1 error generated.

Simply drop the variable.

Signed-off-by: André Draszik <andre.draszik@linaro.org>