net: dsa: realtek: add LEDS_CLASS dependency
This driver fails to link when LED support is disabled:

ERROR: modpost: "led_init_default_state_get" [drivers/net/dsa/realtek/rtl8366.ko] undefined!
ERROR: modpost: "devm_led_classdev_register_ext" [drivers/net/dsa/realtek/rtl8366.ko] undefined!

Add a dependency that prevents this configuration.

Fixes: 32d617005475 ("net: dsa: realtek: add LED drivers for rtl8366rb")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>