drm/pagemap: avoid referencing HPAGE_PMD_ORDER for non-hugepage builds
HPAGE_PMD_SHIFT/HPAGE_PMD_ORDER can only be used in configurations
that allow hugepages, but forces a build error otherwise:

drivers/gpu/drm/drm_pagemap.c:671:48: error: call to '__compiletime_assert_608' declared with 'error' attribute: BUILD_BUG failed
  671 |                                       folio_order(page_folio(src_page)) != HPAGE_PMD_ORDER,
      |                                                                            ^
include/linux/huge_mm.h:117:26: note: expanded from macro 'HPAGE_PMD_ORDER'
  117 | #define HPAGE_PMD_ORDER (HPAGE_PMD_SHIFT-PAGE_SHIFT)
      |                          ^
include/linux/huge_mm.h:113:28: note: expanded from macro 'HPAGE_PMD_SHIFT'
  113 | #define HPAGE_PMD_SHIFT ({ BUILD_BUG(); 0; })
      |                            ^
include/linux/build_bug.h:60:21: note: expanded from macro 'BUILD_BUG'
   60 | #define BUILD_BUG() BUILD_BUG_ON_MSG(1, "BUILD_BUG failed")
      |                     ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
include/linux/compiler_types.h:697:2: note: expanded from macro '_compiletime_assert'
  697 |         __compiletime_assert(condition, msg, prefix, suffix)
      |         ^

Hide this inside of a check for CONFIG_PGTABLE_HAS_HUGE_LEAVES.

Fixes: 192cb1f5cb16 ("drm/pagemap: Enable THP support for GPU memory migration")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>