platform/loongarch: laptop: Fix build error due to backport
In 6.1/6.6 there is no BACKLIGHT_POWER_ON definition so a build error
occurs due to recently backport:

  CC      drivers/platform/loongarch/loongson-laptop.o
drivers/platform/loongarch/loongson-laptop.c: In function 'laptop_backlight_register':
drivers/platform/loongarch/loongson-laptop.c:428:23: error: 'BACKLIGHT_POWER_ON' undeclared (first use in this function)
  428 |         props.power = BACKLIGHT_POWER_ON;
      |                       ^~~~~~~~~~~~~~~~~~

Use FB_BLANK_UNBLANK instead which has the same meaning.

Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>