rust: num: add `cv!` macro to create values from constant expressions
Currently, constructing a `NonZero` or `Bounded` from a constant is
verbose. The former would require `const { NonZero::new(...).unwrap() }`
and the latter require turbofish. Similarly, the `num::casts` exposes
methods that cast numbers using turbofish syntax, which is unergonomic and
unnecessarily causes the value to flow into the type system, which is very
restrictive without `generic_const_exprs`.

Implement a macro `cv!` (short for constant value) which converts a const
integer to types that implements `FromConst` trait and validate them during
const evaluation.

The usage is of form

    cv!(<expression>)

for inferred type and

    cv!(<expression> => <type>)

for explicit type specification.

As we do not have const trait implementation yet, dark magic is used. The
dark magic is documented in the code, but in essence it defines inherent
`__from_const` impls on types, which can be marked const, and rely on
Rust's method resolution algorithm to pick the correct function. Multiple
helpers are defined to aid type inference to work properly.

As a result, this allows construction of primitive integers, `NonZero`,
`Bounded`, `Alignment` using a single `cv!` macro. This macro does not have
`generic_const_exprs` restrictions (e.g. in a function with `const N: u32`
generic parameter, you may use `cv!(N + 1)`), it supports full type
inference and it has nice error messages in some common error scenario:

    error[E0080]: evaluation panicked: constant is zero
       --> example.rs:22:25
        |
     22 | const X: NonZero<u32> = cv!(0);
        |                         ^^^^^^ evaluation of `X::{constant#0}` failed inside this call

    error[E0277]: `kernel::page::Page` cannot be converted from constant
       --> example.rs:22:17
        |
     22 | const X: Page = cv!(0);
        |                 ^^^^^^ the trait `kernel::num::FromConst` is not implemented for `kernel::page::Page`

Of course, this trick is not full const trait impl. So the following code cannot work properly:

    fn generic<T: FromConst>() -> T {
        cv!(0)
    }

That said, useful error message is still produced in this context.

    error[E0080]: evaluation panicked: `cv!()` cannot be used with generic types yet
       --> example.rs:23:5
        |
     22 |     cv!(0)
        |     ^^^^^^ evaluation of `generic::<u32>::{constant#0}` failed inside this call

Co-developed-by: Eliot Courtney <ecourtney@nvidia.com>
Signed-off-by: Eliot Courtney <ecourtney@nvidia.com>
Signed-off-by: Gary Guo <gary@garyguo.net>