x86/hyperv: Fix smp_ops build failure on UP kernels
CI testing found this build failure:

  arch/x86/hyperv/hv_crash.c:631:9: error: ‘smp_ops’ undeclared (first use in this function)

And I bisected it back to the initial commit that enabled this feature:

  182bfe213cf44614d3a7aa6e6efbfb1b64301369 is the first bad commit
  commit 182bfe213cf44614d3a7aa6e6efbfb1b64301369 (HEAD)
  Author: Mukesh Rathor <mrathor@linux.microsoft.com>
  Date:   Mon Oct 6 15:42:08 2025 -0700

  x86/hyperv: Enable build of hypervisor crashdump collection files

Hyperv should probably be limited to SMP kernels, as nobody
appears to be testing it on UP kernels.

Until then, fix the smp_ops assumption. Build tested only.

Fixes: 182bfe213cf44 ("x86/hyperv: Enable build of hypervisor crashdump collection files")
Cc: Mukesh Rathor <mrathor@linux.microsoft.com>
Cc: Wei Liu <wei.liu@kernel.org>
Cc: linux-kernel@vger.kernel.org
Signed-off-by: Ingo Molnar <mingo@kernel.org>