docs: rust: quick-start: Add another way to install
When compiling with LLVM and CONFIG_RUST is set, there is build error on
LoongArch:

     --> rust/kernel/lib.rs:331:13
      |
  331 |         loc.file_with_nul()
      |             ^^^^^^^^^^^^^ method not found in `&'a Location<'a>`

  error: aborting due to 1 previous error

It seems that the latest version of rustc is not compatible, in order to
install the workable rustc version for LoongArch, there is another simple
and easy way, add it to the Quick Start guide.

Suggested-by: WANG Rui <wangrui@loongson.cn>
Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>