rust: device: avoid trailing ; in printing macros
These macros are used like expressions, so they should must not emit a
semicolon. This is being turned into a hard error in a future release of
Rust.

error: trailing semicolon in macro used in expression position
  --> drivers/gpu/nova-core/firmware/fsp.rs:79:34
   |
79 |                 .inspect_err(|_| dev_err!(dev, "FMC firmware missing '{}' section\n", name))
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
   = note: this error originates in the macro `dev_err` (in Nightly builds, run with -Z macro-backtrace for more info)

Cc: stable@vger.kernel.org
Fixes: 5c7ca6fa603f ("rust: add `dev_*` print macros.")
Link: https://github.com/rust-lang/rust/issues/79813
Signed-off-by: Alice Ryhl <aliceryhl@google.com>