irqchip: build IMX_MU_MSI only on ARM
compile-testing IMX_MU_MSI on x86 without PCI_MSI support results
in a build failure:

drivers/gpio/gpio-sprd.c:8:
include/linux/gpio/driver.h:41:33: error: field 'msiinfo' has incomplete type
drivers/iommu/iommufd/viommu.c:4:
include/linux/msi.h:528:33: error: field 'alloc_info' has incomplete type

Tighten the dependency further to only allow compile testing on Arm.
This could be refined further to allow certain x86 configs.

I submitted this patch before to address a different build failure, which
was fixed independently but has now returned.

Link: https://lore.kernel.org/all/20221215164109.761427-1-arnd@kernel.org/
Fixes: 70afdab904d2d1e6 ("irqchip: Add IMX MU MSI controller driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>