Revert "drm/msm/mdp5: provide dynamic bandwidth management"
This reverts commit 12fd1ef6aabd781eeee647d6446cc1eca9710a81.

Breaks armv7 build

  ERROR: modpost: "__aeabi_ldivmod" [drivers/gpu/drm/msm/msm.ko] undefined!

Signed-off-by: Rob Clark <robdclark@chromium.org>