selftests: harness: Mark test fixture objects __maybe_unused
Mark test fixture objects __maybe_unused since they will not be used
when there are fixture variants (the variants will be used instead).

This fixes the VFIO selftest build with clang and -Werror:

vfio_dma_mapping_mmio_test.c:106:1: error: variable '_vfio_dma_mapping_mmio_test_map_full_bar_object' set but not used [-Werror,-Wunused-but-set-global]
  106 | TEST_F(vfio_dma_mapping_mmio_test, map_full_bar)
      | ^
./../kselftest_harness.h:398:2: note: expanded from macro 'TEST_F'
  398 |         __TEST_F_IMPL(fixture_name, test_name, -1, TEST_TIMEOUT_DEFAULT)
      |         ^
./../kselftest_harness.h:470:33: note: expanded from macro '__TEST_F_IMPL'
  470 |         static struct __test_metadata *_##fixture_name##_##test_name##_object; \
      |

Fixes: ff556bd98348 ("vfio: selftests: Add -Wall and -Werror to the Makefile")
Reported-by: Aaron Lewis <aaronlewis@google.com>
Signed-off-by: David Matlack <dmatlack@google.com>