serial: max310x: fix I2C-only build
Allowing the driver to be built when CONFIG_SPI_MASTER is turned off
now causes build failures:

drivers/tty/serial/max310x.c: In function 'max310x_uart_init':
drivers/tty/serial/max310x.c:1737:32: error: 'max310x_spi_driver' undeclared (first use in this function); did you mean 'max310x_i2c_driver'?
 1737 |         spi_unregister_driver(&max310x_spi_driver);
      |                                ^~~~~~~~~~~~~~~~~~
      |                                max310x_i2c_driver
drivers/tty/serial/max310x.c:1737:32: note: each undeclared identifier is reported only once for each function it appears in
drivers/tty/serial/max310x.c:1740:1: error: label 'err_spi_register' defined but not used [-Werror=unused-label]
 1740 | err_spi_register:
      | ^~~~~~~~~~~~~~~~
drivers/tty/serial/max310x.c: At top level:
drivers/tty/serial/max310x.c:1502:29: error: 'regcfg' defined but not used [-Werror=unused-variable]
 1502 | static struct regmap_config regcfg = {
      |                             ^~~~~~

While fixing this, I ran into another problem with I2C=m, which
previously would just not use I2C support.

Fix the #ifdef checks to handle all combinations correctly, and
change the Kconfig dependency to ensure that the driver cannot
be built-in when I2C=m.

Fixes: 20ffe4b3330a ("serial: max310x: allow driver to be built with SPI or I2C")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>