btrfs: don't allow adding block device of less than 1 MB
Commit 15ae0410 in btrfs-progs inadvertently changed it so that if the
BLKGETSIZE64 ioctl on a block device returned a size of 0, this was no
longer seen as an error condition.

Unfortunately this is how disconnected NBD devices behave, meaning that
with btrfs-progs 6.16 it's now possible to add a device you can't
remove:

~ # btrfs device add /dev/nbd0 /root/temp
~ # btrfs device remove /dev/nbd0 /root/temp
ERROR: error removing device '/dev/nbd0': Invalid argument

This check should always have been done kernel-side anyway, so add a
check in btrfs_init_new_device() that the new device doesn't have a size
less than BTRFS_DEVICE_RANGE_RESERVED (i.e. 1 MB).

Signed-off-by: Mark Harmstone <mark@harmstone.com>