selftests: x86: test_FISTTP: use fisttps instead of ambigous fisttp
Use fisttps instead of fisttp to specify correctly that the output
variable is of size short.

test_FISTTP.c:28:3: error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
   28 |         "       fisttp  res16""\n"
      |          ^
<inline asm>:3:2: note: instantiated into assembly here
    3 |         fisttp  res16
      |         ^
test_FISTTP.c:48:3: error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
   48 |         "       fisttp  res16""\n"
      |          ^
<inline asm>:3:2: note: instantiated into assembly here
    3 |         fisttp  res16
      |         ^
test_FISTTP.c:69:3: error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
   69 |         "       fisttp  res16""\n"
      |          ^
<inline asm>:4:2: note: instantiated into assembly here
    4 |         fisttp  res16
      |         ^
test_FISTTP.c:91:3: error: ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
   91 |         "       fisttp  res16""\n"
      |          ^
<inline asm>:3:2: note: instantiated into assembly here
    3 |         fisttp  res16
      |         ^

Signed-off-by: Muhammad Usama Anjum <usama.anjum@collabora.com>