btrfs: fix btrfs_parse_param() build failure
With CONFIG_BTRFS_FS_POSIX_ACL disabled, the newly added function fails
to build because of an apparent broken rebase:

fs/btrfs/super.c: In function 'btrfs_parse_param':
fs/btrfs/super.c:416:25: error: 'ret' undeclared (first use in this function); did you mean 'net'?
  416 |                         ret = -EINVAL;
      |                         ^~~

Just return the error directly here instead of the incorrect unwinding.

Fixes: a7293bf27082 ("btrfs: add parse_param callback for the new mount api")
Reported-by: Linux Kernel Functional Testing <lkft@linaro.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>