ARM: OMAP2+: hwmod: remove misuse of kernel-doc
kernel-doc does not support documenting data definitions, so change
the "/**" comments to common "/*" comments to avoid kernel-doc
warnings:

omap_hwmod_common_data.c:37: error: Cannot parse struct or union!
omap_hwmod_common_data.c:51: error: Cannot parse struct or union!
omap_hwmod_common_data.c:60: error: Cannot parse struct or union!

Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Paul Walmsley <paul@pwsan.com>
Cc: Tony Lindgren <tony@atomide.com>
Cc: linux-omap@vger.kernel.org
Cc: Russell King <linux@armlinux.org.uk>
Cc: linux-arm-kernel@lists.infradead.org
Cc: patches@armlinux.org.uk