kbuild: change __retain macro for gcc-11
Building kernels with CONFIG_LD_DEAD_CODE_DATA_ELIMINATION using gcc-11
causes compiler warnings:

kernel/cgroup/rstat.c:65:1: error: 'retain' attribute ignored [-Werror=attributes]

It appears that this version reports __has_attribute(__retain__) as true
but doesn't actually support the feature.

Fixes: 0a5d3258d7c9 ("compiler_types.h: Define __retain for __attribute__((__retain__))")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>