mux: mmio: Fix missing CONFIG_REGMAP_MMIO
MMIO mux uses now regmap_init_mmio(), so one way or another
CONFIG_REGMAP_MMIO should be enabled, because there are no stubs for
!REGMAP_MMIO case:

  ERROR: modpost: "__regmap_init_mmio_clk" [drivers/mux/mux-mmio.ko] undefined!

REGMAP_MMIO should be, because it is a non-visible symbol, but this
causes a circular dependency:

  error: recursive dependency detected!
  symbol IRQ_DOMAIN is selected by REGMAP
  symbol REGMAP default is visible depending on REGMAP_MMIO
  symbol REGMAP_MMIO is selected by MUX_MMIO
  symbol MUX_MMIO depends on MULTIPLEXER
  symbol MULTIPLEXER is selected by MDIO_BUS_MUX_MULTIPLEXER
  symbol MDIO_BUS_MUX_MULTIPLEXER depends on MDIO_DEVICE
  symbol MDIO_DEVICE is selected by PHYLIB
  symbol PHYLIB is selected by ARC_EMAC_CORE
  symbol ARC_EMAC_CORE is selected by EMAC_ROCKCHIP
  symbol EMAC_ROCKCHIP depends on OF_IRQ
  symbol OF_IRQ depends on IRQ_DOMAIN

... which we can break by changing dependency in EMAC_ROCKCHIP from
OF_IRQ to OF.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202505150312.dYbBqUhG-lkp@intel.com/
Fixes: 61de83fd8256 ("mux: mmio: Do not use syscon helper to build regmap")
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>