media: cec: Add missing I2C dependency
If CONFIG_I2C is not set, build fails:

drivers/media/cec/i2c/tda9950.c: In function ‘tda9950_probe’:
drivers/media/cec/i2c/tda9950.c:391:14: error: implicit declaration of function ‘i2c_check_functionality’ [-Werror=implicit-function-declaration]
	if (!i2c_check_functionality(client->adapter, I2C_FUNC_I2C)) {
      |              ^~~~~~~~~~~~~~~~~~~~~~~
  CC      crypto/aes_generic.o
drivers/media/cec/i2c/tda9950.c: At top level:
drivers/media/cec/i2c/tda9950.c:503:1: warning: data definition has no type or storage class
  503 | module_i2c_driver(tda9950_driver);
      | ^~~~~~~~~~~~~~~~~
drivers/media/cec/i2c/tda9950.c:503:1: error: type defaults to ‘int’ in declaration of ‘module_i2c_driver’ [-Werror=implicit-int]
drivers/media/cec/i2c/tda9950.c:503:1: warning: parameter names (without types) in function declaration

Add missing I2C dependency to fix this.

Fixes: caa6f4a75e9f ("media: cec: move driver for TDA9950 from drm/i2c")
Signed-off-by: Yue Haibing <yuehaibing@huawei.com>