drm/xe/configfs: fix clang warnings for missing parameter name
Fixes warning from clang-17 that look like:

drivers/gpu/drm/xe/xe_configfs.h:35:97: error: omitting the parameter name in a function definition is a C2x extension [-Werror,-Wc2x-extensions]
   35 | static inline u32 xe_configfs_get_ctx_restore_post_bb(struct pci_dev *pdev, enum xe_engine_class,

Signed-off-by: Ryan Neph <ryanneph@google.com>