MIPS: vpe-mt: drop unused functions vpe_alloc() and vpe_start()
These two functions are defined but unused. Removing them to silence
the missing prototypes warnings:

arch/mips/kernel/vpe-mt.c:180:7: error: no previous prototype for 'vpe_alloc' [-Werror=missing-prototypes]
  180 | void *vpe_alloc(void)
      |       ^~~~~~~~~
arch/mips/kernel/vpe-mt.c:198:5: error: no previous prototype for 'vpe_start' [-Werror=missing-prototypes]
  198 | int vpe_start(void *vpe, unsigned long start)
      |     ^~~~~~~~~

Signed-off-by: Shiji Yang <yangshiji66@outlook.com>