selftests: net: Work around build error seen with -Werror
Fix

ksft.h: In function ‘ksft_ready’:
ksft.h:27:9: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’

ksft.h: In function ‘ksft_wait’:
ksft.h:51:9: error: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’

by checking and then ignoring the return value of the affected functions.

Fixes: 2b6d490b82668 ("selftests: drv-net: Factor out ksft C helpers")
Cc: Joe Damato <jdamato@fastly.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>