kunit: Check for kunit_parse_glob_filter() failure
Smatch complains that the missing error checks would lead to a crash:

    lib/kunit/executor_test.c:40 parse_filter_test()
    error: double free of 'filter.test_glob'

We may as well do it right...

Fixes: a127b154a8f2 ("kunit: tool: allow filtering test cases via glob")
Signed-off-by: Dan Carpenter <dan.carpenter@linaro.org>