pref/x86/rapl: Remove unused function
get_rapl_pmu_cpumask() is unused, it prevents kernel builds
with clang, `make W=1` and CONFIG_WERROR=y:

  arch/x86/events/rapl.c:165:37: error: unused function 'get_rapl_pmu_cpumask' [-Werror,-Wunused-function]

Fix this by removing unused function.

See also commit 6863f5643dd7 ("kbuild: allow Clang to find unused static
inline functions for W=1 build").

Fixes: 9e9af8bbb5f9 ("perf/x86/rapl: Clean up cpumask and hotplug")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>