iomap: provide iomap_want_unshare_iter() stub for !CONFIG_BLOCK
When block device support is disabled, DAX fails to link with:

aarch64-linux/bin/aarch64-linux-ld: fs/dax.o: in function `dax_file_unshare':
dax.c:(.text+0x2694): undefined reference to `iomap_want_unshare_iter'

Return false in this case, as far as I can tell, this cannot happen
without block devices.

Fixes: 6ef6a0e821d3 ("iomap: share iomap_unshare_iter predicate code with fsdax")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>