tools/mm: fix show_page() build error
At one point I needed mm tools for debugging but couldn't compile them due to the
following error:

gcc -Wall -Wextra -I../lib/ -pthread -o page-types page-types.c ../lib/api/libapi.a -pthread
page-types.c: In function ‘show_page’:
page-types.c:423:49: error: expected ‘;’ before ‘if’
  423 |                 printf("@%" PRIu64 "\t", cgroup)
      |                                                 ^
      |                                                 ;
  424 |         if (opt_list_mapcnt)
      |         ~~
page-types.c:416:65: warning: unused parameter ‘mapcnt’ [-Wunused-parameter]
  416 |                       uint64_t flags, uint64_t cgroup, uint64_t mapcnt)
      |                                                        ~~~~~~~~~^~~~~~
make: *** [Makefile:23: page-types] Error 1

Trailing ; was forgotten, so add it.

Fixes: ece5897e5a10 ("tools/mm: -Werror fixes in page-types/slabinfo")
Signed-off-by: Oleksandr Natalenko <oleksandr@natalenko.name>