tools headers: Sync UAPI linux/openat2.h with the kernel sources
Since commit 3d6cfbaf279d ("perf beauty: Introduce scrape script for
various fs syscalls 'flags' arguments"), the file
tools/perf/trace/beauty/include/uapi/linux/fcntl.h includes
<linux/openat2.h>, but openat2.h was never synced to the
tools/perf/trace/beauty/include/uapi/linux/ directory, even though it
was added to the BEAUTY_FILES check list in tools/perf/check-headers.sh.

This causes a compilation failure:
  $ aarch64-linux-gnu-gcc -E
  tools/perf/trace/beauty/include/uapi/linux/fcntl.h \
  -I./tools/perf/trace/beauty/include/uapi

  tools/perf/trace/beauty/include/uapi/linux/fcntl.h:6:10: fatal error:
  linux/openat2.h: No such file or directory 6 | #include
  <linux/openat2.h>

So, now we need sync openat2.h from include/uapi/linux/openat2.h to fix this
dependency.

Signed-off-by: Wang Xiang <wangxiang3@lixiang.com>