Revert "btrfs: add 32-bit compat ioctl for BTRFS_IOC_GET_SUBVOL_INFO"
This reverts commit 538e5bdbc8996d3f6ce65565dda7df58e6e97e04.

This patch is causing libbtrfsutils regression on 64bit systems, which
is the most common cases.

The involved selftests failures look like this, all related to
unprivileged ioctls:

 ======================================================================
 FAIL: test_subvolume_get_info_unprivileged (test_subvolume.TestSubvolume.test_subvolume_get_info_unprivileged)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 336, in test_subvolume_get_info_unprivileged
     self._test_subvolume_info(subvol, snapshot)
     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 196, in _test_subvolume_info
     self.assertEqual(info.id, 256)
     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
 AssertionError: 140488005556880 != 256

 ======================================================================
 FAIL: test_subvolume_info_unprivileged (test_subvolume.TestSubvolume.test_subvolume_info_unprivileged)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 318, in test_subvolume_info_unprivileged
     self._test_subvolume_info(subvol, snapshot)
     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 196, in _test_subvolume_info
     self.assertEqual(info.id, 256)
     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
 AssertionError: 140488005503648 != 256

 ======================================================================
 FAIL: test_subvolume_iterator_unprivileged (test_subvolume.TestSubvolume.test_subvolume_iterator_unprivileged)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 835, in test_subvolume_iterator_unprivileged
     self._test_subvolume_iterator()
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
   File "/home/adam/btrfs-progs/libbtrfsutil/python/tests/test_subvolume.py", line 700, in _test_subvolume_iterator
     self.assertEqual(subvol.id, 256)
     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
 AssertionError: 0 != 256

Adding 32bit compatibility should never cause regression on 64bit
systems.

Revert the offending commit to avoid regression.

Signed-off-by: Qu Wenruo <wqu@suse.com>