iio: dac: ad5755: mark OF related data as maybe unused
When compile tested with W=1 on x86_64 with driver as built-in:

  ad5755.c:866:34: error: unused variable 'ad5755_of_match' [-Werror,-Wunused-const-variable]

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>