firmware: arm_ffa: Fix beyond size of field warning
An allmodconfig build of arm64 resulted in following warning:

	In function ‘fortify_memcpy_chk’,
	    inlined from ‘export_uuid’ at ./include/linux/uuid.h:88:2,
	    inlined from ‘ffa_msg_send_direct_req2’ at ./drivers/firmware/arm_ffa/driver.c:488:2:
	./include/linux/fortify-string.h:571:25: error: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
	  571 |                         __write_overflow_field(p_size_field, size);
	      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	In function ‘fortify_memcpy_chk’,
	    inlined from ‘ffa_msg_send_direct_req2’ at ./drivers/firmware/arm_ffa/driver.c:489:2:
	./linux-next/include/linux/fortify-string.h:571:25: error: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror=attribute-warning]
	  571 |                         __write_overflow_field(p_size_field, size);
	      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Because ffa_msg_send_direct_req2() memcpy uuid_t and struct
ffa_send_direct_data2 data to unsigned long dst, the copy size is 2 or
or 14 unsigned long which beyond size of dst size, fix it by using a temp
array for memcpy.

Signed-off-by: Jinjie Ruan <ruanjinjie@huawei.com>