perf/x86/intel: Fix the building warning for i386 arch
The warnings below are seen for building i386 arch image.

arch/x86/events/intel/ds.c: In function 'intel_pmu_drain_arch_pebs':
arch/x86/events/intel/ds.c:2983:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
 2983 |         top = (void *)((u64)cpuc->pebs_vaddr +
      |                        ^
arch/x86/events/intel/ds.c:2983:15: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 2983 |         top = (void *)((u64)cpuc->pebs_vaddr +
      |               ^
cc1: all warnings being treated as errors

change "u64" to "unsigned long" to fix the building error.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Closes: https://lore.kernel.org/all/20251112154200.4d3671f9@canb.auug.org.au/
Fixes: d21954c8a0ff ("perf/x86/intel: Process arch-PEBS records or record fragments")
Signed-off-by: Dapeng Mi <dapeng1.mi@linux.intel.com>