gpu: nova-core: vbios: Fix clippy error in Vbios::new()
From clippy:

  error: this `if` can be collapsed into the outer `match`
     --> drivers/gpu/nova-core/vbios.rs:328:21
      |
  328 | /                     if pci_at_image.is_none() {
  329 | |                         pci_at_image = Some(PciAtBiosImage::try_from(image)?);
  330 | |                     }
      | |_____________________^
      |

There should be no functional changes in this patch.

Signed-off-by: Lyude Paul <lyude@redhat.com>