media: i2c: it6625: select CONFIG_HDMI
Without HDMI support, the driver fails to link:

arm-linux-gnueabi-ld: drivers/media/i2c/it6625.o: in function `it6625_show_avi_infoframe':
it6625.c:(.text.it6625_show_avi_infoframe+0x94): undefined reference to `hdmi_infoframe_unpack'

Select the option like the other similar drivers do.

Fixes: 142e5f00bd57 ("media: i2c: add driver for ITE IT6625/IT6626")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>