mm: call page_owner swap hooks from generic swap hooks
Finally, call the page_owner swap hooks from the generic swap hooks.
This plugs the new functionality into the kernel.

Add a missing include in 'page_owner.h' to fix build errors in files
that include 'pgtable.h' (thus now 'page_owner.h') without an earlier
include that provides 'pg_data_t':

    In file included from .../include/linux/pgtable.h:19,
                     from .../arch/x86/boot/startup/map_kernel.c:7:
    .../include/linux/page_owner.h:20:41: error: unknown type name ‘pg_data_t’

Signed-off-by: Mauricio Faria de Oliveira <mfo@igalia.com>