LoongArch: Add numa_add_reserved_memblk() support in numa
This patch fixes the error below when compiling kernel with
loongarch's loongson3_defconfig:

drivers/acpi/numa/srat.c: In function ‘acpi_parse_cfmws’:
drivers/acpi/numa/srat.c:467:13: error: implicit declaration of function
‘numa_add_reserved_memblk’ [-Werror=implicit-function-declaration]
  467 |         if (numa_add_reserved_memblk(node, start, end) < 0) {

The error is caused by the missing the newly added
numa_add_reserved_memblk (under include/linux/numa_memblks.h) definition
inside loongarch's numa related code.

The commit's code(style) was formatted by ./scripts/checkpatch.pl

Signed-off-by: Yulong Han <wheatfox17@icloud.com>