kbuild: uapi: Avoid testing certain headers on ARCH=arm with CC=clang
After commit e3970d77ec50 ("kbuild: uapi: drop dependency on
CC_CAN_LINK"), which enables compile testing of UAPI headers in more
circumstances due to dropping the dependency on CONFIG_CC_CAN_LINK,
there are new instances of -Wunaligned-access when building with clang
targeting ARCH=arm in a few headers:

  In file included from <built-in>:1:
  ./usr/include/linux/hyperv.h:361:2: error: field  within 'struct hv_kvp_exchg_msg_value' is less aligned than 'union hv_kvp_exchg_msg_value::(anonymous at ./usr/include/linux/hyperv.h:361:2)' and is usually due to 'struct hv_kvp_exchg_msg_value' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
    361 |         union {
        |         ^
  1 error generated.

  In file included from <built-in>:1:
  In file included from ./usr/include/linux/vboxguest.h:14:
  usr/include/linux/vbox_vmmdev_types.h:239:4: error: field u within 'struct vmmdev_hgcm_function_parameter32' is less aligned than 'union (unnamed union at usr/include/linux/vbox_vmmdev_types.h:223:2)' and is usually due to 'struct vmmdev_hgcm_function_parameter32' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
    239 |         } u;
        |           ^
  usr/include/linux/vbox_vmmdev_types.h:254:6: error: field u within 'struct vmmdev_hgcm_function_parameter64::(unnamed at usr/include/linux/vbox_vmmdev_types.h:249:3)' is less aligned than 'union (unnamed union at usr/include/linux/vbox_vmmdev_types.h:251:4)' and is usually due to 'struct vmmdev_hgcm_function_parameter64::(unnamed at usr/include/linux/vbox_vmmdev_types.h:249:3)' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
    254 |                         } u;
        |                           ^
  2 errors generated.

These warnings are now fatal after commit 3788d69db18d ("kbuild: uapi:
fail header test on compiler warnings"). -Wunaligned-access is only
enabled at W=1 for the rest of the kernel because of numerous instances
of it.

To keep the build working while the root cause of the warnings is
investigated and resolved, disable testing these header files for
ARCH=arm when building with clang. This should be a minimal loss of
coverage; if the issue pointed out by this warning existed in the wild,
it should have been noticed in real testing at this point since some of
these structures have been around for many years. It is likely the case
that since these structures are for specialized applications, they have
never been used on an ARM platform that does not support unaligned
access.

Fixes: e3970d77ec50 ("kbuild: uapi: drop dependency on CC_CAN_LINK")
Link: https://github.com/ClangBuiltLinux/linux/issues/1576
Signed-off-by: Nathan Chancellor <nathan@kernel.org>