net: hisilicon: hns_mdio: remove incorrect ACPI_PTR annotation
Building with W=1 shows a warning about hns_mdio_acpi_match being unused when
CONFIG_ACPI is disabled:

drivers/net/ethernet/hisilicon/hns_mdio.c:631:36: error: unused variable 'hns_mdio_acpi_match' [-Werror,-Wunused-const-variable]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250225163341.4168238-1-arnd@kernel.org
Signed-off-by: Paolo Abeni <pabeni@redhat.com>