mapple_tree: Fix build error (`make W=1`)
clang complains about unused function:

lib/maple_tree.c:179:19: error: unused function 'mt_alloc_bulk' [-Werror,-Wunused-function]

Fix this by removing unused code.

Fixes: a48d52b2d21b ("maple_tree: Convert forking to use the sheaf interface")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>