dt-bindings: clock: qcom: gcc-ipq5424: add spi4 clocks
SPI protocol runs on serial engine 4. Hence we need to
rename the spi0 clocks to spi4 clocks.

However, renaming spi0 to spi4 will result in the following
compilation error's.
drivers/clk/qcom/gcc-ipq5424.c:2865:3: error: ‘GCC_QUPV3_SPI0_CLK’
undeclared here
drivers/clk/qcom/gcc-ipq5424.c:2866:3: error: ‘GCC_QUPV3_SPI0_CLK_SRC’
undeclared here

To add spi4 clocks without compilation error's, do not
rename the spi0 clocks. Instead, duplicate the spi0 clock
macros and rename them to spi4.

After switching to spi4 clocks in the gcc-ipq5424 driver,
remove the spi0 clock macros.

Signed-off-by: Manikanta Mylavarapu <quic_mmanikan@quicinc.com>