coda: Remove set but unused variables
The clang compiler is not happy with set and unused variables:

  fs/coda/upcall.c:115:27: error: variable 'outp' set but not used [-Werror,-Wunused-but-set-variable]
  ...
  fs/coda/upcall.c:577:20: error: variable 'outp' set but not used [-Werror,-Wunused-but-set-variable]

Clean up the unused variables and associated unused code pieces.
To make this happen, introduce a new UPARG_NO_OUTP() helper macro.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>