drm: panel: himax-hx8279: avoid using an uninitialized variable
goa_even_valid is only initialized in one branch but not the other:

drivers/gpu/drm/panel/panel-himax-hx8279.c:838:6: error: variable 'goa_even_valid' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
  838 |         if (num_zero == ARRAY_SIZE(desc->goa_even_timing))
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/panel/panel-himax-hx8279.c:842:23: note: uninitialized use occurs here
  842 |         if (goa_odd_valid != goa_even_valid)
      |                              ^~~~~~~~~~~~~~

Change the initialization to set it to the value of the condition instead.

Fixes: 38d42c261389 ("drm: panel: Add driver for Himax HX8279 DDIC panels")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>