tools: virtio/linux/module.h add MODULE_DESCRIPTION() define.
when we build tools/virtio, meet below error information.

cc -g -O2 -Werror -Wno-maybe-uninitialized -Wall
-I. -I../include/ -I ../../usr/include/
-Wno-pointer-sign -fno-strict-overflow
-fno-strict-aliasing -fno-common -MMD
-U_FORTIFY_SOURCE -include ../../include/linux/kconfig.h
-mfunction-return=thunk -fcf-protection=none
-mindirect-branch-register -pthread
-c -o virtio_ring.o ../../drivers/virtio/virtio_ring.c
../../drivers/virtio/virtio_ring.c:3276:20: error：expected declaration specifiers or ‘...’ before string constant
 3276 | MODULE_DESCRIPTION("Virtio ring implementation");
      |

Fixes: <ab0727f3ddb8>("virtio: add missing MODULE_DESCRIPTION() macros")
also add MODULE_DESCRIPTION() define for virtio test.

Signed-off-by: Yufeng Wang <wangyufeng@kylinos.cn>