arm: perf: Fix ARCH=arm build with GCC in armv8pmu_set_event_filter()
LLVM ignores everything inside the if statement and doesn't generate
errors, but GCC does, resulting in the following:

  drivers/perf/arm_pmuv3.c: In function armv8pmu_set_event_filter:
  include/linux/bits.h:34:29: error: left shift count >= width of type [-Werror=shift-count-overflow]
  34 |         (((~UL(0)) - (UL(1) << (l)) + 1) & \

Fix it by changing the if to #if. This results in an unused function
warning for armv8pmu_event_threshold_control(), so suppress that too.

Fixes: 816c26754447 ("arm64: perf: Add support for event counting threshold")
Signed-off-by: James Clark <james.clark@arm.com>