drm/nouveau/gsp: fix kernel-doc directive after file rename
Fix the kernel-doc directive after the rename
drivers/gpu/drm/nouveau/nvkm/subdev/gsp/{r535,rm/r535/gsp}.c leading to
erros:

ERROR: Cannot find file ../drivers/gpu/drm/nouveau/nvkm/subdev/gsp/r535.c
WARNING: No kernel-doc for file ../drivers/gpu/drm/nouveau/nvkm/subdev/gsp/r535.c

Fixes: c472d828348c ("drm/nouveau/gsp: move subdev/engine impls to subdev/gsp/rm/r535/")
Cc: Ben Skeggs <bskeggs@nvidia.com>
Signed-off-by: Jani Nikula <jani.nikula@intel.com>