perf test: Fix probe testsuite with a new error message
On my system, it's constantly failing because of new error message from
perf probe.  It should update the regex pattern to match the message -
"A function DIE doesn't have decl_line. Maybe broken DWARF?".

  $ sudo head -n 2 /sys/kernel/debug/kprobes/blacklist | cut -f2
  warn_thunk_thunk
  asm_exc_divide_error

  $ sudo perf probe warn_thunk_thunk
  A function DIE doesn't have decl_line. Maybe broken DWARF?
  A function DIE doesn't have decl_line. Maybe broken DWARF?
  Probe point 'warn_thunk_thunk' not found.
    Error: Failed to add events.

  $ sudo perf probe asm_exc_overflow
  Failed to find scope of probe point.
    Error: Failed to add events.

Cc: Masami Hiramatsu <mhiramat@kernel.org>
Cc: Michael Petlan <mpetlan@redhat.com>
Cc: Veronika Molnarova <vmolnaro@redhat.com>
Signed-off-by: Namhyung Kim <namhyung@kernel.org>