clk: meson: S4: select CONFIG_COMMON_CLK_MESON_CLKC_UTILS
Without this, the newly added driver fails to link:

aarch64-linux-ld: drivers/clk/meson/s4-pll.o: in function `meson_s4_pll_probe':
s4-pll.c:(.text+0x13c): undefined reference to `meson_clk_hw_get'

Fixes: e787c9c55edad ("clk: meson: S4: add support for Amlogic S4 SoC PLL clock driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>