EDAC/amd64: avoid -Wformat-security warning
Using a variable as a format string causes a (default-disabled) warning:

drivers/edac/amd64_edac.c: In function 'per_family_init':
drivers/edac/amd64_edac.c:3914:17: error: format not a string literal and no format arguments [-Werror=format-security]
 3914 |                 scnprintf(pvt->ctl_name, sizeof(pvt->ctl_name), tmp_name);
      |                 ^~~~~~~~~

The code here is safe, but in order to enable the warning by default in
the future, change this instance to pass the name indirectly.

Fixes: e9abd990aefd ("EDAC/amd64: Generate ctl_name string at runtime")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>