KVM/x86: increase frame warning limit in emulate when using KASAN or KCSAN
On Thu, Jun 13, 2024, flyingpenghao@gmail.com wrote:
> From: Peng Hao <flyingpeng@tencent.com>
>
>  When building kernel with clang, which will typically
>  have sanitizers enabled, there is a warning about a large stack frame.
>
> arch/x86/kvm/emulate.c:3022:5: error: stack frame size (2520) exceeds limit (2048)
> in 'emulator_task_switch' [-Werror,-Wframe-larger-than]
> int emulator_task_switch(struct x86_emulate_ctxt *ctxt,
>     ^
> 599/2520 (23.77%) spills, 1921/2520 (76.23%) variables
>
> so increase the limit for configurations that have KASAN or KCSAN enabled for not
> breaking the majority of builds.

Overriding -Wframe-larger-than in KVM isn't maintainble or robust, and KVM shouldn't
discard the userspace configuration.

Can you provide the relevant pieces of your .config?  KVM already guards against
KASAN, so maybe it's just KCSAN that's problematic?  If that's the case, then I
believe the below two patches will do the trick.

If KVM_WERROR is enabled because WERROR is enabled, then that's working as intended,
i.e. the problem is in the config, not in KVM.

From: Sean Christopherson <seanjc@google.com>
Date: Thu, 13 Jun 2024 12:03:13 -0700
Subject: [PATCH 1/2] KVM: x86: Disallow KVM_WERROR if KCSAN and/or KMSAN is
 enabled

Extend KVM_WERROR's incompatibility list to include KCSAN and KMSAN, in
addition to the existing KASAN restriction.  Like KASAN, KCSAN and KMSAN
require more memory and can cause problems with FRAME_WARN.

Signed-off-by: Sean Christopherson <seanjc@google.com>