parisc: hide ioread64 declaration on 32-bit
The definition of ioread64 etc is hidden on 32-bit, but the declaration
remained by accident, which led to the generic definition getting left
out:

ERROR: modpost: "ioread64" [drivers/pci/switch/switchtec.ko] undefined!

Hide the declaration and #define under the same #ifdef.

Reported-by: kernel test robot <lkp@intel.com>
Fixes: cf85120355ea ("parisc: Remove 64bit access on 32bit machines")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>