leds: multicolor: Change intensity_value to unsigned int
Using min to compare the intensity_value with led_dev->max_brightness
causes a signedness error:

	drivers/leds/led-class-multicolor.c: In function 'multi_intensity_store':
	././include/linux/compiler_types.h:630:45: error:
	  call to '__compiletime_assert_195' declared with attribute error:
	    min(intensity_value[i], led_cdev->max_brightness) signedness error

Change the type of intensity_value to unsigned int to fix the signedness
error.

intensity_value is used to set mcled_cdev->subled_info[i].intensity,
which is unsigned int, too.

Fixes: 129f82752bce ("leds: multicolor: Limit intensity to max_brightness of LED")
Signed-off-by: Michael Tretter <m.tretter@pengutronix.de>
Link: https://patch.msgid.link/20260206-leds-multicolor-fix-signedness-error-v1-1-48a00ed33c07@pengutronix.de
Signed-off-by: Lee Jones <lee@kernel.org>