PCI: cadence: fix build-time dependencies
The split of the the cadence pcie controller driver into three modules
does not match the Kconfig structure, as the common symbol tries to
call into the more specific ones. If one is built-in but the other is
a loadable module, we get one of these link errors:

arm-linux-gnueabi-ld: drivers/pci/controller/cadence/pcie-cadence-plat.o: in function `cdns_plat_pcie_probe':
pcie-cadence-plat.c:(.text+0x33c): undefined reference to `cdns_pcie_host_setup'
arm-linux-gnueabi-ld: drivers/pci/controller/cadence/pcie-cadence-plat.o: in function `cdns_plat_pcie_probe':
pcie-cadence-plat.c:(.text+0x264): undefined reference to `cdns_pcie_ep_setup'

Move the two parts back into a common module to ensure they can always
link, while keeping the optional parts out of possible.

Fixes: 611627a4e5e4 ("PCI: cadence: Add module support for platform controller driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>