misc: keba: Fix missing AUXILIARY_BUS dependency
The cp500 driver creates auxiliary devices. Kernel configs without
CONFIG_AUXILIARY_BUS lead to warnings like this:

cp500.c: undefined reference to `auxiliary_device_init'
cp500.c: undefined reference to `__auxiliary_device_add'

Add missing dependency to AUXILIARY_BUS to KEBA_CP500 Kconfig.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407081327.2DR4Ltu9-lkp@intel.com/
Fixes: 44ac4116f3b4 ("misc: keba: Add basic KEBA CP500 system FPGA support")
Signed-off-by: Gerhard Engleder <eg@keba.com>
Link: https://lore.kernel.org/r/20240708180049.12713-1-gerhard@engleder-embedded.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>