linux-next: build failure after merge of the vfs-brauner tree
Hi all,

After merging the vfs-brauner tree, today's linux-next build
(arm multi_v7_defconfig) failed like this:

/tmp/next/build/fs/ntfs3/inode.c: In function 'ntfs_read_folio':
/tmp/next/build/fs/ntfs3/inode.c:678:9: error: too few arguments to function 'iomap_read_folio'
  678 |         iomap_read_folio(&ntfs_iomap_ops, &ctx);
      |         ^~~~~~~~~~~~~~~~
In file included from /tmp/next/build/fs/ntfs3/inode.c:15:
/tmp/next/build/include/linux/iomap.h:347:6: note: declared here
  347 | void iomap_read_folio(const struct iomap_ops *ops,
      |      ^~~~~~~~~~~~~~~~
/tmp/next/build/fs/ntfs3/inode.c: In function 'ntfs_readahead':
/tmp/next/build/fs/ntfs3/inode.c:702:9: error: too few arguments to function 'iomap_readahead'
  702 |         iomap_readahead(&ntfs_iomap_ops, &ctx);
      |         ^~~~~~~~~~~~~~~
/tmp/next/build/include/linux/iomap.h:349:6: note: declared here
  349 | void iomap_readahead(const struct iomap_ops *ops,
      |      ^~~~~~~~~~~~~~~

Caused by commit

   8806f279244bf (iomap: stash iomap read ctx in the private field of iomap_iter)

interacting with

   099ef9ab9203d (fs/ntfs3: implement iomap-based file operations)

from the ntfs3 tree.  I have applied the below fixup and will carry:

From f7872b478d46a5bfecf385fe87fd3a5894ac8254 Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Mon, 19 Jan 2026 14:10:04 +0000
Subject: [PATCH] ntfs3: Fix merge issue with ntfs3

/tmp/next/build/fs/ntfs3/inode.c: In function 'ntfs_read_folio':
/tmp/next/build/fs/ntfs3/inode.c:678:9: error: too few arguments to function 'iomap_read_folio'
  678 |         iomap_read_folio(&ntfs_iomap_ops, &ctx);
      |         ^~~~~~~~~~~~~~~~
In file included from /tmp/next/build/fs/ntfs3/inode.c:15:
/tmp/next/build/include/linux/iomap.h:347:6: note: declared here
  347 | void iomap_read_folio(const struct iomap_ops *ops,
      |      ^~~~~~~~~~~~~~~~
/tmp/next/build/fs/ntfs3/inode.c: In function 'ntfs_readahead':
/tmp/next/build/fs/ntfs3/inode.c:702:9: error: too few arguments to function 'iomap_readahead'
  702 |         iomap_readahead(&ntfs_iomap_ops, &ctx);
      |         ^~~~~~~~~~~~~~~
/tmp/next/build/include/linux/iomap.h:349:6: note: declared here
  349 | void iomap_readahead(const struct iomap_ops *ops,
      |      ^~~~~~~~~~~~~~~

Signed-off-by: Mark Brown <broonie@kernel.org>