libperf: Add back guard on MAX_NR_CPUS
Building perf with EXTRA_CFLAGS="-DMAX_NR_CPUS=1" fails:

	  CC      /home/chleroy/linux-powerpc/tools/perf/libperf/cpumap.o
	cpumap.c:16: error: "MAX_NR_CPUS" redefined [-Werror]
	   16 | #define MAX_NR_CPUS 4096
	      |
	<command-line>: note: this is the location of the previous definition

Commit e8399d34d568 ("libperf cpumap: Hide/reduce scope of MAX_NR_CPUS")
moved definition of MAX_NR_CPUS from lib/perf/include/internal/cpumap.h
to lib/perf/cpumap.c but the guard surrounding that definition got lost
in the move.

See commit 21b8732eb447 ("perf tools: Allow overriding MAX_NR_CPUS at
compile time") to see why it is needed.

Note that MAX_NR_CPUS was initialy defined in perf/perf.h and a
redundant definition was added by commit 9c3516d1b850 ("libperf:
Add perf_cpu_map__new()/perf_cpu_map__read() functions").

A cleaner fix would be to remove that duplicate but for the time
being fix the problem by bringing back the guard for when MAX_NR_CPUS
is already defined.

Fixes: e8399d34d568 ("libperf cpumap: Hide/reduce scope of MAX_NR_CPUS")
Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
Reviewed-by: Arnaldo Carvalho de Melo <acme@redhat.com>