ACPI: NUMA: Move get_numa_distances_cnt() helper to needed location
In LoongArch, get_numa_distances_cnt() was not in use, resulting in
a compiler warning.

Serendipitously, drivers/acpi/numa/srat.c appears to be a more
relevant location for this helper function, hence its relocation.

This commit not only resolves these immediate concerns but also sets
the groundwork for potential future integration of ACPI related logic
from other architectures into this driver module.

Separately, the locality_count member in struct acpi_table_slit is
typed as u64. Adapt the function type to eliminate potential code
risks.

Fix follow errors with clang-18 when W=1e:

arch/loongarch/kernel/acpi.c:259:28: error: unused function 'get_numa_distances_cnt' [-Werror,-Wunused-function]
  259 | static inline unsigned int get_numa_distances_cnt(struct acpi_table_slit *slit)
      |                            ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>