linux-next: build failure after merge of the mm tree
Hi all,

After merging the mm tree, today's linux-next build (arm64 defconfig)
failed like this:

/tmp/next/build/mm/hugetlb_cgroup.c: In function 'hugetlb_cgroup_cfttypes_init':
/tmp/next/build/mm/hugetlb_cgroup.c:840:42: error: 'struct cftype' has no member named 'lockdep_key'
  840 |                 lockdep_register_key(&cft->lockdep_key);
      |                                          ^~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:244: mm/hugetlb_cgroup.o] Error 1

Caused by commit

  eb9290991cb59 ("mm/hugetlb_cgroup: register lockdep key for cftype")

From 2de1726235b66fe778f30b53532baaa48b284f8c Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Wed, 19 Jun 2024 12:21:59 +0100
Subject: [PATCH] mm: Fix build failure due to missing build time check

/tmp/next/build/mm/hugetlb_cgroup.c: In function 'hugetlb_cgroup_cfttypes_init':
/tmp/next/build/mm/hugetlb_cgroup.c:840:42: error: 'struct cftype' has no member named 'lockdep_key'
  840 |                 lockdep_register_key(&cft->lockdep_key);
      |                                          ^~

Signed-off-by: Mark Brown <broonie@kernel.org>