i2c: i2c-bcm-iproc: fix -Wvoid-pointer-to-enum-cast warning
When building with W=1 we see the following warning:

|  drivers/i2c/busses/i2c-bcm-iproc.c:1039:3: error: cast to smaller \
|       integer type 'enum bcm_iproc_i2c_type' from 'const void *' [-Werror,-Wvoid-pointer-to-enum-cast]
|   1039 |                 (enum bcm_iproc_i2c_type)of_device_get_match_data(&pdev->dev);
|        |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is due to the fact that the `bcm_iproc_i2c_type` enum members are
int-width and a cast from pointer-width down to int will cause
truncation and possible data loss. Although in this case `bcm_iproc_i2c_type`
has only a few enumerated fields and thus there is likely no data loss
occurring. Nonetheless, this patch is necessary to the goal of promoting
this warning out of W=1.

Link: https://github.com/ClangBuiltLinux/linux/issues/1903
Signed-off-by: Justin Stitt <justinstitt@google.com>