Loongarch: KGDB: fix implicit declaration of flush_icache_range()
Add <asm/cacheflush.h> to prevent a build error:

arch/loongarch/kernel/kgdb.c: In function 'do_single_step':
arch/loongarch/kernel/kgdb.c:440:9: error: implicit declaration of function 'flush_icache_range' [-Werror=implicit-function-declaration]
  440 |         flush_icache_range(addr, addr + BREAK_INSTR_SIZE);

Fixes: 8968eb010689 ("LoongArch: Add basic KGDB & KDB support")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Qing Zhang <zhangqing@loongson.cn>
Cc: Hui Li <lihui@loongson.cn>
Cc: Binbin Zhou <zhoubinbin@loongson.cn>
Cc: Huacai Chen <chenhuacai@kernel.org>
Cc: WANG Xuerui <kernel@xen0n.name>
Cc: loongarch@lists.linux.dev