iommufd: fix selftest link dependency on amdv1 driver
When CONFIG_AMD_IOMMU is disabled, the selftest runs into a link failure:

aarch64-linux-ld: drivers/iommu/iommufd/selftest.o: in function `mock_domain_alloc_pgtable.isra.0':
selftest.c:(.text+0x1590): undefined reference to `pt_iommu_amdv1_init'
aarch64-linux-ld: drivers/iommu/iommufd/selftest.o:(.rodata+0x280): undefined reference to `pt_iommu_amdv1_map_pages'
aarch64-linux-ld: drivers/iommu/iommufd/selftest.o:(.rodata+0x288): undefined reference to `pt_iommu_amdv1_unmap_pages'
aarch64-linux-ld: drivers/iommu/iommufd/selftest.o:(.rodata+0x2b0): undefined reference to `pt_iommu_amdv1_iova_to_phys'
aarch64-linux-ld: drivers/iommu/iommufd/selftest.o:(.rodata+0x2d8): undefined reference to `pt_iommu_amdv1_read_and_clear_dirty'

Change the top-level function to skip all the amdv1 tests in this configuration.

Fixes: e93d5945ed5b ("iommufd: Change the selftest to use iommupt instead of xarray")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>