platform/x86/intel/pmt: fix format string warnings
The %ld format string is for 'long'. size_t is the same length
but requires the use of '%zd' to avoid this portability warning:

drivers/platform/x86/intel/pmt/discovery.c: In function 'pmt_feature_get_feature_table':
drivers/platform/x86/intel/pmt/discovery.c:427:35: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
  427 |         if (WARN(size > res_size, "Bad table size %ld > %pa", size, &res_size))

Similarly, passing a string pointer as a format string means
that gcc is unable and warns when -Wformat-security is enabled:

drivers/platform/x86/intel/pmt/discovery.c: In function 'pmt_features_discovery':
drivers/platform/x86/intel/pmt/discovery.c:505:36: error: format not a string literal and no format arguments [-Werror=format-security]
  505 |                                    pmt_feature_names[feature->id]);
      |                                    ^~~~~~~~~~~~~~~~~

Fix both trivial format string warnings in the obvious way.

Fixes: d9a078809356 ("platform/x86/intel/pmt: Add PMT Discovery driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>