linux-next: build failure after merge of the block tree
Hi all,

After merging the block tree, today's linux-next build
(arm64 allnoconfig) failed like this:

In file included from /tmp/next/build/io_uring/filetable.h:5,
                 from /tmp/next/build/io_uring/openclose.c:17:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/openclose.o] Error 1 make[4]: *** Waiting for unfinished jobs....
In file included from /tmp/next/build/include/linux/io_uring/cmd.h:6,
                 from /tmp/next/build/io_uring/uring_cmd.c:5:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/uring_cmd.o] Error 1 In file included from
/tmp/next/build/include/linux/io_uring/cmd.h:6,
                 from /tmp/next/build/io_uring/opdef.c:10:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/opdef.o] Error 1 In file included
from /tmp/next/build/io_uring/eventfd.c:9:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/eventfd.o] Error 1 In file included from
/tmp/next/build/io_uring/filetable.h:5,
                 from /tmp/next/build/io_uring/splice.c:14:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/splice.o] Error 1 In file included from
/tmp/next/build/include/trace/events/io_uring.h:10,
                 from /tmp/next/build/io_uring/timeout.c:8:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/timeout.o] Error 1 In file included from
/tmp/next/build/io_uring/filetable.h:5,
                 from /tmp/next/build/io_uring/cancel.c:12:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/cancel.o] Error 1 In file included from
/tmp/next/build/include/trace/events/io_uring.h:10,
                 from /tmp/next/build/io_uring/wait.c:10:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~
make[4]: *** [/tmp/next/build/scripts/Makefile.build:290:
io_uring/wait.o] Error 1 In file included from
/tmp/next/build/include/trace/events/io_uring.h:10,
                 from /tmp/next/build/io_uring/poll.c:12:
/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~

Caused by commit

   95961b72c57b2 (io_uring/rsrc: rename and export IO_IMU_DEST / IO_IMU_SOURCE)

from the fuse tree interacting with something in the block tree.  I have
applied the fixup below for today and can carry as needed:

From 227fd8e91f19230683755e9a191e23c7dbfacaab Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Tue, 18 Aug 2026 19:36:17 +0100
Subject: [PATCH] io_uring: Add missing include for ITER_SOURCE and ITER_DEST

Fix IWYU issues:

/tmp/next/build/include/linux/io_uring_types.h:56:32: error: 'ITER_DEST'
undeclared here (not in a function)
   56 |         IO_BUF_DEST     = 1 << ITER_DEST,
      |                                ^~~~~~~~~
/tmp/next/build/include/linux/io_uring_types.h:57:32: error: 'ITER_SOURCE'
undeclared here (not in a function)
   57 |         IO_BUF_SOURCE   = 1 << ITER_SOURCE,
      |                                ^~~~~~~~~~~

Fixes: 95961b72c57b2 ("io_uring/rsrc: rename and export IO_IMU_DEST / IO_IMU_SOURCE")
Signed-off-by: Mark Brown <broonie@kernel.org>