tools/headers: Sync stddef.h with include/uapi to fix BPF
tools/include/uapi/linux/stddef.h is a copy of include/uapi/linux/stddef.h
used by the tools build. But it occurred to be an older snapshot, what
causes the BPF selftests build failures in manual selftests builds:
  In file included from test_tag.c:18:
  /usr/include/linux/if_alg.h:45:22: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘__counted_by’
     45 |         __u8    iv[] __counted_by(ivlen);
        |                      ^~~~~~~~~~~~

Commit dacbfc167808 ("crypto: af_alg - Annotate struct af_alg_iv
with __counted_by") added __counted_by() to a uapi header
(include/uapi/linux/if_alg.h), but tools/include/uapi/linux/stddef.h
was not updated.

Sync tools/include/uapi/linux/stddef.h with include/uapi/linux/stddef.h
to fix selftests/bpf build.

Fixes: dacbfc167808 ("crypto: af_alg - Annotate struct af_alg_iv with __counted_by")
Signed-off-by: Mikhail Zaslonko <zaslonko@linux.ibm.com>