i2c: PCF8584: Fixed space(s) required after different operators
Error: spaces required around or before or after  '=', ';', '<'
and ',' operators. Revealed by checkpatch.pl.
Added space(s) around or before or after different operators.

Signed-off-by: Cezar Chiru <chiru.cezar.89@gmail.com>