staging: gpib: Resolve prefixing 0x with decimal
- pr_info() of hp_82341_attach() in hp_82341 uses 0x%u which is defective.
- The iobase is of u32 and correct prefix is 0x%x.
- This error reported by checkpatch with below message:
  ERROR: Prefixing 0x with decimal output is defective.

Signed-off-by: Ajith P V <ajithpv.linux@gmail.com>