perf: Fix up build failure due to bpf changes
Fix

util/btf.c: In function '__btf_type__find_member_by_name':
util/btf.c:19:43: error: comparison of integer expressions of different signedness: 'int' and '__u32' {aka 'unsigned int'} [-Werror=sign-compare]
   19 |         for (i = 0, m = btf_members(t); i < btf_vlen(t); i++, m++) {
      |                                           ^
cc1: all warnings being treated as errors

by making the variable the same type as the function.

Signed-off-by: Mark Brown <broonie@kernel.org>