alpha: fix marvel_ioread8 build regression
The previous build fix contained a small typo that led to
another regression:

arch/alpha/kernel/core_marvel.c:807:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'marvel_ioread8'

Reported-by: kernel test robot <lkp@intel.com>
Fixes: 979f733ba305 ("alpha: add full ioread64/iowrite64 implementation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>