PCI: Constify dummy pci_register_io_range() fwnode_handle
If CONFIG_PCI=n:

    drivers/of/address.c: In function ‘of_pci_range_to_resource’:
    drivers/of/address.c:247:45: error: passing argument 1 of ‘pci_register_io_range’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
      247 |                 err = pci_register_io_range(&np->fwnode, range->cpu_addr,
	  |                                             ^~~~~~~~~~~
    In file included from drivers/of/address.c:12:
    include/linux/pci.h:2022:63: note: expected ‘struct fwnode_handle *’ but argument is of type ‘const struct fwnode_handle *’
     2022 | static inline int pci_register_io_range(struct fwnode_handle *fwnode,
	  |                                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~

Fixes: 6ad99a07e6d2ed91 ("PCI: Constify pci_register_io_range() fwnode_handle")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>