crypto: qcom: add HW_RANDOM dependency
The driver now calls into the hwrng subsystem and causes a link failure if that
is not reachable:

x86_64-linux-ld: vmlinux.o: in function `qcom_rng_probe':
qcom-rng.c:(.text+0xfefc7e): undefined reference to `devm_hwrng_register'

Add a Kconfig dependency as we have for the pure hw_random drivers. I see
that there are some other crypto drivers that instead use 'select HW_RANDOM',
but those seem to be mistakes as that may lead to circular dependencies,
and a simple driver should not force-enable an entire subsytem.

Fixes: f29cd5bb64c25 ("crypto: qcom-rng - Add hw_random interface support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>