Documentation: nouveau: Update GSP message queue kernel-doc reference
Commit c472d828348caf ("drm/nouveau/gsp: move subdev/engine impls to
subdev/gsp/rm/r535/") moves GSP-RM message queue implementation in
drivers/gpu/drm/nouveau/nvkm/subdev/gsp/r535.c to versioned path in
drivers/gpu/drm/nouveau/nvkm/subdev/gsp/rm/r535/gsp.c, but forgets to
update kernel-doc reference in nouveau docs, hence triggers htmldocs
warnings:

ERROR: Cannot find file ./drivers/gpu/drm/nouveau/nvkm/subdev/gsp/r535.c
WARNING: No kernel-doc for file ./drivers/gpu/drm/nouveau/nvkm/subdev/gsp/r535.c

Update the reference.

Fixes: c472d828348c ("drm/nouveau/gsp: move subdev/engine impls to subdev/gsp/rm/r535/")
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>