Revert "crypto: crc32 - remove "_generic" from filenames"
Each loadable module in the kernel must have a unique name, so renaming
the crc32 crypto module made it conflict with the crc32 library, as
shown by the build failure:

 error: the following would cause module name conflict:
   crypto/crc32.ko
   lib/crc32.ko

This could be solved by renaming one of the two conflicting modules
to something else again. As I can't think of a better name, just
revert back to the previous state as the easiest fix.

Fixes: ce653e0a7e0a ("crypto: crc32 - remove "_generic" from filenames")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>