drm/panthor: fix building without CONFIG_DEBUG_FS
When debugfs is disabled, including panthor_gem.h causes warnings
about a non-static global function defined in a header:

In file included from drivers/gpu/drm/panthor/panthor_drv.c:30:
drivers/gpu/drm/panthor/panthor_gem.h:222:6: error: no previous prototype for 'panthor_gem_debugfs_set_usage_flags' [-Werror=missing-prototypes]
  222 | void panthor_gem_debugfs_set_usage_flags(struct panthor_gem_object *bo, u32 usage_flags) {};

This could be changed to a static inline function, but as the normal
one is also static inline, just move the #ifdef check in there.
The #ifdef is still needed to avoid accessing a struct member that
does not exist without debugfs.

Fixes: a3707f53eb3f ("drm/panthor: show device-wide list of DRM GEM objects over DebugFS")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>