selftests/pidfd: fix building with clang-20
When using 'make LLVM=1 W=1 -C tools/testing/selftests/pidfd' with
clang-20, I've noticed the following:

pidfd_fdinfo_test.c:230:6: error: call to undeclared function 'mount';
ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
  230 |         r = mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, 0);
      |             ^
pidfd_fdinfo_test.c:230:29: error: use of undeclared identifier 'MS_REC'
  230 |         r = mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, 0);
      |                                    ^

and:

pidfd_setns_test.c:172:40: error: call to undeclared function 'ioctl';
ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
  172 |                 self->child_pidfd_derived_nsfds[i] = \
                               ioctl(self->pidfd, info->pidfd_ioctl, 0);
      |                        ^

So include '<sys/mount.h>' and 'sys/ioctl.h', respectively,
to add all of the required declarations.

Signed-off-by: Dmitry Antipov <dmantipov@yandex.ru>