hrtimers: Replace hrtimer_clock_to_base_table approach with switch-case
Clang (and GCC as well) complains about overlapped initialisers
in the hrtimer_clock_to_base_table definition. With `make W=1`
and CONFIG_WERROR=y (which is default nowadays) this breaks
the build:

  CC      kernel/time/hrtimer.o
kernel/time/hrtimer.c:124:21: error: initializer overrides prior initialization of this subobject [-Werror,-Winitializer-overrides]
  124 |         [CLOCK_REALTIME]        = HRTIMER_BASE_REALTIME,

kernel/time/hrtimer.c:122:27: note: previous initialization is here
  122 |         [0 ... MAX_CLOCKS - 1]  = HRTIMER_MAX_CLOCK_BASES,

(and similar for CLOCK_MONOTONIC, CLOCK_BOOTTIME, and CLOCK_TAI).

Replace hrtimer_clock_to_base_table approach with switch-case to make
the compiler happy.

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>