drm/v3d: Fix compile with CONFIG_WERROR
Fix compile with CONFIG_WERROR by explicitly computing the max number of
7.1 and 4.2 counters.

In file included from ../drivers/gpu/drm/v3d/v3d_drv.h:14,
                 from ../drivers/gpu/drm/v3d/v3d_bo.c:26:
../drivers/gpu/drm/v3d/v3d_performance_counters.h:118:43: \
	error: ‘v3d_v42_performance_counters’ defined but not used \
	[-Werror=unused-const-variable=]

Fixes: 3cbcbe016c31 ("drm/v3d: Add Performance Counters descriptions for V3D 4.2 and 7.1")
Signed-off-by: Ashutosh Dixit <ashutosh.dixit@intel.com>