selftests: coredump: Fix compilation issue
Building coredump selftests fails on x86 due to following issues:

1./usr/include/x86_64-linux-gnu/sys/mount.h:35:3: error: expected identifier before numeric constant
   35 |   MS_RDONLY = 1,                /* Mount read-only.  */
      |

<linux/fs.h> pulls in kernel-internal headers that conflict with
   glibc's <sys/mount.h>, causing this error.

2.stackdump_test.c:25:1: note: ‘offsetof’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?

Missing <stddef.h> causes unresolved use of offsetof().

Fix this by:
  - dropping <linux/fs.h> and including <sys/mount.h>
  - including <stddef.h> for offsetof()

Signed-off-by: Sahil Chandna <chandna.sahil@gmail.com>