soc: qcom_stats: add AOSS_QMP dependency
Using the QMP functions fails in a built-in driver when QMP is a loadable
module:

aarch64-linux-ld: drivers/soc/qcom/qcom_stats.o: in function `qcom_ddr_stats_show':
qcom_stats.c:(.text+0x6f4): undefined reference to `qmp_send'
aarch64-linux-ld: drivers/soc/qcom/qcom_stats.o: in function `qcom_stats_probe':
qcom_stats.c:(.text+0x117c): undefined reference to `qmp_get'

Fixes: e84e61bdb97c ("soc: qcom: stats: Add DDR sleep stats")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>