net/mlx5: don't build with CONFIG_CPUMASK_OFFSTACK
Local cpumask_t variables must be wrapped with alloc_cpumask_var() or
similar helpers, to allow building with ridiculous values of CONFIG_NR_CPUS:

drivers/net/ethernet/mellanox/mlx5/core/eq.c: In function ‘comp_irq_request_sf’:
drivers/net/ethernet/mellanox/mlx5/core/eq.c:897:1: error: the frame size of 8560 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c: In function ‘mlx5_ctrl_irq_request’:
drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:494:1: error: the frame size of 8544 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c: In function ‘mlx5_irq_request_vector’:
drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:561:1: error: the frame size of 8560 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
drivers/net/ethernet/mellanox/mlx5/core/irq_affinity.c: In function ‘irq_pool_request_irq’:
drivers/net/ethernet/mellanox/mlx5/core/irq_affinity.c:74:1: error: the frame size of 8544 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]

The mlx5 driver used to do this correctly in the past, but was changed
to use local 'irq_affinity_desc' structures in at least four places,
which ends up having the mask on the stack again.

It is not easily possible to use alloc_cpumask_var() again without
reverting that patch, so work around this by disallowing this drivers
on kernels that rely on CONFIG_CPUMASK_OFFSTACK.

Fixes: bbac70c74183 ("net/mlx5: Use newer affinity descriptor")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>