mm, slab: fold need_slab_obj_ext() into its only user
need_slab_obj_ext() is used only in one place, fold it into there.
Without that, clang can't build kernel with `make W=1` when
CONFIG_WERROR=y, which is default in the x86 configurations.

mm/slub.c:2079:20: error: unused function 'need_slab_obj_ext' [-Werror,-Wunused-function]

To solve this, fold need_slab_obj_ext() into its only user.

Fixes: e33b7ae3d802 ("mm, slab: clean up slab->obj_exts always")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>