perf stat: fix JSON output with non-C locales
When running `perf stat -j` under a locale that uses ',' as radix point
separator (e.g. LC_NUMERIC=fr_FR.UTF-8), the JSON output becomes
invalid. This is reproducible with perf test "perf stat JSON output
linter", which fails which such locales.

Example failure:

  $ LC_NUMERIC=fr_FR.UTF-8 perf test "JSON output" -v

  Checking json output: no args Test failed for input:

  {"counter-value" : "1,202545", "unit" : "msec", "event" :
   "task-clock", "event-runtime" : 1202545, "pcnt-running" : 100,00,
   "metric-value" : "0,473483", "metric-unit" : "CPUs utilized"}

  json.decoder.JSONDecodeError: Expecting property name enclosed in
  double quotes: line 2 column 121 (char 122)

Fix this by always using the POSIX numeric locale in json_out(),
ensuring that '.' is consistently used as the radix point in all JSON
numbers.

Signed-off-by: Pablo de Oliveira Castro <pablo@sifflez.org>