iommu/arm-smmu-v3-iommufd: Separate vDEVICE allocation list
Stephen Rothwell reports htmldocs warnings when merging iommufd tree:

Documentation/userspace-api/iommufd:335: include/uapi/linux/iommufd.h:456: ERROR: Unexpected indentation. [docutils]
Documentation/userspace-api/iommufd:335: include/uapi/linux/iommufd.h:457: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]

Fix them by separating vDEVICE allocation list from preceding paragraph.

Fixes: 9f0b286fe40130 ("iommu/arm-smmu-v3-iommufd: Allow attaching nested domain for GBPA cases")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Closes: https://lore.kernel.org/linux-next/20251126125920.207fc959@canb.auug.org.au/
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>