Bluetooth: btintel_pcie: avoid unguarded 64-bit division
Directly dividing a 64-bit value is not allowed on 32-bit
architectures in the kernel.

arm-linux-gnueabi/bin/arm-linux-gnueabi-ld: drivers/bluetooth/btintel_pcie.o: in function `btintel_pcie_suspend_late':
btintel_pcie.c:(.text+0x224): undefined reference to `__aeabi_ldivmod'

Since this is a ktime_t value and dividing by 1000 gives a microsecond
number, just convert it into microseconds using the appropriate helper.

Fixes: 33bb9b1ce6f6 ("Bluetooth: btintel_pcie: Add support for _suspend() / _resume()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>