kho: fix kho_test_restore section mismatch warning
kho_test_restore_data() is not always inlined, and that configuration
causes a link warning:

WARNING: modpost: vmlinux: section mismatch in reference: kho_test_restore+0xd2 (section: .text.unlikely) -> kho_test_restore_data.isra.0 (section: .init.text)
ERROR: modpost: Section mismatches detected.

Mark it __init as well to be consistent with the rest of the call chain.

Fixes: c2d288f7ab13 ("kho: add test for kexec handover")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>