PCI: Constify pci_register_io_range stub fwnode_handle
The patch to change the argument types for pci_register_io_range()
only caught one of the two implementations, but missed the empty
version:

drivers/of/address.c: In function 'of_pci_range_to_resource':
drivers/of/address.c:244:45: error: passing argument 1 of 'pci_register_io_range' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  244 |                 err = pci_register_io_range(&np->fwnode, range->cpu_addr,
      |                                             ^~~~~~~~~~~
In file included from drivers/of/address.c:12:
include/linux/pci.h:1559:49: note: expected 'struct fwnode_handle *' but argument is of type 'const struct fwnode_handle *'
 1559 | int pci_register_io_range(struct fwnode_handle *fwnode, phys_addr_t addr,
      |                           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~

Change this the same way.

Fixes: 6ad99a07e6d2 ("PCI: Constify pci_register_io_range() fwnode_handle")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>