Revert "ARM: mach-virt: Select PMUv3 driver by default"
This reverts commit d866d1d1e90550cb6ccc767e00c27bc769f467b9.

Selecting a Kconfig option that has its own set of dependencies tends to
end badly, and in this case 'randconfig' builds blew up on 32-bit ARM
where ARM_PMUV3 was being selecting with HW_PERF_EVENTS=n:

  |    drivers/perf/arm_pmuv3.c:68:5: error: use of undeclared identifier 'DTLB'
  |            [C(DTLB)][C(OP_READ)][C(RESULT_ACCESS)] = ARMV8_PMUV3_PERFCTR_L1D_TLB,
  |               ^
  |    fatal error: too many errors emitted, stopping now [-ferror-limit=]
  |    20 errors generated.
  |
  | Kconfig warnings: (for reference only)
  |    WARNING: unmet direct dependencies detected for ARM_PMUV3
  |    Depends on [n]: PERF_EVENTS [=y] && HW_PERF_EVENTS [=n] && (ARM [=y] && CPU_V7 [=y] || ARM64)
  |    Selected by [y]:
  |    - ARCH_VIRT [=y] && ARCH_MULTI_V7 [=y] && PERF_EVENTS [=y]

As suggested by Marc, just drop the 'select' clause altogether by
reverting the patch which introduced it.

Link: https://lore.kernel.org/r/202303281539.zzI4vpw1-lkp@intel.com
Reported-by: kernel test robot <lkp@intel.com>
Reported-by: Arnd Bergmann <arnd@arndb.de>
Suggested-by: Marc Zyngier <maz@kernel.org>
Signed-off-by: Will Deacon <will@kernel.org>