drm/fbdev-emulation: restore drm_fb_helper_gem_is_fb() dummy
linux-next contains an incorrect merge of the drm tree and the amdgpu tree,
which have conflicting patches from Thomas Zimmermann:

drivers/gpu/drm/amd/amdgpu/amdgpu_display.c: In function 'amdgpu_display_suspend_helper':
drivers/gpu/drm/amd/amdgpu/amdgpu_display.c:1777:22: error: implicit declaration of function 'drm_fb_helper_gem_is_fb'; did you mean 'drm_fb_helper_from_client'? [-Wimplicit-function-declaration]
 1777 |                 if (!drm_fb_helper_gem_is_fb(dev->fb_helper, fb->obj[0])) {

drivers/gpu/drm/radeon/radeon_device.c: In function 'radeon_suspend_kms':
drivers/gpu/drm/radeon/radeon_device.c:1592:22: error: implicit declaration of function 'drm_fb_helper_gem_is_fb'; did you mean 'drm_fb_helper_from_client'? [-Wimplicit-function-declaration]
 1592 |                 if (!drm_fb_helper_gem_is_fb(dev->fb_helper, fb->obj[0])) {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
      |                      drm_fb_helper_from_client

The newly added drm_fb_helper_from_client() stub is in fact needed, while all
the other stubs are correctly removed.

Fixes: 6d438685340d ("drm/fbdev-emulation: Remove empty placeholders")
Fixes: 1837c76b780a ("drm/amdgpu: Move test for fbdev GEM object into generic helper")
Fixes: 9c63d743d5cc ("Merge branch 'drm-next' of https://gitlab.freedesktop.org/agd5f/linux.git")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>