drm/bridge: Separate of_drm_find_bridge() preconditions list
Sphinx reports htmldocs warnings:

Documentation/gpu/drm-kms-helpers:197: drivers/gpu/drm/drm_bridge.c:1521: ERROR: Unexpected indentation. [docutils]
Documentation/gpu/drm-kms-helpers:197: drivers/gpu/drm/drm_bridge.c:1523: WARNING: Block quote ends without a blank line; unexpected unindent. [docutils]

Fix them by separating preconditions list in of_drm_find_bridge()
kernel-doc comment from previous paragraph.

Fixes: 9da0e06abda87b ("drm/bridge: deprecate of_drm_find_bridge()")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Closes: https://lore.kernel.org/linux-next/20260105155735.3b4012b6@canb.auug.org.au/
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>