libbpf: increase probe_name buffer size to avoid format-truncation
This patch increases the size of the `probe_name` buffer in
`probe_kern_syscall_wrapper()` from `MAX_EVENT_NAME_LEN` to
`MAX_EVENT_NAME_LEN * 2`.

The change addresses a build failure in perf builds caused by GCC's
-Werror=format-truncation warning:

  libbpf.c:11052:45: error: '%s' directive output may be truncated writing up to 63 bytes into a region of size between 34 and 53 [-Werror=format-truncation]

The warning is triggered by a `snprintf()` call that formats a string
using syscall names and other identifiers. In some cases, the buffer
size is insufficient, leading to potential truncation.

Debug builds pass because they do not treat warnings as errors, but
perf builds fail due to `-Werror`.

Increasing the buffer size ensures that the formatted string fits
safely, resolving the issue without affecting functionality.

Signed-off-by: Sanjay Chitroda <quic_ckantibh@quicinc.com>