checkpatch: don't warn about complex macros in i.MX pin header
The pin function ID in i.MX pin headers is a tuple of <mux_reg conf_reg
input_reg mux_mode input_val>, as below:
"#define IMX95_PAD_DAP_TDI__JTAG_MUX_TDI  0x0000 0x0204 0x0610 0x00 0x00"
The pin headers are used by device trees, not drivers.

checkpatch erroneously flags it as error:
  ERROR: Macros with complex values should be enclosed in parentheses

Bypass the check for pin header files with file names imx[*]-pinfunc.h.

Signed-off-by: Peng Fan <peng.fan@nxp.com>