Bluetooth: btintel_pcie: fix CONFIG_PM_SLEEP check
Using both pm_sleep_ptr() and an #ifdef around the definition is not
valid:

In file included from include/linux/kernel.h:36,
                 from drivers/bluetooth/btintel_pcie.c:9:
drivers/bluetooth/btintel_pcie.c:2674:36: error: 'btintel_pcie_pm_ops' undeclared here (not in a function); did you mean 'btintel_pcie_in_op'?
 2674 |         .driver.pm = pm_sleep_ptr(&btintel_pcie_pm_ops),
      |                                    ^~~~~~~~~~~~~~~~~~~

Remove the #ifdef check to let the compiler's dead-code-elimination drop
this as intended by pm_sleep_ptr().

Fixes: d1b3de23042b ("Bluetooth: btintel_pcie: Add support for _suspend() / _resume()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>