trigger: ledtrig-tty: move variable definition to the top
Has complained about the following construct:
drivers/leds/trigger/ledtrig-tty.c:362:3: error: a label can only be
part of a statement and a declaration is not a statement

Hence move the variable definition to the beginning of the function.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202309270440.IJB24Xap-lkp@intel.com/
Signed-off-by: Florian Eckert <fe@dev.tdt.de>