usb: typec: nb7vpq904m: add CONFIG_OF dependency
DRM_AUX_BRIDGE depends on CONFIG_OF, so the same dependency is needed
here to avoid a build failure:

WARNING: unmet direct dependencies detected for DRM_AUX_BRIDGE
  Depends on [n]: HAS_IOMEM [=y] && DRM_BRIDGE [=y] && OF [=n]
  Selected by [y]:
  - TYPEC_MUX_NB7VPQ904M [=y] && USB_SUPPORT [=y] && TYPEC [=y] && I2C [=y] && (DRM [=y] || DRM [=y]=n) && DRM_BRIDGE [=y]
x86_64-linux-ld: drivers/gpu/drm/bridge/aux-bridge.o: in function `drm_aux_bridge_register':
aux-bridge.c:(.text+0x13b): undefined reference to `auxiliary_device_init'
x86_64-linux-ld: aux-bridge.c:(.text+0x14d): undefined reference to `__auxiliary_device_add'
x86_64-linux-ld: drivers/gpu/drm/bridge/aux-bridge.o: in function `drm_aux_bridge_drv_init':
aux-bridge.c:(.init.text+0x15): undefined reference to `__auxiliary_driver_register'
x86_64-linux-ld: drivers/gpu/drm/bridge/aux-bridge.o: in function `drm_aux_bridge_drv_exit':
aux-bridge.c:(.exit.text+0x9): undefined reference to `auxiliary_driver_unregister'

Fixes: c5d296bad640 ("usb: typec: nb7vpq904m: switch to DRM_AUX_BRIDGE")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>