platform/x86/intel/pmt: fix format string in unit test
Another warning about incorrect format strings shows up in the unit test

In file included from include/kunit/assert.h:13,
                 from include/kunit/test.h:12,
                 from drivers/platform/x86/intel/pmt/discovery-kunit.c:9:
drivers/platform/x86/intel/pmt/discovery-kunit.c: In function 'validate_pmt_regions':
include/linux/kern_levels.h:5:25: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]

Fixes: b9707d46a959 ("platform/x86/intel/pmt: KUNIT test for PMT Enhanced Discovery API")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>