squashfs: Fix percpu address space issues in decompressor_multi_percpu.c
When strict percpu address space checks are enabled, then current
direct casts between the percpu address space and the generic address
space fail the compilation on x86_64 with:

decompressor_multi_percpu.c: In function ‘squashfs_decompressor_create’:
decompressor_multi_percpu.c:49:16: error: cast to generic address space pointer from disjoint ‘__seg_gs’ address space pointer

decompressor_multi_percpu.c: In function ‘squashfs_decompressor_destroy’:
decompressor_multi_percpu.c:64:25: error: cast to ‘__seg_gs’ address space pointer from disjoint generic address space pointer

decompressor_multi_percpu.c: In function ‘squashfs_decompress’:
decompressor_multi_percpu.c:82:25: error: cast to ‘__seg_gs’ address space pointer from disjoint generic address space pointer

Add intermediate casts to unsigned long, as advised in [1] and [2].

Side note: sparse still requires __force when casting from the percpu
address space, although the documentation [2] allows casts to
unsigned long without __force attribute.

Found by GCC's named address space checks.

There were no changes in the resulting object file.

[1] https://gcc.gnu.org/onlinedocs/gcc/Named-Address-Spaces.html#x86-Named-Address-Spaces
[2] https://sparse.docs.kernel.org/en/latest/annotations.html#address-space-name

Signed-off-by: Uros Bizjak <ubizjak@gmail.com>
Cc: Phillip Lougher <phillip@squashfs.org.uk>
Cc: Andrew Morton <akpm@linux-foundation.org>