selftests/pid_namespace: fix building with clang-20
When using 'make LLVM=1 W=1 -C tools/testing/selftests/pid_namespace'
with clang-20, I've noticed the following:

pid_max.c:42:8: error: call to undeclared function 'mount'; ISO
C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
   42 |         ret = mount("", "/", NULL, MS_PRIVATE | MS_REC, 0);
      |               ^
pid_max.c:42:29: error: use of undeclared identifier 'MS_PRIVATE'
   42 |         ret = mount("", "/", NULL, MS_PRIVATE | MS_REC, 0);
      |                                    ^
...

So include '<sys/mount.h>' to add all of the required declarations.

Signed-off-by: Dmitry Antipov <dmantipov@yandex.ru>