rust: alloc: add missing trait item MIN_ALIGN to Cmalloc
Cmalloc is missing the trait item MIN_ALIGN introduced by commit
1b1a946dc2b5 ("rust: alloc: specify the minimum alignment of each
allocator"), causing the following error on the `rusttest` make target.

	error[E0046]: not all trait items implemented, missing: `MIN_ALIGN`
	   --> rust/kernel/alloc/allocator_test.rs:37:1
	    |
	37  | unsafe impl Allocator for Cmalloc {
	    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `MIN_ALIGN` in implementation
	    |
	   ::: rust/kernel/alloc.rs:146:5
	    |
	146 |     const MIN_ALIGN: usize;
	    |     ---------------------- `MIN_ALIGN` from trait

Implement MIN_ALIGN for Cmalloc to fix this.

Reported-by: Miguel Ojeda <miguel.ojeda.sandonis@gmail.com>
Closes: https://lore.kernel.org/all/CANiq72k0FSBTB2yOjiAy9PnAuyM=-PHxL3uQQ_Cv+zwswnr_bA@mail.gmail.com/
Fixes: 1b1a946dc2b5 ("rust: alloc: specify the minimum alignment of each allocator")
Signed-off-by: Danilo Krummrich <dakr@kernel.org>