lib/crypto: arm/poly1305: fix poly1305_blocks_neon link failure
The reference to poly1305_blocks_neon from generated assembler code is
apparently the reason we had the silly __weak function in the wrapper.
Removing it introduced a link failure:

ERROR: modpost: "poly1305_blocks_neon" [lib/crypto/arm/poly1305-arm.ko] undefined!

Moving the reference inside of the #if ARMv7 block avoids this problem.

Fixes: 16f9e0cc99ec ("lib/crypto: arm/poly1305: Remove unneeded empty weak function")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>