mtd: dc21285: fix bytewise memcpy()
The commit that split up the 8/16/32-bit operations in 2004 seems to have
broken the 8-bit case, as clang-21 now points out:

drivers/mtd/maps/dc21285.c:129:97: error: parameter 'len' set but not used [-Werror,-Wunused-but-set-parameter]
  129 | static void dc21285_copy_to_8(struct map_info *map, unsigned long to, const void *from, ssize_t len)

Put back the loop that was in linux-2.6.8 and earlier for this case.

Fixes: 67d4878e4e61 ("NOR flash drivers update")
Cc: David Woodhouse <dwmw2@infradead.org>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>