dyndbg: pr_fmt(fmt) with additional arguments?
Hello Jason, hello Jim,

I've been using the following in my modules to prefix all messages with
the module and function name:
	#define pr_fmt(fmt) KBUILD_MODNAME ".%s ", __func__

This worked nicely until `pr_debug_ratelimit()` is used: The additional
arguments breaks `DEFINE_DYNAMIC_DEBUG_METADATA_CLS`:

	#define pr_debug_ratelimited(fmt, ...)					\
		DEFINE_DYNAMIC_DEBUG_METADATA(…, pr_fmt(fmt));		\

	#define DEFINE_DYNAMIC_DEBUG_METADATA(name, fmt)		\
		DEFINE_DYNAMIC_DEBUG_METADATA_CLS(name, …, fmt)

	#define DEFINE_DYNAMIC_DEBUG_METADATA_CLS(name, cls, fmt)	\
		static struct _ddebug  __aligned(8)			\
		__section("__dyndbg") name = {				\
			… \
			.format = (fmt),				\

This could be fixed easily by adding an additional '...' to it to slurp
any additional argument which `pr_fmt` might add.

Would this be okay or do I miss something?

For testing I have recompiled current 7.0.0-rc1 for x86_64 with no
compile failures.

Philipp Hahn

From 545173a75e3928ec000b1127bfc99439b7fa2f8b Mon Sep 17 00:00:00 2001
Message-ID: <545173a75e3928ec000b1127bfc99439b7fa2f8b.1772186702.git.p.hahn@avm.de>
From: Philipp Hahn <phahn-oss@avm.de>
Date: Fri, 27 Feb 2026 10:53:04 +0100
Subject: [PATCH] dyndbg: Ignore additional arguments from pr_fmt
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
Organization: FRITZ! Technology GmbH, Berlin, Germany

pr_fmt can be used to add a common prefix to any output from a module:
	#define pr_fmt(fmt) KBUILD_MODNAME ".%s ", __func__

But adding additional arguments breaks dynamic debug:
> error: macro "DEFINE_DYNAMIC_DEBUG_METADATA_CLS" passed 4 arguments, but takes just 3
> |         pr_debug_ratelimited("%s", "Hello world!");
> |                                                  ^
> note: macro "DEFINE_DYNAMIC_DEBUG_METADATA_CLS" defined here
> | #define DEFINE_DYNAMIC_DEBUG_METADATA_CLS(name, cls, fmt)       \
> |
> error: ‘DEFINE_DYNAMIC_DEBUG_METADATA_CLS’ undeclared (first use in this function)
> |         DEFINE_DYNAMIC_DEBUG_METADATA_CLS(name, _DPRINTK_CLASS_DFLT, fmt)
> |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> note: in expansion of macro ‘DEFINE_DYNAMIC_DEBUG_METADATA’
> |         DEFINE_DYNAMIC_DEBUG_METADATA(descriptor, pr_fmt(fmt));         \
> |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> note: in expansion of macro ‘pr_debug_ratelimited’
> |         pr_debug_ratelimited("%s", "Hello world!");
> |         ^~~~~~~~~~~~~~~~~~~~

Add an additional ', ...' to DEFINE_DYNAMIC_DEBUG_METADATA_CLS to slurp
any additional argument, which `pr_fmt` might add.

Signed-off-by: Philipp Hahn <phahn-oss@avm.de>