drm/msm/dp: include linux/io.h
The driver started using readl/writel, which are defined in linux/io.h,
so this needs to be included here:

drivers/gpu/drm/msm/dp/dp_panel.c:33:9: error: call to undeclared function 'readl_relaxed'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   33 |         return readl_relaxed(panel->link_base + offset);

Fixes: 9d47325ee063 ("drm/msm/dp: drop the msm_dp_catalog module")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>