gcc-plugins: Fix build with GCC 16.1
GCC is written in C++ for 13 years already, and from the time it
was implemented in C and times when it could be built by both C and C++
there were various CONST_CAST* macros.  In GCC 16 these macros were
removed because one can use C++ const_cast directly.

The kernel gcc-plugins use 2 of those macros though, so when GCC plugins
are enabled, kernel fails to build with
In file included from scripts/gcc-plugins/latent_entropy_plugin.c:78:
scripts/gcc-plugins/gcc-common.h: In function ‘void debug_tree(const_tree)’:
scripts/gcc-plugins/gcc-common.h:417:20: error: ‘CONST_CAST_TREE’ was not declared in this scope; did you mean ‘CONST_CAST_EXPR’?
  417 |         debug_tree(CONST_CAST_TREE(t));
      |                    ^~~~~~~~~~~~~~~
      |                    CONST_CAST_EXPR
scripts/gcc-plugins/gcc-common.h: In function ‘void debug_gimple_stmt(const_gimple_ptr)’:
scripts/gcc-plugins/gcc-common.h:312:47: error: expected primary-expression before ‘,’ token
  312 | #define CONST_CAST_GIMPLE(X) CONST_CAST(gimple, (X))
      |                                               ^
scripts/gcc-plugins/gcc-common.h:422:27: note: in expansion of macro ‘CONST_CAST_GIMPLE’
  422 |         debug_gimple_stmt(CONST_CAST_GIMPLE(s));
      |                           ^~~~~~~~~~~~~~~~~
scripts/gcc-plugins/gcc-common.h:312:30: error: ‘CONST_CAST’ was not declared in this scope; did you mean ‘CONST_INT’?
  312 | #define CONST_CAST_GIMPLE(X) CONST_CAST(gimple, (X))
      |                              ^~~~~~~~~~
scripts/gcc-plugins/gcc-common.h:422:27: note: in expansion of macro ‘CONST_CAST_GIMPLE’
  422 |         debug_gimple_stmt(CONST_CAST_GIMPLE(s));
      |                           ^~~~~~~~~~~~~~~~~

The following patch fixes it by defining the macros the way
they were defined in GCC 15 and earlier for the plugin compatibility
layer.

Tested with both GCC 15.2.1 (where it works before/after this patch) and
GCC 16.1.1 (where it is fixed with it).

Signed-off-by: Jakub Jelinek <jakub@redhat.com>