linux-next: build failure after merge of the drm-misc tree
Hi all,

After merging the drm-misc tree, today's linux-next build (x86_64
allmodconfig) failed like this:

/tmp/next/build/drivers/gpu/drm/tests/drm_hdmi_state_helper_test.c: In function 'drm_test_check_reject_hdr_infoframe_bpc_10':
/tmp/next/build/drivers/gpu/drm/tests/drm_hdmi_state_helper_test.c:2926:49: error: passing argument 6 of 'drm_property_replace_blob_from_id' makes integer from pointer without a cast [-Wint-conversion]
 2926 |                                                 &replaced);
      |                                                 ^~~~~~~~~
      |                                                 |
      |                                                 bool * {aka _Bool *}
In file included from /tmp/next/build/include/drm/drm_connector.h:33,
                 from /tmp/next/build/include/drm/drm_modes.h:33,
                 from /tmp/next/build/include/drm/drm_crtc.h:32,
                 from /tmp/next/build/include/drm/drm_atomic.h:31,
                 from /tmp/next/build/drivers/gpu/drm/tests/drm_hdmi_state_helper_test.c:7:
/tmp/next/build/include/drm/drm_property.h:287:47: note: expected 'ssize_t' {aka 'long int'} but argument is of type 'bool *' {aka '_Bool *'}
  287 |                                       ssize_t max_size,
      |                                       ~~~~~~~~^~~~~~~~
/tmp/next/build/drivers/gpu/drm/tests/drm_hdmi_state_helper_test.c:2922:15: error: too few arguments to function 'drm_property_replace_blob_from_id'
 2922 |         ret = drm_property_replace_blob_from_id(drm,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/next/build/include/drm/drm_property.h:282:5: note: declared here
  282 | int drm_property_replace_blob_from_id(struct drm_device *dev,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Caused by commit

   7436a87db99d5 (drm/tests: hdmi: check the infoframes behaviour)

interacting with

   ca59e33f5a1f6 (drm/atomic: add max_size check to drm_property_replace_blob_from_id())

I have applied a fixup:

From 7e99cf59cfdd75f6815ab3eb0b0d8140878bcd6f Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Mon, 19 Jan 2026 17:27:36 +0000
Subject: [PATCH] drm: Fix up incompatible API change

Signed-off-by: Mark Brown <broonie@kernel.org>