ARM64: Update __NR_compat_syscalls for statmount/listmount
Commit d8b0f5465012 ("wire up syscalls for statmount/listmount") added
two new system calls to arch/arm64/include/asm/unistd32.h but forgot to
update the __NR_compat_syscalls number, thus causing the following build
failures:

/arch/arm64/include/asm/unistd32.h:922:24: error: array index in initializer exceeds array bounds
  922 | #define __NR_statmount 457
      |                        ^~~
arch/arm64/kernel/sys32.c:130:34: note: in definition of macro '__SYSCALL'
  130 | #define __SYSCALL(nr, sym)      [nr] = __arm64_##sym,
      |                                  ^~

Bump up the number by two to accomodate for the new system calls added.

Fixes: d8b0f5465012 ("wire up syscalls for statmount/listmount")
Signed-off-by: Florian Fainelli <florian.fainelli@broadcom.com>