wcslen() prototype in string.h
If this is desired, it should be squashed into the previous change. I
wrote it separately because it is slightly more invasive.

In order to export wcslen() to the rest of the kernel (should it ever be
necessary elsewhere), it needs to be added to string.h, along with nls.h
for the typedef of wchar_t. However, dragging in nls.h into string.h
causes an error in the efistub due to a conflicting function name:

  drivers/firmware/efi/libstub/printk.c:27:5: error: static declaration of 'utf8_to_utf32' follows non-static declaration
     27 | u32 utf8_to_utf32(const u8 **s8)
        |     ^
  include/linux/nls.h:55:12: note: previous declaration is here
     55 | extern int utf8_to_utf32(const u8 *s, int len, unicode_t *pu);
        |            ^
  drivers/firmware/efi/libstub/printk.c:85:26: error: too few arguments to function call, expected 3, have 1
     85 |                 c32 = utf8_to_utf32(&s8);
        |                       ~~~~~~~~~~~~~    ^
  include/linux/nls.h:55:12: note: 'utf8_to_utf32' declared here
     55 | extern int utf8_to_utf32(const u8 *s, int len, unicode_t *pu);
        |            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 errors generated.

Rename the efi function to avoid the conflict.

Signed-off-by: Nathan Chancellor <nathan@kernel.org>