ext4: fix ext4_tune_sb_params padding
The padding at the end of struct ext4_tune_sb_params is architecture
specific and in particular is different between x86-32 and x86-64,
since the __u64 member only enforces struct alignment on the latter.

This shows up as a new warning when test-building the headers with
-Wpadded:

include/linux/ext4.h:144:1: error: padding struct size to alignment boundary with 4 bytes [-Werror=padded]

All members inside the structure are naturally aligned, so the only
difference here is the amount of padding at the end.

Add explicit padding to mount_opts[] to keep the struct members compatible
with the original version and also keep the pad[64] member 8-byte
aligned for future extensions.  This gives a consistent sizeof(struct
ext4_tune_sb_params) of 232 on all architectures and avoids adding compat
ioctl handling for EXT4_IOC_GET_TUNE_SB_PARAM/EXT4_IOC_SET_TUNE_SB_PARAM.

This is an ABI break on x86-32 but hopefully this can go into 6.18.y
early enough as a fixup so no actual users will be affected.

Fixes: 04a91570ac67 ("ext4: implemet new ioctls to set and get superblock parameters")
Reviewed-by: Jan Kara <jack@suse.cz>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>