linux-next: build failure after merge of the drivers-x86 tree
Hi all,

After merging the drivers-x86 tree, today's linux-next build (x86_64
allmodconfig) failed like this:

/tmp/next/build/drivers/platform/arm64/qcom-hamoa-ec.c:394:64: error: incompatible pointer to integer conversion passing 'void *' to parameter of type 'u32' (aka 'unsigned int') [-Wint-conversion]
  394 |                 ec_cdev->cdev = devm_thermal_of_cooling_device_register(dev, NULL, name, ec_cdev,
      |                                                                              ^~~~
/tmp/next/build/include/linux/stddef.h:8:14: note: expanded from macro 'NULL'
    8 | #define NULL ((void *)0)
      |              ^~~~~~~~~~~
/tmp/next/build/include/linux/thermal.h:210:65: note: passing argument to parameter 'cdev_id' here
  210 | devm_thermal_of_cooling_device_register(struct device *dev, u32 cdev_id,
      |

Caused by commit

   5c44f48e91dee (platform: arm64: Add driver for EC found on Qualcomm reference devices)

interacting with

  37324803f049b (thermal/of: Add cooling device ID support)
  3570cb58e3171 (thermal/of: Pass cdev_id and introduce devm registration helper)

from the thermal tree.  I have fixed this up as below and can carry
this, but this will need to be dealt with during the merge window.

From 7402d20e88c7a0f8a3ce34e660ac40683092b547 Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Mon, 8 Jun 2026 14:51:40 +0100
Subject: [PATCH] drivers-x86: hamoa: Fix up semantic conflit with thermal tree

/tmp/next/build/drivers/platform/arm64/qcom-hamoa-ec.c:394:64: error: incompatible pointer to integer conversion passing 'void *' to parameter of type 'u32' (aka 'unsigned int') [-Wint-conversion]
  394 |                 ec_cdev->cdev = devm_thermal_of_cooling_device_register(dev, NULL, name, ec_cdev,
      |                                                                              ^~~~
/tmp/next/build/include/linux/stddef.h:8:14: note: expanded from macro 'NULL'
    8 | #define NULL ((void *)0)
      |              ^~~~~~~~~~~
/tmp/next/build/include/linux/thermal.h:210:65: note: passing argument to parameter 'cdev_id' here
  210 | devm_thermal_of_cooling_device_register(struct device *dev, u32 cdev_id,
      |

Signed-off-by: Mark Brown <broonie@kernel.org>