selftests: Add kselftest framework to the testfile
This patch updates the existing test that checks
for `open(O_TMPFILE)` and `linkat()` behaviors in
mount namespaces to use the kselftest framework.

This includes the following changes:

- Replaced direct error handling with
 `ksft_test_result_*` macros for better reporting
  of test outcomes.

- Added `ksft_print_header()` and `ksft_set_plan()`
 to structure test outputs more effectively.

- Introduced the helper function `is_unshare()` to
  handle unshare-related checks.

- Improved the test flow by adding more detailed pass/fail
  reporting for unshare, mounting, file opening, and linking
  operations.

- Skips the test if it's not run as root, providing an
  appropriate Warning.

Test logs:

Before change:

- Withou root
 error: unshare, errno 1

- With root
 No, output

After change:

- Without root
 TAP version 13
 1..1
 ok 1 # SKIP This test needs root to ru

- With root
 TAP version 13
 1..1
 ok 1 unshare(): we have a new mount namespace.
 1..2
 ok 2 mount(): Root filesystem private mount: Success
 1..3
 ok 3 mount(): Mounting tmpfs on /tmp: Success
 1..4
 ok 4 openat(): Open first temporary file: Success
 1..5
 ok 5 linkat(): Linking the temporary file: Success
 1..6
 ok 6 openat(): Opening the second temporary file: Success
 # Totals: pass:6 fail:0 xfail:0 xpass:0 skip:0 error:0

Signed-off-by: Shivam Chaudhary <cvam0000@gmail.com>