Input: pf1550 - convert to DEFINE_SIMPLE_DEV_PM_OPS
SIMPLE_DEV_PM_OPS() is deprecated and used incorrectly in this new
driver:

drivers/input/misc/pf1550-onkey.c:154:12: error: 'pf1550_onkey_resume' defined but not used [-Werror=unused-function]
  154 | static int pf1550_onkey_resume(struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~~
drivers/input/misc/pf1550-onkey.c:133:12: error: 'pf1550_onkey_suspend' defined but not used [-Werror=unused-function]
  133 | static int pf1550_onkey_suspend(struct device *dev)
      |            ^~~~~~~~~~~~~~~~~~~~

Convert to the modern DEFINE_SIMPLE_DEV_PM_OPS() that avoids these warnings.

Fixes: 9acb215cbebd ("Input: pf1550 - add onkey support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>