RDMA/core: Fix ib_core building error when CONFIG_MMU=n
zap_vma_ptes() depends on CONFIG_MMU. When CONFIG_MMU=n,
a building error occurs due to the zap_vma_ptes() call in
uverbs_user_mmap_disassociate():

ERROR: modpost: "zap_vma_ptes" [drivers/infiniband/core/ib_core.ko] undefined!

Add "#ifdef CONFIG_MMU" to fix this error.

Fixes: 577b3696166a ("RDMA/core: Provide rdma_user_mmap_disassociate() to disassociate mmap pages")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202408072142.mVX227UI-lkp@intel.com/
Signed-off-by: Junxian Huang <huangjunxian6@hisilicon.com>