tracing: make tr->d_max_latency accessible without CONFIG_FSNOTIFY
A recent change attempted to make the tracing_max_latency file visible
unconditionally, but this lead to a build failure:

kernel/trace/trace.c: In function 'trace_create_maxlat_file':
kernel/trace/trace.c:1543:13: error: 'struct trace_array' has no member named 'd_max_latency'; did you mean 'max_latency'?
 1543 |         tr->d_max_latency = trace_create_file("tracing_max_latency",
      |             ^~~~~~~~~~~~~

Make the corresponding change in the header file.

Fixes: ba73713da50e ("tracing: Clean up use of trace_create_maxlat_file()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>