drm/tiny: fix printk format string for 32-bit
A size_t must be printed with the %z modifier instead of %l:

In file included from include/linux/device.h:15,
                 from include/linux/usb.h:19,
                 from drivers/gpu/drm/tiny/appletbdrm.c:19:
drivers/gpu/drm/tiny/appletbdrm.c: In function 'appletbdrm_send_request':
include/drm/drm_print.h:589:54: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
drivers/gpu/drm/tiny/appletbdrm.c:170:17: note: in expansion of macro 'drm_err'
  170 |                 drm_err(drm, "Actual size (%d) doesn't match expected size (%lu)\n",
      |                 ^~~~~~~
drivers/gpu/drm/tiny/appletbdrm.c: In function 'appletbdrm_read_response':
include/drm/drm_print.h:589:54: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
drivers/gpu/drm/tiny/appletbdrm.c:211:17: note: in expansion of macro 'drm_err'
  211 |                 drm_err(drm, "Actual size (%d) doesn't match expected size (%lu)\n",
      |                 ^~~~~~~

Fixes: 0670c2f56e45 ("drm/tiny: add driver for Apple Touch Bars in x86 Macs")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>