fs: Fix build error
The following build error report:
fs/overlayfs/file.c: In function ‘ovl_file_end_write’:
fs/overlayfs/file.c:292:51: error: parameter name omitted
  292 | static void ovl_file_end_write(struct file *file, loff_t, ssize_t)
      |                                                   ^~~~~~
fs/overlayfs/file.c:292:59: error: parameter name omitted
  292 | static void ovl_file_end_write(struct file *file, loff_t, ssize_t)
                                                                  ^~~~~~~

Fixes: 291f180e5929 ("fs: pass offset and result to backing_file end_write() callback")
Signed-off-by: Zheng Zucheng <zhengzucheng@huawei.com>