headers: Add check for C standard version
Compiling the kernel with GCC 15 results in errors, as with GCC 15
the default language version for C compilation has been changed from
-std=gnu17 to -std=gnu23 - unless the language version has been
changed using

    KBUILD_CFLAGS += -std=gnu17

or earlier.

C23 includes new keywords 'bool', 'true' and 'false', which cause
compilation errors in Linux headers:

    ./include/linux/types.h:30:33: error: ‘bool’ cannot be defined
        via ‘typedef’

    ./include/linux/stddef.h:11:9: error: cannot use keyword ‘false’
        as enumeration constant

Add check for C Standard's version in the header files to be able
to compile the kernel with C23.

Signed-off-by: Hanne-Lotta Mäenpää <hannelotta@gmail.com>