landlock: fix typo in landlock_append_net_rule() stub function
There is an extraneous semicolon in the empty stub helper for
this function tha causes randconfig builds to break:

In file included from security/landlock/setup.c:17:
security/landlock/net.h:28:1: error: expected identifier or '(' before '{' token
security/landlock/net.h:26:1: error: 'landlock_append_net_rule' declared 'static' but never defined [-Werror=unused-function]

Fixes: 614d46b333ab9 ("landlock: Add network rules and TCP hooks support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>