clocksource/drivers/exynos_mct: Revert commits causing section mismatches
Commit 5d86e479193b ("clocksource/drivers/exynos_mct: Add module
support") introduced section mismatch failures.
Commit 7e477e9c4eb4 ("clocksource/drivers/exynos_mct: Fix section
mismatch from the module conversion") replaced these to other section
mismatch failures:

  WARNING: modpost: vmlinux: section mismatch in reference: mct_init_dt+0x164 (section: .text) -> register_current_timer_delay (section: .init.text)
  WARNING: modpost: vmlinux: section mismatch in reference: mct_init_dt+0x20c (section: .text) -> register_current_timer_delay (section: .init.text)
  ERROR: modpost: Section mismatches detected.

No progress on real fixing of these happened (intermediary fix was still
not tested), so revert both commits till the work is prepared correctly.

Fixes: 7e477e9c4eb4 ("clocksource/drivers/exynos_mct: Fix section mismatch from the module conversion")
Fixes: 5d86e479193b ("clocksource/drivers/exynos_mct: Add module support")
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>