gpiolib: add missing include
With some randconfigs I'm seeing the following error:

In file included from drivers/gpio/gpiolib-swnode.c:19:
./include/linux/gpio/consumer.h: In function ‘gpiod_enable_hw_timestamp_ns’:
./include/linux/gpio/consumer.h:557:17: error: implicit declaration of function ‘WARN_ON’ [-Wimplicit-function-declaration]
  557 |                 WARN_ON(desc);
      |                 ^~~~~~~

Pull in bug.h to fix it.

Signed-off-by: Bartosz Golaszewski <bartosz.golaszewski@linaro.org>