rust: helpers: Fix pci_free_irq_vectors() build with CONFIG_PCI disabled
Fix the following error with CONFIG_PCI disabled:

In file included from linux/rust/helpers/helpers.c:40:
linux/rust/helpers/pci.c:36:2: error: call to undeclared function 'pci_free_irq_vectors'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   36 |         pci_free_irq_vectors(dev);
      |         ^
linux/rust/helpers/pci.c:36:2: note: did you mean 'pci_alloc_irq_vectors'?
linux/include/linux/pci.h:2208:1: note: 'pci_alloc_irq_vectors' declared here
 2208 | pci_alloc_irq_vectors(struct pci_dev *dev, unsigned int min_vecs,
      | ^
1 error generated.
make[3]: *** [linux/rust/Makefile:621: rust/helpers/helpers.o] Error 1
make[3]: *** Waiting for unfinished jobs....
linux/rust/helpers/pci.c:36:2: error: call to undeclared function 'pci_free_irq_vectors'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
Unable to generate bindings: clang diagnosed error: linux/rust/helpers/pci.c:36:2: error: call to undeclared function 'pci_free_irq_vectors'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

Fixes: 473b9f331718 ("rust: pci: fix build failure when CONFIG_PCI_MSI is disabled")
Signed-off-by: FUJITA Tomonori <fujita.tomonori@gmail.com>