Fix unused variable warning in 'drm_print.h'
previous code can make unused variable warning,

e.g. when CONFIG_DRM_USE_DYNAMIC_DEBUG is set,
this outputs the following build error.

drivers/gpu/drm/drm_print.c: In function ‘__drm_printfn_dbg’:
drivers/gpu/drm/drm_print.c:218:33: error: unused variable ‘category’ [-Werror=unused-variable]
  218 |         enum drm_debug_category category = p->category;

so i simply add '(void)(category);' to remove unused variable warning,
by referring to "https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html".

Signed-off-by: Gyeyoung Baek <gye976@gmail.com>