x86/mm: Define PTRS_PER_PMD for assembly code too
* Ingo Molnar <mingo@kernel.org> wrote:

> Separating out the assembler-compatible defines from the types
> headers appears to be a bigger patch, since it's all mixed in with C
> syntax:
>
> <=-----------------------------------===============================
> typedef struct { pud_t pud; } pmd_t;
>
> #define PMD_SHIFT       PUD_SHIFT
> #define PTRS_PER_PMD    1
> #define PMD_SIZE        (1UL << PMD_SHIFT)
> #define PMD_MASK        (~(PMD_SIZE-1))
>
> /*
>  * The "pud_xxx()" functions here are trivial for a folded two-level
>  * setup: the pmd is never bad, and a pmd always exists (as it's folded
>  * into the pud entry)
>  */
> static inline int pud_none(pud_t pud)           { return 0; }
> static inline int pud_bad(pud_t pud)            { return 0; }
> static inline int pud_present(pud_t pud)        { return 1; }
> ================================================================>
>
> In any case I've removed the commit for the time being until this all
> is cleared up.

So there's a simple solution: define it on i386 too, via the patch
below. It appears the double-definition doesn't create any warnings, on
GCC at least.

But if it's an issue, we could do something like this in
<asm-generic/pgtable-nopmd.h>:

 #if defined(PTRS_PER_PMD) && (PTRS_PER_PMD != 1)
 # error "mm: Wait a minute, that's a super confusing pagetable setup ..."
 #endif

?

Thanks,

	Ingo

=========================>
From: Ingo Molnar <mingo@kernel.org>
Date: Thu, 6 Mar 2025 22:53:49 +0100
Subject: [PATCH] x86/mm: Define PTRS_PER_PMD for assembly code too

Andy reported the following build warning from head_32.S:

  In file included from arch/x86/kernel/head_32.S:29:
  arch/x86/include/asm/pgtable_32.h:59:5: error: "PTRS_PER_PMD" is not defined, evaluates to 0 [-Werror=undef]
       59 | #if PTRS_PER_PMD > 1

The reason is that on 2-level i386 paging the folded in PMD's
PTRS_PER_PMD constant is not defined in assembly headers,
only in generic MM C headers.

Instead of trying to fish out the definition from the generic
headers, just define it - it even has a comment for it already...

Reported-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Ingo Molnar <mingo@kernel.org>