tools/cgroup/slabinfo: Fix use of slab.memcg_data
After the introduce slabobj_ext to support slab object extensions, the
memcg_slabinfo tool broke. An attempt to run it produces a trace like
this:
Traceback (most recent call last):
  File "/usr/local/bin/drgn", line 8, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib64/python3.11/site-packages/drgn/cli.py", line 688, in _main
    runpy.run_path(
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/root/memcg_slabinfo.py", line 225, in <module>
    main()
  File "/root/memcg_slabinfo.py", line 195, in main
    objcg_vec_raw = slab.memcg_data.value_()
AttributeError: 'struct slab' has no member 'memcg_data'

Fixes: 21c690a349ba ("mm: introduce slabobj_ext to support slab object extensions")
Signed-off-by: Hongfu Li <lihongfu@kylinos.cn>