tracing: remove duplicate latency_fsnotify() stub
During the move, an extra copy of latency_fsnotify() crept in:

kernel/trace/trace_snapshot.c:395:20: error: redefinition of 'latency_fsnotify'
  395 | static inline void latency_fsnotify(struct trace_array *tr) { }
      |                    ^~~~~~~~~~~~~~~~
In file included from kernel/trace/trace_snapshot.c:6:
kernel/trace/trace.h:858:20: note: previous definition of 'latency_fsnotify' with type 'void(struct trace_array *)'
  858 | static inline void latency_fsnotify(struct trace_array *tr) { }
      |                    ^~~~~~~~~~~~~~~~

The function is still called from the hwlat and osnoise tracers, so the
copy in the header file is the one that has to stay.

Remove the extra one from trace_snapshot.c

Fixes: bade44fe5462 ("tracing: Move snapshot code out of trace.c and into trace_snapshot.c")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>