iio: adc: ad_sigma_delta: select CONFIG_IIO_BUFFER_DMAENGINE
The newly added support for SPI offloading causes a link error
when the dmaengine buffer helpers are unavailable:

arm-linux-gnueabi-ld: drivers/iio/adc/ad_sigma_delta.o: in function `devm_ad_sd_setup_buffer_and_trigger':
ad_sigma_delta.c:(.text+0x6b8): undefined reference to `devm_iio_dmaengine_buffer_setup_with_handle'

Fixes: 219da3ea842a ("iio: adc: ad_sigma_delta: add SPI offload support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>