kbuild: install-extmod-build: Add missing python libraries
scripts/lib has been moved to tools/lib/python recently. Since then, I
got a regression while building out-of-tree modules with W=<anything>
(1/2/3/c/e):

  $ make -C /lib/modules/6.19.0-rc6/build/ M="$(pwd)" modules V=1 W=1
  [...]
  make -f /usr/src/linux-headers-6.19.0-rc6/scripts/Makefile.build obj=. need-builtin=1 need-modorder=1
  # CC [M]  mod.o
  [...]
  # cmd_checkdoc mod.o
  PYTHONDONTWRITEBYTECODE=1 python3 /usr/src/linux-headers-6.19.0-rc6/scripts/kernel-doc.py -none mod.c
  Traceback (most recent call last):
    File "/usr/src/linux-headers-6.19.0-rc6/scripts/kernel-doc.py", line 339, in <module>
      main()
      ~~~~^^
    File "/usr/src/linux-headers-6.19.0-rc6/scripts/kernel-doc.py", line 295, in main
      from kdoc.kdoc_files import KernelFiles             # pylint: disable=C0415
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ModuleNotFoundError: No module named 'kdoc'
  make[3]: *** [/usr/src/linux-headers-6.19.0-rc6/scripts/Makefile.build:287: mod.o] Error 1

Fix it by installing python libraries from tools/lib/python.

Fixes: 778b8ebe5192 ("docs: Move the python libraries to tools/lib/python")
Signed-off-by: Rong Zhang <i@rong.moe>