can: rockchip_canfd: Use div_s64() in rkcanfd_timestamp_init()
When building with clang for a 32-bit target, such as arm, a libcall is
generated when dividing the result of clocksource_cyc2ns(), which
returns a signed 64-bit integer:

  ERROR: modpost: "__aeabi_ldivmod" [drivers/net/can/rockchip/rockchip_canfd.ko] undefined!

Use div_s64() to avoid generating the libcall.

Fixes: 4e1a18bab124 ("can: rockchip_canfd: add hardware timestamping support")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>