spi: amd: add CONFIG_PCI dependency
Without CONFIG_PCI, the module_pci_driver() macro is not defined:

drivers/spi/spi-amd-pci.c:67:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   67 | module_pci_driver(amd_spi_pci_driver);

Fixes: 9725d95a3d0a ("spi: spi_amd: Add PCI-based driver for AMD HID2 SPI controller")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250410140809.812863-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>