fbdev: sstfb: Fix build after CONFIG_FB_DEVICE changes
Commit 7c0510bb3452 ("fbdev: sstfb: Make CONFIG_FB_DEVICE optional")
made sstfb's dependency on CONFIG_FB_DEVICE optional. Fix the build
error

drivers/video/fbdev/sstfb.c: In function 'sstfb_probe':
drivers/video/fbdev/sstfb.c:1439:2: error: invalid preprocessing directive #fdef; did you mean #ifdef?
 1439 | #fdef CONFIG_FB_DEVICE
      |  ^~~~
      |  ifdef
drivers/video/fbdev/sstfb.c:1442:2: error: #endif without #if
 1442 | #endif
      |  ^~~~~

plus some formatting changes.

Also remove the dependency in the Kconfig rule, so that the driver
can be selected without FB_DEVICE enabled.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Closes: https://lore.kernel.org/lkml/20241015120119.533e65e8@canb.auug.org.au/raw
Signed-off-by: Thomas Zimmermann <tzimmermann@suse.de>
Fixes: 7c0510bb3452 ("fbdev: sstfb: Make CONFIG_FB_DEVICE optional")
Cc: Gonzalo Silvalde Blanco <gonzalo.silvalde@gmail.com>
Cc: Thomas Zimmermann <tzimmermann@suse.de>
Cc: Helge Deller <deller@gmx.de>