rust: io: always inline methods leading to build_assert
`build_assert` relies on the compiler to optimize out its error path,
lest build fails with the dreaded error:

    ERROR: modpost: "rust_build_error" [drivers/gpu/nova-core/nova_core.ko] undefined!

It has been observed that very trivial code performing I/O accesses
(sometimes even using an immediate value) would seemingly randomly fail
with this error whenever `CLIPPY=1` was set. Removing the CLIPPY option
makes the error go away, but that's obviously not a great workaround.
Clippy appears to influence the way the compiler optimizes things,
making it on occasion generate a method where we would need it to inline
in order to satisfy a `build_assert`.

Fix this by instructing the compiler to always inline the methods
leading to `build_assert`. This stronger directive is effective even
when `CLIPPY=1` is specified, which gets rid of this error.

Signed-off-by: Alexandre Courbot <acourbot@nvidia.com>