selftests: vDSO: vdso_test_correctness: Include linux/types.h
When cross compiling the vDSO tests with a Yocto Scarthgap SDK, the
following build errors are encountered:

make headers
make -C tools/testing/selftests CC="${CC}" TARGETS="vDSO"
  CC       vdso_test_correctness
vdso_test_correctness.c:58:27: error: unknown type name
‘__kernel_time_t’
   58 | typedef time_t (*vtime_t)(__kernel_time_t *tloc);
      |                           ^~~~~~~~~~~~~~~
vdso_test_correctness.c:60:1: error: unknown type name ‘vtime_t’;
did you mean ‘time_t’?
   60 | vtime_t vdso_time;
      | ^~~~~~~
      | time_t

The code uses __kernel_time_t without including the header that declares
it. Fix this by including <linux/types.h>.

Fixes: bed0053a6303 ("selftests: vDSO: vdso_test_correctness: Add a test for time()")
Signed-off-by: Ovidiu Panait <ovidiu.panait.rb@renesas.com>