mm: include linux/pagemap.h where needed
The pagemap header used to be included by accident here but is now
missing:

mm/z3fold.c: In function 'free_z3fold_page':
mm/z3fold.c:353:17: error: implicit declaration of function 'lock_page'; did you mean 'copy_page'? [-Wimplicit-function-declaration]
  353 |                 lock_page(page);
      |                 ^~~~~~~~~
      |                 copy_page

Add the correct #include statement.

Fixes: a6c37165ca40 ("mempolicy.h: remove unnecessary header file inclusions with no test failure")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>