checkpatch: Warn about sign offs if there's an accidental patch separator
The regex ^---$ to detect a patch separator, means a patch is
considerd to have been separated only when the line is exactly just
"---". git-mailinfo (and thus git am) treats any line starting with
"---" as the start of a patch. This can mean a comment causes
git-mailinfo to truncate the commit message if the line in the comment
starts with "---". checkpatch won't warn about things like missing
sign offs after the "---" started comment as it doesn't see the patch
as having started yet. The recording of sign offs is made to ignore
the case it is in a patch. This issue caused missing tags in commit
6528cdd61590 ("perf tests stat: Add test for error for an offline CPU")
as reported by Stephen Rothwell <sfr@canb.auug.org.au> in:
https://lore.kernel.org/lkml/20251205092428.3e2b94e3@canb.auug.org.au/

Before:

  $ ./scripts/checkpatch.pl v2-0006-perf-tests-stat-Add-test-for-error-for-an-offline.patch
  total: 0 errors, 0 warnings, 39 lines checked

  v2-0006-perf-tests-stat-Add-test-for-error-for-an-offline.patch has no obvious style problems and is ready for submission.

After:

  $ ./scripts/checkpatch.pl v2-0006-perf-tests-stat-Add-test-for-error-for-an-offline.patch
  ERROR: Missing Signed-off-by: line(s)

  total: 1 errors, 0 warnings, 39 lines checked

  NOTE: For some of the reported defects, checkpatch may be able to
        mechanically convert to the typical style using --fix or --fix-inplace.

  v2-0006-perf-tests-stat-Add-test-for-error-for-an-offline.patch has style problems, please review.

  NOTE: If any of the errors are false positives, please report
        them to the maintainer, see CHECKPATCH in MAINTAINERS.

Signed-off-by: Ian Rogers <irogers@google.com>