nmi_backtrace: fix trigger_allbutcpu_cpu_backtrace() stub definition
The prototype for the extern declaration was changed, but the one for
the empty stub is now missing an unused argument:

kernel/watchdog.c: In function 'watchdog_timer_fn':
kernel/watchdog.c:521:4: error: too many arguments to function 'trigger_allbutcpu_cpu_backtrace'
  521 |    trigger_allbutcpu_cpu_backtrace(smp_processor_id());
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from kernel/watchdog.c:17:
include/linux/nmi.h:193:20: note: declared here
  193 | static inline bool trigger_allbutcpu_cpu_backtrace(void)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 0ca1d340a231e ("nmi_backtrace: allow excluding an arbitrary CPU")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>