mm/vmalloc: fix build error
commit 056b93566a35 ("mm/vmalloc: warn only once when vmalloc
detect invalid gfp flags") modify the function call from WARN to WARN_ONCE.

WARN_ONCE input parameter format error, missing ',' tag.
Resulting in the following compilation errors:

mm/vmalloc.c:3940:19: error: expected `)' before `invalid_mask'
 3940 |                   invalid_mask, &invalid_mask, flags, &flags);

After adding the "," tag, the compilation passed.

Link: https://lkml.kernel.org/r/20251118155034.273696-1-peng8420.li@gmail.com
Signed-off-by: Peng Li <peng8420.li@gmail.com>
Cc: David Heidelberg <david@ixit.cz>
Cc: "Uladzislau Rezki (Sony)" <urezki@gmail.com>
Cc: Vishal Moola (Oracle) <vishal.moola@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>