mm/highmem: fix __kmap_to_page() build error
From 706fa431358390713c47667f6bcaecce56d071cc Mon Sep 17 00:00:00 2001
From: William Tambe <williamt@cadence.com>
Date: Thu, 11 Dec 2025 12:38:19 -0800
Subject: [PATCH] mm/highmem: fix __kmap_to_page() build error

This changes fixes following build error which is probably a miss from:
ef6e06b2ef87 highmem: fix kmap_to_page() for kmap_local_page() addresses

mm/highmem.c:184:66: error: 'pteval' undeclared (first use in this
function); did you mean 'pte_val'?
184 | idx = arch_kmap_local_map_idx(i, pte_pfn(pteval));

In __kmap_to_page(), pteval is used but does not exist in the function.

Reviewed-by: Max Filippov <jcmvbkbc@gmail.com>
Signed-off-by: William Tambe <williamt@cadence.com>