PCI/bwctrl: Remove unused pcie_bwctrl_lbms_rwsem
PCI/bwctrl: Remove unused pcie_bwctrl_lbms_rwsem

Builds with CONFIG_PREEMPT_RT=y get the following build error:

drivers/pci/pcie/bwctrl.c:56:22: error: ‘pcie_bwctrl_lbms_rwsem’ defined but not used [-Werror=unused-variable]

Therefore, remove this unused variable.  Perhaps this should be folded
into the commit shown below.

Fixes: 0238f352a63a ("PCI/bwctrl: Replace lbms_count with PCI_LINK_LBMS_SEEN flag")
Signed-off-by: Paul E. McKenney <paulmck@kernel.org>
Cc: "Ilpo Järvinen" <ilpo.jarvinen@linux.intel.com>
Cc: Bjorn Helgaas <bhelgaas@google.com>
Cc: <linux-pci@vger.kernel.org>