drm/i915/pmu: Use raw_spin_lock where ever needed in i915 pmu
Currently i915 pmu driver gets registered with linux perf
subsystem with its callback functions implemented, it is
using spin_lock for synchronization where ever is needed.
linux perf subsystem in some instance is using raw_spin_locks
for synchronization and calls the i915 pmu callback functions with
raw_spin_lock held.

The issue is
When PREEMPT_RT is configured in kernel config the normal spin_lock
behaves as mutex lock and when these are called with raw_spin_lock
held race condition can occur.So in the path of the raw_spin_lock
held convert spin_lock into raw_spin_lock where ever is needed.

v2:
- Fix build error below
  drivers/gpu/drm/i915/i915_pmu.c:233:31: error: passing argument 1
  of ‘_raw_spin_lock_irqsave’ from incompatible pointer type
  [-Werror=incompatible-pointer-types]
  233 |         raw_spin_lock_irqsave(&pmu->lock, flags);
      |                               ^~~~~~~~~~

Signed-off-by: Ravi Kumar Vodapalli <ravi.kumar.vodapalli@intel.com>