net: macb: Move macb_{alloc,free}_tieoff() out of CONFIG_OF block
Commit 5262eab9462a ("net: macb: allocate tieoff descriptor once across
device lifetime") moved macb_alloc_tieoff() and macb_free_tieoff() into
a CONFIG_OF block, breaking the build when it is disabled:

  drivers/net/ethernet/cadence/macb_main.c: In function 'macb_probe':
  drivers/net/ethernet/cadence/macb_main.c:5951:15: error: implicit declaration of function 'macb_alloc_tieoff' [-Wimplicit-function-declaration]
   5951 |         err = macb_alloc_tieoff(bp);
        |               ^~~~~~~~~~~~~~~~~
  drivers/net/ethernet/cadence/macb_main.c:5973:9: error: implicit declaration of function 'macb_free_tieoff' [-Wimplicit-function-declaration]
   5973 |         macb_free_tieoff(bp);
        |         ^~~~~~~~~~~~~~~~

Moving macb_alloc_tieoff() from its original positive does not appear to
be necessary, so move it and macb_free_tieoff() back out of the
CONFIG_OF block to clear up the error.

Fixes: 5262eab9462a ("net: macb: allocate tieoff descriptor once across device lifetime")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>