vfio/pds: Limit Calling dev_dbg function to CONFIG_PCI_ATS
If CONFIG_PCI_ATS isn't set, then pdev->physfn is not defined.
So it causes a compilation issue:

../drivers/vfio/pci/pds/vfio_dev.c:165:30: error: ‘struct pci_dev’ has no member named ‘physfn’; did you mean ‘is_physfn’?
  165 |   __func__, pci_dev_id(pdev->physfn), pci_id, vf_id,
      |                              ^~~~~~

Signed-off-by: Shixiong Ou <oushixiong@kylinos.cn>