cxl: Drop unused detach_spa()
Clang warns:
  drivers/misc/cxl/native.c:272:20: error: unused function 'detach_spa' [-Werror,-Wunused-function]

It was created as part of some refactoring in commit 05155772f642 ("cxl:
Allocate and release the SPA with the AFU"), but has never been called
in its current form. Drop it.

Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>