arm64: pi: add early_map_kernel prototype
The newly added function only has a caller from assembler code, so it
works without an extern prototype, but we get a warning if it's missing:

arch/arm64/kernel/pi/map_kernel.c:224:24: error: no previous prototype for 'early_map_kernel' [-Werror=missing-prototypes]

Fixes: 478ea5689054 ("arm64: head: Move early kernel mapping routines into C code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>