LoongArch: Enable tracing infrastructure in defconfig
When executing the command "perf list", I met "Error: failed to open
tracing events directory" twice, the first reason is that there is no
"/sys/kernel/tracing/events" directory due to it does not enable the
kernel tracing infrastructure with CONFIG_FTRACE, the second reason
is that there is no root privileges.

Although the error string was added to tell the users what happened
and what should to do in commit b48543c451c3 ("perf list: Give clues
if failed to open tracing events directory"), it is better to enable
CONFIG_FTRACE in defconfig to avoid the error message at runtime:

  $ ./perf list
  Error: failed to open tracing events directory
  /sys/kernel/tracing/events: No such file or directory

Additionally, CONFIG_UPROBE_EVENTS is default y only if CONFIG_FTRACE
is set, otherwise there exists the following error:

  $ ./perf probe -x /usr/lib64/libcrypto.so BN_mod_mul_montgomery
  /sys/kernel/tracing//uprobe_events does not exist.
  Please rebuild kernel with CONFIG_UPROBE_EVENTS=y.
    Error: Failed to add events.

Signed-off-by: Tiezhu Yang <yangtiezhu@loongson.cn>