kbuild: Fix 'import module' error
Commit b1992c3772e6 ("kbuild: use $(src) instead of $(srctree)/$(src)
for source directory") only changes 'symlinks'. However, 'cmd_symlink'
is not changed accordingly. This leads to the following error:

Traceback (most recent call last):
  File "/your_kernel_obj/linux/vmlinux-gdb.py",
 line 29, in <module>
    import linux.utils
ModuleNotFoundError: No module named 'linux.utils'

Fix the issue by using $(src) instead of $(srctree)/$(src).

Fixes: b1992c3772e6 ("kbuild: use $(src) instead of $(srctree)/$(src) for source directory")
Signed-off-by: Adrian Huang <ahuang12@lenovo.com>