acpi: allow building without CONFIG_HAS_IOPORT
CONFIG_HAS_IOPORT will soon become optional and cause a build time
failure when it is disabled but a driver calls inb()/outb(). At the
moment, all architectures that can support ACPI have port I/O, but
this is not necessarily the case in the future. The result is
a set of errors like:

drivers/acpi/osl.c: In function 'acpi_os_read_port':
include/asm-generic/io.h:542:14: error: call to '_inb' declared with attribute error: inb()) requires CONFIG_HAS_IOPORT

In function 'acpi_ec_read_status',
    inlined from 'advance_transaction' at drivers/acpi/ec.c:665:11:
include/asm-generic/io.h:542:14: error: call to '_inb' declared with attribute error: inb()) requires CONFIG_HAS_IOPORT

Since the embedded controller can only exist when port I/O is
active, it makes sense to disable that code on targets that don't
have it. The same is true for anything using acpi_os_read_port()
and similar functions.

Add compile-time conditionals around all of those and their callers.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>