sound: sof: ioc4-topology: avoid extra dai_params copy
The snd_pcm_hw_params structure is really too large to fit on the
stack. Because of the way that clang inlines functions, it ends up
twice in one function, which exceeds the 1024 byte limit for 32-bit
architecutes:

sound/soc/sof/ipc4-topology.c:1700:1: error: stack frame size (1304) exceeds limit (1024) in 'sof_ipc4_prepare_copier_module' [-Werror,-Wframe-larger-than]
sof_ipc4_prepare_copier_module(struct snd_sof_widget *swidget,

From what I can tell, this was unintentional, as both
sof_ipc4_prepare_dai_copier() and sof_ipc4_prepare_copier_module() make a
copy for the same purpose, but copying it once has the exact same effect.

Remove the extra copy and change the direct struct assignment to
an explicit memcpy() call to make it clearer to the reader that this
is what happens. Note that gcc treats struct assignment as a memcpy()
that may be inlined anyway, so the resulting object code is the same.

Fixes: f9209644ae76 ("ASoC: SOF: ipc4-topology: Correct DAI copier config and NHLT blob request")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>