cxl/pci: Unifi CXL trace logging for CXL Endpoints and CXL Ports
CXL currently has separate trace routines for CXL Port errors and CXL
Endpoint errors. This is inconvnenient for the user because they must
enable 2 sets of trace routines. Make updates to the trace logging such
that a single trace routine logs both CXL Endpoint and CXL Port protocol
errors.

Also, CXL RAS errors are currently logged using the associated CXL port's
name returned from devname(). They are typically named with 'port1',
'port2', etc. to indicate the hierarchial location in the CXL topology.
But, this doesn't clearly indicate the CXL card or slot reporting the
error.

Update the logging to also log the corresponding PCIe devname. This will
give a PCIe SBDF or ACPI object name (in case of CXL HB). This will provide
details helping users understand which physical slot and card has the
error.

Below is example output after making these changes.

Correctable error example output:
cxl_port_aer_correctable_error: device=port1 (0000:0c:00.0) parent=root0 (pci0000:0c) status='Received Error From Physical Layer'

Uncorrectable error example output:
cxl_port_aer_uncorrectable_error: device=port1 (0000:0c:00.0) parent=root0 (pci0000:0c) status: 'Memory Byte Enable Parity Error' first_error: 'Memory Byte Enable Parity Error'

Signed-off-by: Terry Bowman <terry.bowman@amd.com>