math64.h: provide rounddown_u64 variant for rounddown macro
There is currently a problem with the usage of rounddown() macro with
u64 dividends. This causes compilation error on specific arch where
64-bit division is done on 32-bit system.

To be more specific GCC try to optimize the function and replace it
with __umoddi3() but this is actually not compiled in the kernel.

Example:
pwm-airoha.c:(.text+0x8f8): undefined reference to `__umoddi3'

To better handle this, introduce a variant of rounddown() macro,
rounddown_u64() that can be used exactly for this scenario.

The new rounddown_u64() in math64.h uses do_div() to do the heavy work
of handling internally all the magic for the 64-bit division on 32-bit
(and indirectly fix the compilation error).

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>