docs: filesystems: fix compile error in netfs_library.rst
`make htmldocs` reports the following error:

  Error: Cannot open file fs/netfs/io.c

Fix it by removing the unused kernel-doc reference.

Fixes: 86b374d061ee ("netfs: Remove fs/netfs/io.c")
Signed-off-by: ChenXiaoSong <chenxiaosong@kylinos.cn>