irqchip/ast2700-intc: reduce stack usage in kunit tests
Build testing this driver can show excessive stack usage, because
of the construction of various large structures on the stack:

drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i1o1mc0i1o1_bad_range_upstream':
drivers/irqchip/irq-ast2700-intc0-test.c:451:1: error: the frame size of 1616 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  451 | }
      | ^
drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i1o2mc0i1o1_invalid':
drivers/irqchip/irq-ast2700-intc0-test.c:403:1: error: the frame size of 1632 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  403 | }
      | ^
drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i2o2mc0i1o1':
drivers/irqchip/irq-ast2700-intc0-test.c:292:1: error: the frame size of 1632 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  292 | }
      | ^
drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i1o1mc0i1o1':
drivers/irqchip/irq-ast2700-intc0-test.c:233:1: error: the frame size of 1632 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  233 | }
      | ^
drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i1o1c0i1o1_disconnected':
drivers/irqchip/irq-ast2700-intc0-test.c:183:1: error: the frame size of 1616 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  183 | }
      | ^
drivers/irqchip/irq-ast2700-intc0-test.c: In function 'aspeed_intc0_resolve_route_c1i1o1c0i1o1_connected':
drivers/irqchip/irq-ast2700-intc0-test.c:135:1: error: the frame size of 1632 bytes is larger than 1536 bytes [-Werror=frame-larger-than=]
  135 | }
      | ^

The largest structure in each case is the irq_domain. Since at most
two of its members are actually assigned here, change this part to
be dynamically allocated and initialized in a common helper.

The other structures here are still fairly large, so it would be
possible to take this further by making additional structures
allocated either statically or through kzalloc(), but the simpler
fix is sufficient to stay below the warning limit.

Fixes: 46e39ee92d14 ("irqchip/ast2700-intc: Add KUnit tests for route resolution")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>