LoongArch: KVM: Ensure ret is always initialized in kvm_eiointc_{read,write}()
Clang warns (or errors with CONFIG_WERROR=y):

  arch/loongarch/kvm/intc/eiointc.c:512:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
    512 |         default:
        |         ^~~~~~~
  arch/loongarch/kvm/intc/eiointc.c:716:2: error: variable 'ret' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
    716 |         default:
        |         ^~~~~~~

Set ret to -EINVAL in the default case to resolve the warning, as len
was not a valid value for the functions to handle.

Fixes: f810ef038c66 ("LoongArch: KVM: Add EIOINTC read and write functions")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>