mm/page_alloc: Mark has_unaccepted_memory() with __maybe_unused
When has_unaccepted_memory() is unused, it prevents kernel builds
with clang, `make W=1` and CONFIG_WERROR=y:

mm/page_alloc.c:7036:20: error: unused function 'has_unaccepted_memory' [-Werror,-Wunused-function]
 7036 | static inline bool has_unaccepted_memory(void)
      |                    ^~~~~~~~~~~~~~~~~~~~~

Fix this by marking it with __maybe_unused (all cases for the sake of
symmetry).

See also commit 6863f5643dd7 ("kbuild: allow Clang to find unused static
inline functions for W=1 build").

Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>