linux-next: build failure after merge of the origin tree
Hi all,

After merging the origin tree, today's linux-next build (perf.log perf)
failed like this:

util/btf.c: In function '__btf_type__find_member_by_name':
util/btf.c:19:43: error: comparison of integer expressions of different signedness: 'int' and '__u32' {aka 'unsigned int'} [-Werror=sign-compare]
   19 |         for (i = 0, m = btf_members(t); i < btf_vlen(t); i++, m++) {
      |                                           ^
cc1: all warnings being treated as errors

Triggered by commit:

   f7a6b9eaff3e6 (bpf: Extend BTF UAPI vlen, kinds to use unused bits)

This was dealt with in -next as part of a conflict resolution,
converting i to a u32, but that doesn't seem to have been picked up
anywhere.  I will apply the fixup below (which I'll also send
separately).

From 47cd4a2a08f874af25930c14437633af43a4a69c Mon Sep 17 00:00:00 2001
From: Mark Brown <broonie@kernel.org>
Date: Wed, 17 Jun 2026 13:42:10 +0100
Subject: [PATCH] perf: Fix up build failure due to bpf changes

Fix

util/btf.c: In function '__btf_type__find_member_by_name':
util/btf.c:19:43: error: comparison of integer expressions of different signedness: 'int' and '__u32' {aka 'unsigned int'} [-Werror=sign-compare]
   19 |         for (i = 0, m = btf_members(t); i < btf_vlen(t); i++, m++) {
      |                                           ^
cc1: all warnings being treated as errors

by making the variable the same type as the function.

Signed-off-by: Mark Brown <broonie@kernel.org>