ASoC: rt1320: fix 32-bit link failure
A plain 64-bit division causes a link failure in some configurations:

ERROR: modpost: "__aeabi_uldivmod" [sound/soc/codecs/snd-soc-rt1320-sdw.ko] undefined!

Since this divides by a constant, using the div_u64() macro ends up
turning this into an efficient multiply/shift operation where possible.

In rt1320_calc_r0(), the open-coded shift seems a litle simpler.

Fixes: 4f1a2dc565fe ("ASoC: rt1320: support calibration and temperature/r0 loading")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20251223215259.677762-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>