dm-pcache: Fix 64-bit division for 32-bit platforms in get_kset_id()
When building for a 32-bit platform (such as ARCH=i386 allmodconfig),
there is a modpost error:

  ERROR: modpost: "__umoddi3" [drivers/md/dm-pcache/dm-pcache.ko] undefined!

Hacking up the driver Makefile to allow building into the kernel shows
that the division comes from get_kset_id(), which is inlined into
cache_key_append() in cache_key.c.

Use the helper div_u64_rem() to avoid emitting a libcall on 32-bit targets.

Fixes: fd5cc4922bef ("dm-pcache: add persistent cache target in device-mapper")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>