btrfs: fix stack size warning in btrfs_test_delayed_refs()
The newly added code has a btrfs_transaction structure on the stack,
which makes it somewhat too large for 32-bit kernels:

fs/btrfs/tests/delayed-refs-tests.c: In function 'btrfs_test_delayed_refs':
fs/btrfs/tests/delayed-refs-tests.c:1012:1: error: the frame size of 1088 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 1012 | }
      | ^

Change this to a dynamic allocation instead.

Fixes: fa3dda44871b ("btrfs: selftests: add delayed ref self test cases")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>