blk-throttle: Fix some potential string truncation in tg_prfill_limit()
When compiled with W=1, we get:
  block/blk-throttle.c: In function ‘tg_prfill_limit’:
  block/blk-throttle.c:1539:74: error: ‘snprintf’ output may be truncated before the last format character [-Werror=format-truncation=]
   1539 |                         snprintf(idle_time, sizeof(idle_time), " idle=%lu",
        |                                                                          ^
  block/blk-throttle.c:1539:25: note: ‘snprintf’ output between 8 and 27 bytes into a destination of size 26
   1539 |                         snprintf(idle_time, sizeof(idle_time), " idle=%lu",
        |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1540 |                                 tg->idletime_threshold_conf);
        |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  block/blk-throttle.c:1546:43: error: ‘%lu’ directive output may be truncated writing between 1 and 20 bytes into a region of size 17 [-Werror=format-truncation=]
   1546 |                                 " latency=%lu", tg->latency_target_conf);
        |                                           ^~~
  block/blk-throttle.c:1546:33: note: directive argument in the range [0, 18446744073709551614]
   1546 |                                 " latency=%lu", tg->latency_target_conf);
        |                                 ^~~~~~~~~~~~~~
  block/blk-throttle.c:1545:25: note: ‘snprintf’ output between 11 and 30 bytes into a destination of size 26
   1545 |                         snprintf(latency_time, sizeof(latency_time),
        |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   1546 |                                 " latency=%lu", tg->latency_target_conf);
        |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In order to fix it, remove all the intermediate buffers and write directly
into the 'sf' seq_file.

Fixes: ada75b6e5b2a ("blk-throttle: add interface to configure idle time threshold")
Fixes: ec80991d6fc2 ("blk-throttle: add interface for per-cgroup target latency")
Signed-off-by: Christophe JAILLET <christophe.jaillet@wanadoo.fr>