selftests/vm: fix undefined reference of the `default_huge_page_size`
The commit a584c7734a4d ("selftests: mm: fix map_hugetlb failure on
64K page size systems") backported the fix from v6.8 to stable v6.1.
The patch uses default_huge_page_size() function, which definition
moved into vm_util.[ch] by commit bd4d67e76f699 ("selftests/mm:
merge default_huge_page_size() into one") merged to upsream since
v6.4. However, in v6.1 common definition/declaration for the
default_huge_page_size() we doesn't have, the following build
error is seen:

map_hugetlb.c:79:25: warning: implicit declaration of function
‘default_huge_page_size’ [-Wimplicit-function-declaration]
   79 |         hugepage_size = default_huge_page_size();
      |                         ^~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /tmp/ccx95BZz.o: in function `main':
map_hugetlb.c:(.text+0x104): undefined reference to
`default_huge_page_size'

Place default_huge_page_size() function body into map_hugetlb.c
to fix this issue.

Fixes: a584c7734a4d ("selftests: mm: fix map_hugetlb failure on 64K page size systems")
Signed-off-by: Andrey Kalachev <kalachev@swemel.ru>