selftests: mqueue: initialize array buf before using it
Currently array buf is not being initialized and so garbage values
on the stack are being used in the mq_send calls. Initialize the
values in the array to zero.

Cleans up cppcheck warning:
mq_perf_tests.c:334:25: error: Uninitialized variable: buff [uninitvar]

Signed-off-by: Colin Ian King <colin.i.king@gmail.com>