drbd: fix rdma dependency
The new rdma transport module uses a trick to only build support
if infiniband/rdma is enabled. This seems to be done the wrong way
around, as it gets built if RDMA is in a loadable module, but not
if it's built-in.

However, this fails in configurations that have infiniband support
in a loadable module but drbd built-in:

ERROR: modpost: "rdma_bind_addr" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_listen" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_destroy_id" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_destroy_qp" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_disconnect" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "__rdma_create_kernel_id" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_resolve_route" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_reject" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_accept" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!
ERROR: modpost: "rdma_create_qp" [drivers/block/drbd/drbd_transport_rdma.ko] undefined!

Address this by moving the logic from Makefile into Kconfig and
describing the two conditions in which rdma transport can be used
in drbd.

Fixes: 038cb6e644e4 ("drbd: add RDMA transport implementation")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>