phy: renesas: rcar-gen3-usb2: Drop local devm_mux_state_get_optional()
Now the mux core provides devm_mux_state_get_optional():

    drivers/phy/renesas/phy-rcar-gen3-usb2.c:944:1: error: static declaration of ‘devm_mux_state_get_optional’ follows non-static
     declaration
      944 | devm_mux_state_get_optional(struct device *dev, const char *mux_name)
	  | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/phy/renesas/phy-rcar-gen3-usb2.c:20:
    include/linux/mux/consumer.h:64:19: note: previous declaration of ‘devm_mux_state_get_optional’ with type ‘struct mux_state *(struct device *, const char *)’
       64 | struct mux_state *devm_mux_state_get_optional(struct device *dev, const char *mux_name);
	  |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by dropping the temporary local wrapper.

Fixes: ad314348ceb4fe1f ("mux: Add helper functions for getting optional and selected mux-state")
Fixes: 8bb92fd7a0407792 ("phy: renesas: rcar-gen3-usb2: Use mux-state for phyrst management")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>