selftests/livepatch: fix test-state.sh execution error
$ sudo ./test-state.sh
TEST: system state modification ... not ok

- expected
+ result
 % insmod test_modules/test_klp_state.ko
 livepatch: enabling patch 'test_klp_state'
-livepatch: 'test_klp_state': initializing patching transition
+transition: 'test_klp_state': initializing patching transition
 test_klp_state: pre_patch_callback: vmlinux
 test_klp_state: allocate_loglevel_state: allocating space to store console_loglevel
-livepatch: 'test_klp_state': starting patching transition
-livepatch: 'test_klp_state': completing patching transition
+transition: 'test_klp_state': starting patching transition
+transition: 'test_klp_state': completing patching transition
 test_klp_state: post_patch_callback: vmlinux
 test_klp_state: fix_console_loglevel: fixing console_loglevel
-livepatch: 'test_klp_state': patching complete
+transition: 'test_klp_state': patching complete
 % echo 0 > /sys/kernel/livepatch/test_klp_state/enabled
-livepatch: 'test_klp_state': initializing unpatching transition
+transition: 'test_klp_state': initializing unpatching transition
 test_klp_state: pre_unpatch_callback: vmlinux
 test_klp_state: restore_console_loglevel: restoring console_loglevel
-livepatch: 'test_klp_state': starting unpatching transition
-livepatch: 'test_klp_state': completing unpatching transition
+transition: 'test_klp_state': starting unpatching transition
+transition: 'test_klp_state': completing unpatching transition
 test_klp_state: post_unpatch_callback: vmlinux
 test_klp_state: free_loglevel_state: freeing space for the stored console_loglevel
-livepatch: 'test_klp_state': unpatching complete
+transition: 'test_klp_state': unpatching complete
 % rmmod test_klp_state

ERROR: livepatch kselftest(s) failed

The issue arises due to a mismatch in expected log output during livepatch
transition. Specifically, the logs previously contained "livepatch:" but have
now been updated to "transition:". This results in test failures when comparing
the output with the expected values.

This patch updates the expected test output to reflect the new log format.

Signed-off-by: George Guo <guodongtai@kylinos.cn>