drivers: acpi: arm64: thermal_cpufreq: export module
The following build error shows up when building an allmodconfig kernel
on arch=arm64:

ERROR: modpost: "acpi_arch_thermal_cpufreq_pctg" [drivers/acpi/processor.ko] undefined!
make[3]: *** [/next/scripts/Makefile.modpost:145: Module.symvers] Error 1
make[3]: Target '__modpost' not remade because of errors.
make[2]: *** [/tmp/next/Makefile:1876: modpost] Error 2
make[2]: Target '__all' not remade because of errors.
make[1]: *** [/tmp/next/Makefile:243: __sub-make] Error 2
make[1]: Target '__all' not remade because of errors.
make: *** [Makefile:243: __sub-make] Error 2
make: Target '__all' not remade because of errors.

Solve the issue by export acpi_arch_thermal_cpufreq_pctg() since the
function are used in function 'acpi_thermal_cpufreq_config()'.

Fixes: a02f66bb3cf4 ("ACPI: Move ACPI_HOTPLUG_CPU to be disabled on arm64 and riscv")
Suggested-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>