btrfs: send: don't send rmdir for same target multiple times with multi hardlink situation
In commit 29d6d30f5c8a("Btrfs: send, don't send rmdir for same target
multiple times") has fixed the issue that btrfs send rmdir for same
target multiple times by keep the last_dir_ino_rm and compare with
it before sending rmdir. But there have a corner case that if the
instructions that rm same dir not in a row, the fix will not work.

Hardlinks of file are store in the same INODE_REF item, and if the
number of hardlinks is too large and exceed the size of one metadata
node can store, it will use INODE_EXTREF to store. The key of
INODE_EXTREF is (inode_id, INODE_EXTREF, hash of name), so if there are
two dir have hardlinks to the same file, the INODE_EXTREF items will
have cross sequence with two dir like below:
    item 0 key (404 INODE_EXTREF 111512) itemoff 16239 itemsize 44
        inode extref index 4825 parent 403 namelen 4 name: 4824
        inode extref index 5825 parent 402 namelen 4 name: 5824
    item 1 key (404 INODE_EXTREF 398645) itemoff 16195 itemsize 44
        inode extref index 4569 parent 403 namelen 4 name: 4568
        inode extref index 5569 parent 402 namelen 4 name: 5568

So when doing btrfs send, the instructions that rmdir for the two dir
are not in a row, and the previous fix will not work.

We use rbtree to keep all the dirs that already add into `check_dirs`,
and compare with it before add a new dir into it.

The reproduce steps are as below:
    $ mkfs.btrfs -f /dev/sdb3
    $ mount /dev/sdb3 /mnt/
    $ mkdir /mnt/a /mnt/b
    $ echo 123 > /mnt/a/foo
    $ for i in $(seq 1 10000); do ln /mnt/a/foo /mnt/a/foo.$i; ln /mnt/a/foo /mnt/b/foo.$i; done
    $ btrfs subvolume snapshot -r /mnt/ /mnt/snap1
    $ btrfs send /mnt/snap1 -f /tmp/base.send
    $ rm -r /mnt/a /mnt/b
    $ btrfs subvolume snapshot -r /mnt/ /mnt/snap2
    $ btrfs send -p /mnt/snap1 /mnt/snap2 -f /tmp/incremental.send

    $ umount /mnt
    $ mkfs.btrfs -f /dev/sdb3
    $ mount /dev/sdb3 /mnt
    $ btrfs receive /mnt -f /tmp/base.send
    $ btrfs receive /mnt -f /tmp/incremental.send

The second btrfs receive command failed with:
    ERROR: rmdir o4205145-4190-0 failed: No such file or directory

Fixes: 29d6d30f5c8a("Btrfs: send, don't send rmdir for same target multiple times")
Signed-off-by: Ting-Chang Hou <tchou@synology.com>