selftests: pid_namespace: Fix missing mount headers in pid_max.c
Fix compilation errors in pid_max.c by including <sys/mount.h>, which
provides definitions for mount(), umount2(), MS_PRIVATE, MS_REC, and
MNT_DETACH.

Without this header, the build fails with implicit declarations and
undefined constants during selftest compilation.

Changes since v1:
- Included example build errors below for clarity

Compile error:
pid_max.c: In function ‘pid_max_cb’:
pid_max.c:42:15: warning: implicit declaration of function ‘mount’ [-Wimplicit-function-declaration]
   42 |         ret = mount("", "/", NULL, MS_PRIVATE | MS_REC, 0);
      |               ^~~~~
pid_max.c:42:36: error: ‘MS_PRIVATE’ undeclared; did you mean ‘MAP_PRIVATE’?
pid_max.c:42:49: error: ‘MS_REC’ undeclared
pid_max.c:48:9: warning: implicit declaration of function ‘umount2’
pid_max.c:48:26: error: ‘MNT_DETACH’ undeclared

[...output trimmed for brevity...]

make: *** [../lib.mk:222: /linux_mainline/tools/testing/selftests/pid_namespace/pid_max] Error 1

Signed-off-by: Moon Hee Lee <moonhee.lee.ca@gmail.com>