sched/fair: avoid integer overflow warning for fair_server_period_max;
The clalculation of fair_server_period_max includes an integer overflow:

In file included from kernel/sched/build_utility.c:72:
kernel/sched/debug.c:341:57: error: integer overflow in expression of type 'long int' results in '-100663296' [-Werror=overflow]
  341 | static unsigned long fair_server_period_max = (1 << 22) * NSEC_PER_USEC; /* ~4 seconds */

Avoids this by using an unsigned constant to start with.

Fixes: d741f297bcea ("sched/fair: Fair server interface")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>