kexec: Remove unused code in kimage_load_cma_segment()
clang is not happy about set but unused variable:

kernel/kexec_core.c:745:16: error: variable 'maddr' set but not used [-Werror,-Wunused-but-set-variable]
  745 |         unsigned long maddr;
      |                       ^
1 error generated.

Fix the compilation breakage (`make W=1` build) by removing unused variable.

Fixes: 07d24902977e ("kexec: enable CMA based contiguous allocation")
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>