ice: move netlist check functions to ice_common.c
The ice_ptp_hw.c file has a few functions which check for whether the
device netlist has a node indicating hardware support for certain features.
These checks don't really make sense to be in ice_ptp_hw.c. In addition,
their names could be confusing as they just say "is_present" but really are
checking the netlist.

Additionally, these functions are only compiled into the ice module if
CONFIG_PTP_1588_CLOCK is enabled. They are used in ice_lib.c which is
unconditionally compiled, so this can result in build errors if the PTP
support is disabled:

ld: vmlinux.o: in function `ice_init_feature_support':
(.text+0x8702b8): undefined reference to `ice_is_phy_rclk_present'
ld: (.text+0x8702cd): undefined reference to `ice_is_cgu_present'
ld: (.text+0x8702d9): undefined reference to `ice_is_clock_mux_present_e810t'

To fix this, we need to define these functions outside of ice_ptp.c or
ice_ptp_hw.c.

The ice_common.c already hace ice_is_gps_in_netlist. Move the similar
functions in ice_ptp_hw.c into ice_common.c, renaming them to use the
postfix "_in_netlist" to match the GPS check. Where appropriate, also drop
the _e810t postfix as well.

This also makes the ice_find_netlist_node only called from within
ice_common.c, so its safe to mark it static and stop declaring it in the
ice_common.h header.

Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>