btrfs: Fix use of GCC_VERSION in messages.h
Clang warns (or errors with CONFIG_WERROR=y):

  fs/btrfs/messages.h:188:5: error: 'GCC_VERSION' is not defined, evaluates to 0 [-Werror,-Wundef]
    188 | #if GCC_VERSION >= 80000
        |     ^

GCC_VERSION is defined in compiler-gcc.h, which is not included when
building with clang. Use the always defined Kconfig symbol,
CONFIG_GCC_VERSION, to do the comparison.

Additionally, as a comment above this #ifdef notes, clang supports
__VA_OPT__, which is really what is needed for this block to function.
Include a check for CONFIG_CC_IS_CLANG as well, since clang 13 is the
minimum supported version for building the kernel.

Fixes: 14d740332aa0 ("btrfs: enhance ASSERT() to take optional format string")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>