kbuild: Require gcc-9 for s390
Upcoming changes to s390 specific inline assemblies require the usage of
strings as immediate input operands. This works only with gcc-9 and newer
compilers. With gcc-8 this leads to a compile error:

void bar(void) { asm volatile("" :: "i" ("foo")); }

Results in:

In function 'bar':
 warning: asm operand 0 probably doesn't match constraints
  asm volatile("" :: "i" ("foo"));
  ^~~
 error: impossible constraint in 'asm'

Bump the minimal gcc version from gcc-8 to gcc-9 for s390 to solve this
problem.

Signed-off-by: Heiko Carstens <hca@linux.ibm.com>