net: enetc: fix NTMP build dependency
When the new library driver is in a loadable module, but the enetc
core driver is built-in, the kernel fails to link:

aarch64-linux-ld: drivers/net/ethernet/freescale/enetc/enetc_cbdr.o: in function `enetc4_teardown_cbdr':
enetc_cbdr.c:(.text+0x70): undefined reference to `ntmp_free_cbdr'
aarch64-linux-ld: drivers/net/ethernet/freescale/enetc/enetc_cbdr.o: in function `enetc4_get_rss_table':
enetc_cbdr.c:(.text+0x98): undefined reference to `ntmp_rsst_query_entry'
aarch64-linux-ld: drivers/net/ethernet/freescale/enetc/enetc_cbdr.o: in function `enetc4_set_rss_table':
enetc_cbdr.c:(.text+0xb8): undefined reference to `ntmp_rsst_update_entry'
aarch64-linux-ld: drivers/net/ethernet/freescale/enetc/enetc_cbdr.o: in function `enetc4_setup_cbdr':
enetc_cbdr.c:(.text+0x438): undefined reference to `ntmp_init_cbdr'

Move the ntmp code into the core module itself to avoid this link error.

Fixes: 4701073c3deb ("net: enetc: add initial netc-lib driver to support NTMP")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>